// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pqrs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_pqrs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_pqrs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_pqrs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_pqrs_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_pqrs_2eproto;
class LTLtest;
struct LTLtestDefaultTypeInternal;
extern LTLtestDefaultTypeInternal _LTLtest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::LTLtest* Arena::CreateMaybeMessage<::LTLtest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class LTLtest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:LTLtest) */ {
 public:
  inline LTLtest() : LTLtest(nullptr) {}
  ~LTLtest() override;
  explicit PROTOBUF_CONSTEXPR LTLtest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LTLtest(const LTLtest& from);
  LTLtest(LTLtest&& from) noexcept
    : LTLtest() {
    *this = ::std::move(from);
  }

  inline LTLtest& operator=(const LTLtest& from) {
    CopyFrom(from);
    return *this;
  }
  inline LTLtest& operator=(LTLtest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LTLtest& default_instance() {
    return *internal_default_instance();
  }
  static inline const LTLtest* internal_default_instance() {
    return reinterpret_cast<const LTLtest*>(
               &_LTLtest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LTLtest& a, LTLtest& b) {
    a.Swap(&b);
  }
  inline void Swap(LTLtest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LTLtest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LTLtest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LTLtest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LTLtest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const LTLtest& from) {
    LTLtest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LTLtest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "LTLtest";
  }
  protected:
  explicit LTLtest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPFieldNumber = 1,
    kQFieldNumber = 2,
    kRFieldNumber = 3,
    kSFieldNumber = 4,
    kTFieldNumber = 5,
    kUFieldNumber = 6,
    kVFieldNumber = 7,
    kWFieldNumber = 8,
  };
  // optional bool p = 1;
  bool has_p() const;
  private:
  bool _internal_has_p() const;
  public:
  void clear_p();
  bool p() const;
  void set_p(bool value);
  private:
  bool _internal_p() const;
  void _internal_set_p(bool value);
  public:

  // optional bool q = 2;
  bool has_q() const;
  private:
  bool _internal_has_q() const;
  public:
  void clear_q();
  bool q() const;
  void set_q(bool value);
  private:
  bool _internal_q() const;
  void _internal_set_q(bool value);
  public:

  // optional bool r = 3;
  bool has_r() const;
  private:
  bool _internal_has_r() const;
  public:
  void clear_r();
  bool r() const;
  void set_r(bool value);
  private:
  bool _internal_r() const;
  void _internal_set_r(bool value);
  public:

  // optional bool s = 4;
  bool has_s() const;
  private:
  bool _internal_has_s() const;
  public:
  void clear_s();
  bool s() const;
  void set_s(bool value);
  private:
  bool _internal_s() const;
  void _internal_set_s(bool value);
  public:

  // optional bool t = 5;
  bool has_t() const;
  private:
  bool _internal_has_t() const;
  public:
  void clear_t();
  bool t() const;
  void set_t(bool value);
  private:
  bool _internal_t() const;
  void _internal_set_t(bool value);
  public:

  // optional bool u = 6;
  bool has_u() const;
  private:
  bool _internal_has_u() const;
  public:
  void clear_u();
  bool u() const;
  void set_u(bool value);
  private:
  bool _internal_u() const;
  void _internal_set_u(bool value);
  public:

  // optional bool v = 7;
  bool has_v() const;
  private:
  bool _internal_has_v() const;
  public:
  void clear_v();
  bool v() const;
  void set_v(bool value);
  private:
  bool _internal_v() const;
  void _internal_set_v(bool value);
  public:

  // optional bool w = 8;
  bool has_w() const;
  private:
  bool _internal_has_w() const;
  public:
  void clear_w();
  bool w() const;
  void set_w(bool value);
  private:
  bool _internal_w() const;
  void _internal_set_w(bool value);
  public:

  // @@protoc_insertion_point(class_scope:LTLtest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    bool p_;
    bool q_;
    bool r_;
    bool s_;
    bool t_;
    bool u_;
    bool v_;
    bool w_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pqrs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LTLtest

// optional bool p = 1;
inline bool LTLtest::_internal_has_p() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LTLtest::has_p() const {
  return _internal_has_p();
}
inline void LTLtest::clear_p() {
  _impl_.p_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool LTLtest::_internal_p() const {
  return _impl_.p_;
}
inline bool LTLtest::p() const {
  // @@protoc_insertion_point(field_get:LTLtest.p)
  return _internal_p();
}
inline void LTLtest::_internal_set_p(bool value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.p_ = value;
}
inline void LTLtest::set_p(bool value) {
  _internal_set_p(value);
  // @@protoc_insertion_point(field_set:LTLtest.p)
}

// optional bool q = 2;
inline bool LTLtest::_internal_has_q() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LTLtest::has_q() const {
  return _internal_has_q();
}
inline void LTLtest::clear_q() {
  _impl_.q_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool LTLtest::_internal_q() const {
  return _impl_.q_;
}
inline bool LTLtest::q() const {
  // @@protoc_insertion_point(field_get:LTLtest.q)
  return _internal_q();
}
inline void LTLtest::_internal_set_q(bool value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.q_ = value;
}
inline void LTLtest::set_q(bool value) {
  _internal_set_q(value);
  // @@protoc_insertion_point(field_set:LTLtest.q)
}

// optional bool r = 3;
inline bool LTLtest::_internal_has_r() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LTLtest::has_r() const {
  return _internal_has_r();
}
inline void LTLtest::clear_r() {
  _impl_.r_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool LTLtest::_internal_r() const {
  return _impl_.r_;
}
inline bool LTLtest::r() const {
  // @@protoc_insertion_point(field_get:LTLtest.r)
  return _internal_r();
}
inline void LTLtest::_internal_set_r(bool value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.r_ = value;
}
inline void LTLtest::set_r(bool value) {
  _internal_set_r(value);
  // @@protoc_insertion_point(field_set:LTLtest.r)
}

// optional bool s = 4;
inline bool LTLtest::_internal_has_s() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool LTLtest::has_s() const {
  return _internal_has_s();
}
inline void LTLtest::clear_s() {
  _impl_.s_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool LTLtest::_internal_s() const {
  return _impl_.s_;
}
inline bool LTLtest::s() const {
  // @@protoc_insertion_point(field_get:LTLtest.s)
  return _internal_s();
}
inline void LTLtest::_internal_set_s(bool value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.s_ = value;
}
inline void LTLtest::set_s(bool value) {
  _internal_set_s(value);
  // @@protoc_insertion_point(field_set:LTLtest.s)
}

// optional bool t = 5;
inline bool LTLtest::_internal_has_t() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool LTLtest::has_t() const {
  return _internal_has_t();
}
inline void LTLtest::clear_t() {
  _impl_.t_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool LTLtest::_internal_t() const {
  return _impl_.t_;
}
inline bool LTLtest::t() const {
  // @@protoc_insertion_point(field_get:LTLtest.t)
  return _internal_t();
}
inline void LTLtest::_internal_set_t(bool value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.t_ = value;
}
inline void LTLtest::set_t(bool value) {
  _internal_set_t(value);
  // @@protoc_insertion_point(field_set:LTLtest.t)
}

// optional bool u = 6;
inline bool LTLtest::_internal_has_u() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool LTLtest::has_u() const {
  return _internal_has_u();
}
inline void LTLtest::clear_u() {
  _impl_.u_ = false;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline bool LTLtest::_internal_u() const {
  return _impl_.u_;
}
inline bool LTLtest::u() const {
  // @@protoc_insertion_point(field_get:LTLtest.u)
  return _internal_u();
}
inline void LTLtest::_internal_set_u(bool value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.u_ = value;
}
inline void LTLtest::set_u(bool value) {
  _internal_set_u(value);
  // @@protoc_insertion_point(field_set:LTLtest.u)
}

// optional bool v = 7;
inline bool LTLtest::_internal_has_v() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool LTLtest::has_v() const {
  return _internal_has_v();
}
inline void LTLtest::clear_v() {
  _impl_.v_ = false;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline bool LTLtest::_internal_v() const {
  return _impl_.v_;
}
inline bool LTLtest::v() const {
  // @@protoc_insertion_point(field_get:LTLtest.v)
  return _internal_v();
}
inline void LTLtest::_internal_set_v(bool value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.v_ = value;
}
inline void LTLtest::set_v(bool value) {
  _internal_set_v(value);
  // @@protoc_insertion_point(field_set:LTLtest.v)
}

// optional bool w = 8;
inline bool LTLtest::_internal_has_w() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool LTLtest::has_w() const {
  return _internal_has_w();
}
inline void LTLtest::clear_w() {
  _impl_.w_ = false;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline bool LTLtest::_internal_w() const {
  return _impl_.w_;
}
inline bool LTLtest::w() const {
  // @@protoc_insertion_point(field_get:LTLtest.w)
  return _internal_w();
}
inline void LTLtest::_internal_set_w(bool value) {
  _impl_._has_bits_[0] |= 0x00000080u;
  _impl_.w_ = value;
}
inline void LTLtest::set_w(bool value) {
  _internal_set_w(value);
  // @@protoc_insertion_point(field_set:LTLtest.w)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_pqrs_2eproto
