// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pqrs.proto

#include "pqrs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR LTLtest::LTLtest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.p_)*/false
  , /*decltype(_impl_.q_)*/false
  , /*decltype(_impl_.r_)*/false
  , /*decltype(_impl_.s_)*/false
  , /*decltype(_impl_.t_)*/false
  , /*decltype(_impl_.u_)*/false
  , /*decltype(_impl_.v_)*/false
  , /*decltype(_impl_.w_)*/false} {}
struct LTLtestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LTLtestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LTLtestDefaultTypeInternal() {}
  union {
    LTLtest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LTLtestDefaultTypeInternal _LTLtest_default_instance_;
static ::_pb::Metadata file_level_metadata_pqrs_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_pqrs_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_pqrs_2eproto = nullptr;

const uint32_t TableStruct_pqrs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.p_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.q_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.r_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.s_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.t_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.u_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.v_),
  PROTOBUF_FIELD_OFFSET(::LTLtest, _impl_.w_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 14, -1, sizeof(::LTLtest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_LTLtest_default_instance_._instance,
};

const char descriptor_table_protodef_pqrs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\npqrs.proto\"a\n\007LTLtest\022\t\n\001p\030\001 \001(\010\022\t\n\001q\030"
  "\002 \001(\010\022\t\n\001r\030\003 \001(\010\022\t\n\001s\030\004 \001(\010\022\t\n\001t\030\005 \001(\010\022\t"
  "\n\001u\030\006 \001(\010\022\t\n\001v\030\007 \001(\010\022\t\n\001w\030\010 \001(\010B\002H\001"
  ;
static ::_pbi::once_flag descriptor_table_pqrs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_pqrs_2eproto = {
    false, false, 115, descriptor_table_protodef_pqrs_2eproto,
    "pqrs.proto",
    &descriptor_table_pqrs_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_pqrs_2eproto::offsets,
    file_level_metadata_pqrs_2eproto, file_level_enum_descriptors_pqrs_2eproto,
    file_level_service_descriptors_pqrs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_pqrs_2eproto_getter() {
  return &descriptor_table_pqrs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_pqrs_2eproto(&descriptor_table_pqrs_2eproto);

// ===================================================================

class LTLtest::_Internal {
 public:
  using HasBits = decltype(std::declval<LTLtest>()._impl_._has_bits_);
  static void set_has_p(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_q(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_r(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_s(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_t(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_u(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_v(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_w(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
};

LTLtest::LTLtest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:LTLtest)
}
LTLtest::LTLtest(const LTLtest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LTLtest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.p_){}
    , decltype(_impl_.q_){}
    , decltype(_impl_.r_){}
    , decltype(_impl_.s_){}
    , decltype(_impl_.t_){}
    , decltype(_impl_.u_){}
    , decltype(_impl_.v_){}
    , decltype(_impl_.w_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.p_, &from._impl_.p_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.w_) -
    reinterpret_cast<char*>(&_impl_.p_)) + sizeof(_impl_.w_));
  // @@protoc_insertion_point(copy_constructor:LTLtest)
}

inline void LTLtest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.p_){false}
    , decltype(_impl_.q_){false}
    , decltype(_impl_.r_){false}
    , decltype(_impl_.s_){false}
    , decltype(_impl_.t_){false}
    , decltype(_impl_.u_){false}
    , decltype(_impl_.v_){false}
    , decltype(_impl_.w_){false}
  };
}

LTLtest::~LTLtest() {
  // @@protoc_insertion_point(destructor:LTLtest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LTLtest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LTLtest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LTLtest::Clear() {
// @@protoc_insertion_point(message_clear_start:LTLtest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    ::memset(&_impl_.p_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.w_) -
        reinterpret_cast<char*>(&_impl_.p_)) + sizeof(_impl_.w_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LTLtest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bool p = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_p(&has_bits);
          _impl_.p_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool q = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_q(&has_bits);
          _impl_.q_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool r = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_r(&has_bits);
          _impl_.r_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool s = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_s(&has_bits);
          _impl_.s_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool t = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_t(&has_bits);
          _impl_.t_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool u = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_u(&has_bits);
          _impl_.u_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool v = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_v(&has_bits);
          _impl_.v_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bool w = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 64)) {
          _Internal::set_has_w(&has_bits);
          _impl_.w_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LTLtest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:LTLtest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bool p = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_p(), target);
  }

  // optional bool q = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_q(), target);
  }

  // optional bool r = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_r(), target);
  }

  // optional bool s = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_s(), target);
  }

  // optional bool t = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_t(), target);
  }

  // optional bool u = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_u(), target);
  }

  // optional bool v = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(7, this->_internal_v(), target);
  }

  // optional bool w = 8;
  if (cached_has_bits & 0x00000080u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(8, this->_internal_w(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:LTLtest)
  return target;
}

size_t LTLtest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:LTLtest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bool p = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 1;
    }

    // optional bool q = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional bool r = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 + 1;
    }

    // optional bool s = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 1;
    }

    // optional bool t = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 1;
    }

    // optional bool u = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 1;
    }

    // optional bool v = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 + 1;
    }

    // optional bool w = 8;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 + 1;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LTLtest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LTLtest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LTLtest::GetClassData() const { return &_class_data_; }


void LTLtest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LTLtest*>(&to_msg);
  auto& from = static_cast<const LTLtest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LTLtest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.p_ = from._impl_.p_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.q_ = from._impl_.q_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.r_ = from._impl_.r_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.s_ = from._impl_.s_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.t_ = from._impl_.t_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.u_ = from._impl_.u_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.v_ = from._impl_.v_;
    }
    if (cached_has_bits & 0x00000080u) {
      _this->_impl_.w_ = from._impl_.w_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LTLtest::CopyFrom(const LTLtest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LTLtest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LTLtest::IsInitialized() const {
  return true;
}

void LTLtest::InternalSwap(LTLtest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LTLtest, _impl_.w_)
      + sizeof(LTLtest::_impl_.w_)
      - PROTOBUF_FIELD_OFFSET(LTLtest, _impl_.p_)>(
          reinterpret_cast<char*>(&_impl_.p_),
          reinterpret_cast<char*>(&other->_impl_.p_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LTLtest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_pqrs_2eproto_getter, &descriptor_table_pqrs_2eproto_once,
      file_level_metadata_pqrs_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::LTLtest*
Arena::CreateMaybeMessage< ::LTLtest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::LTLtest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
