version: '3.8'

services:
  zenoh_bridge:
    build: ./zenoh_bridge   # Path to Dockerfile for zenoh_bridge
    container_name: zenoh_bridge
    networks:
      - zenoh-net
    command: ["zenohd", "--bind", "tcp/0.0.0.0:7447", "--peer", "tcp://esmini_zenoh:7448"]
    ports:
      - "7447:7447"

  esmini_zenoh:
    build: ./esmini_zenoh   # Path to Dockerfile for esmini_zenoh
    container_name: esmini_zenoh
    networks:
      - zenoh-net
    command: ["zenohd", "--bind", "tcp/0.0.0.0:7448", "--peer", "tcp://zenoh_bridge:7447"]
    ports:
      - "7448:7448"

networks:
  zenoh-net:
    driver: bridge