site_name: reelay
repo_url: https://github.com/doganulus/reelay
docs_dir: docs
edit_uri: 'edit/master/docs/'
theme:
  name: material
  include_search_page: false
  # search_index_only: true
  language: en
  palette:
    primary: green
    accent: lime
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "device_hub"

nav:
  - Home: 'index.md'
  - Motivation: 'install.md'
  - Getting Started:
    - 'Install' : 'install.md'
    - 'From Python' : 'install.md'
    - 'From Terminal' : 'install.md'
    - 'From Docker': 'docker.md'
  - User Guide: 
    - 'Specifications' : 'literature.md'
    - 'Time Models' : 'literature.md'
  - Advanced Topics: 
    - 'Time Models' : 'literature.md'
    - 'Benchmarking' : 'performance.md'
    - 'References' : 'literature.md'

  - About:
    - 'License' : 'license.md'
    - 'Naming': 'naming.md'
# - 'License': 'license.md'
# - 'Release Notes': 'release-notes.md'

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.codehilite:
      guess_lang: false

plugins:
  - search
  - minify:
      minify_html: true