site_name: Reelay
repo_url: https://github.com/doganulus/reelay
docs_dir: docs
edit_uri: 'edit/master/docs/'
theme:
  name: material
  include_search_page: false
  # search_index_only: true
  language: en
  palette:
    primary: black
    accent: red
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/favicon.png
  logo: assets/whitelogo_boxed.png


nav:
  - Home: 'index.md'

  # - Motivation: 'motivation.md'
  - Install:
    - 'From Source' : 'install.md'
    - 'Docker Image' : 'docker.md'

  - Get Started:
    - 'Tutorial: Intro' : 'gs_intro.md'
    - 'How to use from C++' : 'gs_cpp.md'
    - 'How to use from Python' : 'gs_python.md'
    - 'How to use from CLI' : 'gs_cli.md'

  - User Guide: 
    - 'Temporal Behaviors' : 'behaviors.md'
    - 'Formal Specifications' : 'specification.md'
    - 'C++ API' : 'cpp_api.md'
    - 'Python API' : 'python_api.md'
    - 'Benchmarking' : 'performance.md'
    - 'Release Notes': 'release_notes.md'

  - Advanced Topics: 
    - 'Time Models' : 'time_models.md'
    - 'Past Temporal Logic' : 'past_temporal_logic.md'
    - 'Regular Expressions' : 'regular_expressions.md'
    - 'Sequential Networks' : 'sequential_networks.md'
    - 'References' : 'literature.md'

  - About:
    - 'Author' : 'author.md'
    - 'License' : 'license.md'
    - 'Naming': 'naming.md'

# - 'License': 'license.md'
# - 'Release Notes': 'release-notes.md'

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.codehilite:
      guess_lang: false

plugins:
  - search
  - minify:
      minify_html: true

google_analytics: ['UA-153753179-1', 'mkdocs.org']