site_name: Reelay
repo_url: https://github.com/doganulus/reelay
docs_dir: docs
edit_uri: 'edit/master/docs/'
theme:
  name: material
  include_search_page: false
  # search_index_only: true
  language: en
  palette:
    primary: green
    accent: lime
  font:
    text: Ubuntu
    code: Ubuntu Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "device_hub"

nav:
  - Home: 'index.md'

  - Motivation: 'motivation.md'
  - Install:
    - 'From Source' : 'install.md'
    - 'Docker Image' : 'docker.md'

  - Get Started:
    - 'An Example' : 'gs_intro.md'
    - 'C++ Tutorial' : 'gs_cpp.md'
    - 'Python Tutorial' : 'gs_python.md'
    - 'CLI Tutorial' : 'gs_cli.md'

  - User Guide: 
    - 'Temporal Behaviors' : 'behaviors.md'
    - 'Formal Specifications' : 'specification.md'
    - 'C++ API' : 'cpp_api.md'
    - 'Python API' : 'python_api.md'
    - 'Benchmarking' : 'performance.md'
    - 'Release Notes': 'release_notes.md'

  - Advanced Topics: 
    - 'Time Models' : 'time_models_advanced.md'
    - 'Temporal Logic' : 'temporal_logic.md'
    - 'Regular Expressions' : 'regular_expressions.md'
    - 'Sequential Networks' : 'sequential_networks.md'
    - 'References' : 'literature.md'

  - About:
    - 'Author' : 'author.md'
    - 'License' : 'license.md'
    - 'Naming': 'naming.md'

# - 'License': 'license.md'
# - 'Release Notes': 'release-notes.md'

markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.codehilite:
      guess_lang: false

plugins:
  - search
  - minify:
      minify_html: true