// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSICOMMON_OSI3_H_
#define FLATBUFFERS_GENERATED_OSICOMMON_OSI3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace osi3 {

struct Vector3d;
struct Vector3dBuilder;

struct Vector2d;
struct Vector2dBuilder;

struct Timestamp;
struct TimestampBuilder;

struct Dimension3d;
struct Dimension3dBuilder;

struct Orientation3d;
struct Orientation3dBuilder;

struct Identifier;
struct IdentifierBuilder;

struct ExternalReference;
struct ExternalReferenceBuilder;

struct MountingPosition;
struct MountingPositionBuilder;

struct Spherical3d;
struct Spherical3dBuilder;

struct LogicalLaneAssignment;
struct LogicalLaneAssignmentBuilder;

struct BoundingBox;
struct BoundingBoxBuilder;

struct BaseStationary;
struct BaseStationaryBuilder;

struct BaseMoving;
struct BaseMovingBuilder;

struct StatePoint;
struct StatePointBuilder;

struct WavelengthData;
struct WavelengthDataBuilder;

struct SpatialSignalStrength;
struct SpatialSignalStrengthBuilder;

struct ColorGrey;
struct ColorGreyBuilder;

struct ColorRGB;
struct ColorRGBBuilder;

struct ColorRGBIR;
struct ColorRGBIRBuilder;

struct ColorHSV;
struct ColorHSVBuilder;

struct ColorLUV;
struct ColorLUVBuilder;

struct ColorCMYK;
struct ColorCMYKBuilder;

struct ColorDescription;
struct ColorDescriptionBuilder;

struct Pedalry;
struct PedalryBuilder;

struct VehicleSteeringWheel;
struct VehicleSteeringWheelBuilder;

struct GeodeticPosition;
struct GeodeticPositionBuilder;

struct KeyValuePair;
struct KeyValuePairBuilder;

struct Polygon3d;
struct Polygon3dBuilder;

enum BoundingBoxType : int8_t {
  BoundingBoxType_TYPE_UNKNOWN = 0,
  BoundingBoxType_TYPE_OTHER = 1,
  BoundingBoxType_TYPE_BASE_STRUCTURE = 2,
  BoundingBoxType_TYPE_PROTRUDING_STRUCTURE = 3,
  BoundingBoxType_TYPE_CARGO = 4,
  BoundingBoxType_TYPE_DOOR = 5,
  BoundingBoxType_TYPE_SIDE_MIRROR = 6,
  BoundingBoxType_MIN = BoundingBoxType_TYPE_UNKNOWN,
  BoundingBoxType_MAX = BoundingBoxType_TYPE_SIDE_MIRROR
};

inline const BoundingBoxType (&EnumValuesBoundingBoxType())[7] {
  static const BoundingBoxType values[] = {
    BoundingBoxType_TYPE_UNKNOWN,
    BoundingBoxType_TYPE_OTHER,
    BoundingBoxType_TYPE_BASE_STRUCTURE,
    BoundingBoxType_TYPE_PROTRUDING_STRUCTURE,
    BoundingBoxType_TYPE_CARGO,
    BoundingBoxType_TYPE_DOOR,
    BoundingBoxType_TYPE_SIDE_MIRROR
  };
  return values;
}

inline const char * const *EnumNamesBoundingBoxType() {
  static const char * const names[8] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_BASE_STRUCTURE",
    "TYPE_PROTRUDING_STRUCTURE",
    "TYPE_CARGO",
    "TYPE_DOOR",
    "TYPE_SIDE_MIRROR",
    nullptr
  };
  return names;
}

inline const char *EnumNameBoundingBoxType(BoundingBoxType e) {
  if (::flatbuffers::IsOutRange(e, BoundingBoxType_TYPE_UNKNOWN, BoundingBoxType_TYPE_SIDE_MIRROR)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBoundingBoxType()[index];
}

struct Vector3d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vector3dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  double x() const {
    return GetField<double>(VT_X, 0.0);
  }
  double y() const {
    return GetField<double>(VT_Y, 0.0);
  }
  double z() const {
    return GetField<double>(VT_Z, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_X, 8) &&
           VerifyField<double>(verifier, VT_Y, 8) &&
           VerifyField<double>(verifier, VT_Z, 8) &&
           verifier.EndTable();
  }
};

struct Vector3dBuilder {
  typedef Vector3d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(double x) {
    fbb_.AddElement<double>(Vector3d::VT_X, x, 0.0);
  }
  void add_y(double y) {
    fbb_.AddElement<double>(Vector3d::VT_Y, y, 0.0);
  }
  void add_z(double z) {
    fbb_.AddElement<double>(Vector3d::VT_Z, z, 0.0);
  }
  explicit Vector3dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector3d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector3d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector3d> CreateVector3d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double x = 0.0,
    double y = 0.0,
    double z = 0.0) {
  Vector3dBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct Vector2d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vector2dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  double x() const {
    return GetField<double>(VT_X, 0.0);
  }
  double y() const {
    return GetField<double>(VT_Y, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_X, 8) &&
           VerifyField<double>(verifier, VT_Y, 8) &&
           verifier.EndTable();
  }
};

struct Vector2dBuilder {
  typedef Vector2d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(double x) {
    fbb_.AddElement<double>(Vector2d::VT_X, x, 0.0);
  }
  void add_y(double y) {
    fbb_.AddElement<double>(Vector2d::VT_Y, y, 0.0);
  }
  explicit Vector2dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vector2d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vector2d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vector2d> CreateVector2d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double x = 0.0,
    double y = 0.0) {
  Vector2dBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct Timestamp FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TimestampBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SECONDS = 4,
    VT_NANOS = 6
  };
  int64_t seconds() const {
    return GetField<int64_t>(VT_SECONDS, 0);
  }
  uint32_t nanos() const {
    return GetField<uint32_t>(VT_NANOS, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_SECONDS, 8) &&
           VerifyField<uint32_t>(verifier, VT_NANOS, 4) &&
           verifier.EndTable();
  }
};

struct TimestampBuilder {
  typedef Timestamp Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seconds(int64_t seconds) {
    fbb_.AddElement<int64_t>(Timestamp::VT_SECONDS, seconds, 0);
  }
  void add_nanos(uint32_t nanos) {
    fbb_.AddElement<uint32_t>(Timestamp::VT_NANOS, nanos, 0);
  }
  explicit TimestampBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Timestamp> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Timestamp>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Timestamp> CreateTimestamp(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t seconds = 0,
    uint32_t nanos = 0) {
  TimestampBuilder builder_(_fbb);
  builder_.add_seconds(seconds);
  builder_.add_nanos(nanos);
  return builder_.Finish();
}

struct Dimension3d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Dimension3dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LENGTH = 4,
    VT_WIDTH = 6,
    VT_HEIGHT = 8
  };
  double length() const {
    return GetField<double>(VT_LENGTH, 0.0);
  }
  double width() const {
    return GetField<double>(VT_WIDTH, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_LENGTH, 8) &&
           VerifyField<double>(verifier, VT_WIDTH, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           verifier.EndTable();
  }
};

struct Dimension3dBuilder {
  typedef Dimension3d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_length(double length) {
    fbb_.AddElement<double>(Dimension3d::VT_LENGTH, length, 0.0);
  }
  void add_width(double width) {
    fbb_.AddElement<double>(Dimension3d::VT_WIDTH, width, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(Dimension3d::VT_HEIGHT, height, 0.0);
  }
  explicit Dimension3dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Dimension3d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Dimension3d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Dimension3d> CreateDimension3d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double length = 0.0,
    double width = 0.0,
    double height = 0.0) {
  Dimension3dBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_length(length);
  return builder_.Finish();
}

struct Orientation3d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Orientation3dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ROLL = 4,
    VT_PITCH = 6,
    VT_YAW = 8
  };
  double roll() const {
    return GetField<double>(VT_ROLL, 0.0);
  }
  double pitch() const {
    return GetField<double>(VT_PITCH, 0.0);
  }
  double yaw() const {
    return GetField<double>(VT_YAW, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_ROLL, 8) &&
           VerifyField<double>(verifier, VT_PITCH, 8) &&
           VerifyField<double>(verifier, VT_YAW, 8) &&
           verifier.EndTable();
  }
};

struct Orientation3dBuilder {
  typedef Orientation3d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_roll(double roll) {
    fbb_.AddElement<double>(Orientation3d::VT_ROLL, roll, 0.0);
  }
  void add_pitch(double pitch) {
    fbb_.AddElement<double>(Orientation3d::VT_PITCH, pitch, 0.0);
  }
  void add_yaw(double yaw) {
    fbb_.AddElement<double>(Orientation3d::VT_YAW, yaw, 0.0);
  }
  explicit Orientation3dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Orientation3d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Orientation3d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Orientation3d> CreateOrientation3d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double roll = 0.0,
    double pitch = 0.0,
    double yaw = 0.0) {
  Orientation3dBuilder builder_(_fbb);
  builder_.add_yaw(yaw);
  builder_.add_pitch(pitch);
  builder_.add_roll(roll);
  return builder_.Finish();
}

struct Identifier FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IdentifierBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE = 4
  };
  uint64_t value() const {
    return GetField<uint64_t>(VT_VALUE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct IdentifierBuilder {
  typedef Identifier Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value(uint64_t value) {
    fbb_.AddElement<uint64_t>(Identifier::VT_VALUE, value, 0);
  }
  explicit IdentifierBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Identifier> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Identifier>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Identifier> CreateIdentifier(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t value = 0) {
  IdentifierBuilder builder_(_fbb);
  builder_.add_value(value);
  return builder_.Finish();
}

struct ExternalReference FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ExternalReferenceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REFERENCE = 4,
    VT_TYPE = 6,
    VT_IDENTIFIER = 8
  };
  const ::flatbuffers::String *reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_REFERENCE);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *identifier() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_IDENTIFIER);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_REFERENCE) &&
           verifier.VerifyString(reference()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_IDENTIFIER) &&
           verifier.VerifyVector(identifier()) &&
           verifier.VerifyVectorOfStrings(identifier()) &&
           verifier.EndTable();
  }
};

struct ExternalReferenceBuilder {
  typedef ExternalReference Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_reference(::flatbuffers::Offset<::flatbuffers::String> reference) {
    fbb_.AddOffset(ExternalReference::VT_REFERENCE, reference);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(ExternalReference::VT_TYPE, type);
  }
  void add_identifier(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> identifier) {
    fbb_.AddOffset(ExternalReference::VT_IDENTIFIER, identifier);
  }
  explicit ExternalReferenceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ExternalReference> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ExternalReference>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ExternalReference> CreateExternalReference(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> reference = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> identifier = 0) {
  ExternalReferenceBuilder builder_(_fbb);
  builder_.add_identifier(identifier);
  builder_.add_type(type);
  builder_.add_reference(reference);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ExternalReference> CreateExternalReferenceDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *reference = nullptr,
    const char *type = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *identifier = nullptr) {
  auto reference__ = reference ? _fbb.CreateString(reference) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto identifier__ = identifier ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*identifier) : 0;
  return osi3::CreateExternalReference(
      _fbb,
      reference__,
      type__,
      identifier__);
}

struct MountingPosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MountingPositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ORIENTATION = 6
  };
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           verifier.EndTable();
  }
};

struct MountingPositionBuilder {
  typedef MountingPosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(MountingPosition::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(MountingPosition::VT_ORIENTATION, orientation);
  }
  explicit MountingPositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MountingPosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MountingPosition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MountingPosition> CreateMountingPosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0) {
  MountingPositionBuilder builder_(_fbb);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  return builder_.Finish();
}

struct Spherical3d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Spherical3dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DISTANCE = 4,
    VT_AZIMUTH = 6,
    VT_ELEVATION = 8
  };
  double distance() const {
    return GetField<double>(VT_DISTANCE, 0.0);
  }
  double azimuth() const {
    return GetField<double>(VT_AZIMUTH, 0.0);
  }
  double elevation() const {
    return GetField<double>(VT_ELEVATION, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_DISTANCE, 8) &&
           VerifyField<double>(verifier, VT_AZIMUTH, 8) &&
           VerifyField<double>(verifier, VT_ELEVATION, 8) &&
           verifier.EndTable();
  }
};

struct Spherical3dBuilder {
  typedef Spherical3d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_distance(double distance) {
    fbb_.AddElement<double>(Spherical3d::VT_DISTANCE, distance, 0.0);
  }
  void add_azimuth(double azimuth) {
    fbb_.AddElement<double>(Spherical3d::VT_AZIMUTH, azimuth, 0.0);
  }
  void add_elevation(double elevation) {
    fbb_.AddElement<double>(Spherical3d::VT_ELEVATION, elevation, 0.0);
  }
  explicit Spherical3dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Spherical3d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Spherical3d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Spherical3d> CreateSpherical3d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double distance = 0.0,
    double azimuth = 0.0,
    double elevation = 0.0) {
  Spherical3dBuilder builder_(_fbb);
  builder_.add_elevation(elevation);
  builder_.add_azimuth(azimuth);
  builder_.add_distance(distance);
  return builder_.Finish();
}

struct LogicalLaneAssignment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogicalLaneAssignmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ASSIGNED_LANE_ID = 4,
    VT_S_POSITION = 6,
    VT_T_POSITION = 8,
    VT_ANGLE_TO_LANE = 10
  };
  const osi3::Identifier *assigned_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_ASSIGNED_LANE_ID);
  }
  double s_position() const {
    return GetField<double>(VT_S_POSITION, 0.0);
  }
  double t_position() const {
    return GetField<double>(VT_T_POSITION, 0.0);
  }
  double angle_to_lane() const {
    return GetField<double>(VT_ANGLE_TO_LANE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyTable(assigned_lane_id()) &&
           VerifyField<double>(verifier, VT_S_POSITION, 8) &&
           VerifyField<double>(verifier, VT_T_POSITION, 8) &&
           VerifyField<double>(verifier, VT_ANGLE_TO_LANE, 8) &&
           verifier.EndTable();
  }
};

struct LogicalLaneAssignmentBuilder {
  typedef LogicalLaneAssignment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_assigned_lane_id(::flatbuffers::Offset<osi3::Identifier> assigned_lane_id) {
    fbb_.AddOffset(LogicalLaneAssignment::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_s_position(double s_position) {
    fbb_.AddElement<double>(LogicalLaneAssignment::VT_S_POSITION, s_position, 0.0);
  }
  void add_t_position(double t_position) {
    fbb_.AddElement<double>(LogicalLaneAssignment::VT_T_POSITION, t_position, 0.0);
  }
  void add_angle_to_lane(double angle_to_lane) {
    fbb_.AddElement<double>(LogicalLaneAssignment::VT_ANGLE_TO_LANE, angle_to_lane, 0.0);
  }
  explicit LogicalLaneAssignmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LogicalLaneAssignment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LogicalLaneAssignment>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LogicalLaneAssignment> CreateLogicalLaneAssignment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> assigned_lane_id = 0,
    double s_position = 0.0,
    double t_position = 0.0,
    double angle_to_lane = 0.0) {
  LogicalLaneAssignmentBuilder builder_(_fbb);
  builder_.add_angle_to_lane(angle_to_lane);
  builder_.add_t_position(t_position);
  builder_.add_s_position(s_position);
  builder_.add_assigned_lane_id(assigned_lane_id);
  return builder_.Finish();
}

struct BoundingBox FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoundingBoxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIMENSION = 4,
    VT_POSITION = 6,
    VT_ORIENTATION = 8,
    VT_CONTAINED_OBJECT_TYPE = 10,
    VT_MODEL_REFERENCE = 12
  };
  const osi3::Dimension3d *dimension() const {
    return GetPointer<const osi3::Dimension3d *>(VT_DIMENSION);
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  osi3::BoundingBoxType contained_object_type() const {
    return static_cast<osi3::BoundingBoxType>(GetField<int8_t>(VT_CONTAINED_OBJECT_TYPE, 0));
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIMENSION) &&
           verifier.VerifyTable(dimension()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyField<int8_t>(verifier, VT_CONTAINED_OBJECT_TYPE, 1) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           verifier.EndTable();
  }
};

struct BoundingBoxBuilder {
  typedef BoundingBox Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dimension(::flatbuffers::Offset<osi3::Dimension3d> dimension) {
    fbb_.AddOffset(BoundingBox::VT_DIMENSION, dimension);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(BoundingBox::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(BoundingBox::VT_ORIENTATION, orientation);
  }
  void add_contained_object_type(osi3::BoundingBoxType contained_object_type) {
    fbb_.AddElement<int8_t>(BoundingBox::VT_CONTAINED_OBJECT_TYPE, static_cast<int8_t>(contained_object_type), 0);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(BoundingBox::VT_MODEL_REFERENCE, model_reference);
  }
  explicit BoundingBoxBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoundingBox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoundingBox>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoundingBox> CreateBoundingBox(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    osi3::BoundingBoxType contained_object_type = osi3::BoundingBoxType_TYPE_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0) {
  BoundingBoxBuilder builder_(_fbb);
  builder_.add_model_reference(model_reference);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_dimension(dimension);
  builder_.add_contained_object_type(contained_object_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BoundingBox> CreateBoundingBoxDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    osi3::BoundingBoxType contained_object_type = osi3::BoundingBoxType_TYPE_UNKNOWN,
    const char *model_reference = nullptr) {
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  return osi3::CreateBoundingBox(
      _fbb,
      dimension,
      position,
      orientation,
      contained_object_type,
      model_reference__);
}

struct BaseStationary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BaseStationaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIMENSION = 4,
    VT_POSITION = 6,
    VT_ORIENTATION = 8,
    VT_BASE_POLYGON = 10,
    VT_BOUNDING_BOX_SECTION = 12
  };
  const osi3::Dimension3d *dimension() const {
    return GetPointer<const osi3::Dimension3d *>(VT_DIMENSION);
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>> *base_polygon() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>> *>(VT_BASE_POLYGON);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>> *bounding_box_section() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>> *>(VT_BOUNDING_BOX_SECTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIMENSION) &&
           verifier.VerifyTable(dimension()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyOffset(verifier, VT_BASE_POLYGON) &&
           verifier.VerifyVector(base_polygon()) &&
           verifier.VerifyVectorOfTables(base_polygon()) &&
           VerifyOffset(verifier, VT_BOUNDING_BOX_SECTION) &&
           verifier.VerifyVector(bounding_box_section()) &&
           verifier.VerifyVectorOfTables(bounding_box_section()) &&
           verifier.EndTable();
  }
};

struct BaseStationaryBuilder {
  typedef BaseStationary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dimension(::flatbuffers::Offset<osi3::Dimension3d> dimension) {
    fbb_.AddOffset(BaseStationary::VT_DIMENSION, dimension);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(BaseStationary::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(BaseStationary::VT_ORIENTATION, orientation);
  }
  void add_base_polygon(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>>> base_polygon) {
    fbb_.AddOffset(BaseStationary::VT_BASE_POLYGON, base_polygon);
  }
  void add_bounding_box_section(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>>> bounding_box_section) {
    fbb_.AddOffset(BaseStationary::VT_BOUNDING_BOX_SECTION, bounding_box_section);
  }
  explicit BaseStationaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BaseStationary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BaseStationary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BaseStationary> CreateBaseStationary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>>> base_polygon = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>>> bounding_box_section = 0) {
  BaseStationaryBuilder builder_(_fbb);
  builder_.add_bounding_box_section(bounding_box_section);
  builder_.add_base_polygon(base_polygon);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_dimension(dimension);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BaseStationary> CreateBaseStationaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    const std::vector<::flatbuffers::Offset<osi3::Vector2d>> *base_polygon = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::BoundingBox>> *bounding_box_section = nullptr) {
  auto base_polygon__ = base_polygon ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Vector2d>>(*base_polygon) : 0;
  auto bounding_box_section__ = bounding_box_section ? _fbb.CreateVector<::flatbuffers::Offset<osi3::BoundingBox>>(*bounding_box_section) : 0;
  return osi3::CreateBaseStationary(
      _fbb,
      dimension,
      position,
      orientation,
      base_polygon__,
      bounding_box_section__);
}

struct BaseMoving FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BaseMovingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DIMENSION = 4,
    VT_POSITION = 6,
    VT_ORIENTATION = 8,
    VT_VELOCITY = 10,
    VT_ACCELERATION = 12,
    VT_ORIENTATION_RATE = 14,
    VT_BASE_POLYGON = 16,
    VT_ORIENTATION_ACCELERATION = 18,
    VT_BOUNDING_BOX_SECTION = 20
  };
  const osi3::Dimension3d *dimension() const {
    return GetPointer<const osi3::Dimension3d *>(VT_DIMENSION);
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  const osi3::Vector3d *velocity() const {
    return GetPointer<const osi3::Vector3d *>(VT_VELOCITY);
  }
  const osi3::Vector3d *acceleration() const {
    return GetPointer<const osi3::Vector3d *>(VT_ACCELERATION);
  }
  const osi3::Orientation3d *orientation_rate() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION_RATE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>> *base_polygon() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>> *>(VT_BASE_POLYGON);
  }
  const osi3::Orientation3d *orientation_acceleration() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION_ACCELERATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>> *bounding_box_section() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>> *>(VT_BOUNDING_BOX_SECTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DIMENSION) &&
           verifier.VerifyTable(dimension()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyOffset(verifier, VT_VELOCITY) &&
           verifier.VerifyTable(velocity()) &&
           VerifyOffset(verifier, VT_ACCELERATION) &&
           verifier.VerifyTable(acceleration()) &&
           VerifyOffset(verifier, VT_ORIENTATION_RATE) &&
           verifier.VerifyTable(orientation_rate()) &&
           VerifyOffset(verifier, VT_BASE_POLYGON) &&
           verifier.VerifyVector(base_polygon()) &&
           verifier.VerifyVectorOfTables(base_polygon()) &&
           VerifyOffset(verifier, VT_ORIENTATION_ACCELERATION) &&
           verifier.VerifyTable(orientation_acceleration()) &&
           VerifyOffset(verifier, VT_BOUNDING_BOX_SECTION) &&
           verifier.VerifyVector(bounding_box_section()) &&
           verifier.VerifyVectorOfTables(bounding_box_section()) &&
           verifier.EndTable();
  }
};

struct BaseMovingBuilder {
  typedef BaseMoving Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_dimension(::flatbuffers::Offset<osi3::Dimension3d> dimension) {
    fbb_.AddOffset(BaseMoving::VT_DIMENSION, dimension);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(BaseMoving::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(BaseMoving::VT_ORIENTATION, orientation);
  }
  void add_velocity(::flatbuffers::Offset<osi3::Vector3d> velocity) {
    fbb_.AddOffset(BaseMoving::VT_VELOCITY, velocity);
  }
  void add_acceleration(::flatbuffers::Offset<osi3::Vector3d> acceleration) {
    fbb_.AddOffset(BaseMoving::VT_ACCELERATION, acceleration);
  }
  void add_orientation_rate(::flatbuffers::Offset<osi3::Orientation3d> orientation_rate) {
    fbb_.AddOffset(BaseMoving::VT_ORIENTATION_RATE, orientation_rate);
  }
  void add_base_polygon(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>>> base_polygon) {
    fbb_.AddOffset(BaseMoving::VT_BASE_POLYGON, base_polygon);
  }
  void add_orientation_acceleration(::flatbuffers::Offset<osi3::Orientation3d> orientation_acceleration) {
    fbb_.AddOffset(BaseMoving::VT_ORIENTATION_ACCELERATION, orientation_acceleration);
  }
  void add_bounding_box_section(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>>> bounding_box_section) {
    fbb_.AddOffset(BaseMoving::VT_BOUNDING_BOX_SECTION, bounding_box_section);
  }
  explicit BaseMovingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BaseMoving> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BaseMoving>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BaseMoving> CreateBaseMoving(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    ::flatbuffers::Offset<osi3::Vector3d> velocity = 0,
    ::flatbuffers::Offset<osi3::Vector3d> acceleration = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation_rate = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector2d>>> base_polygon = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation_acceleration = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::BoundingBox>>> bounding_box_section = 0) {
  BaseMovingBuilder builder_(_fbb);
  builder_.add_bounding_box_section(bounding_box_section);
  builder_.add_orientation_acceleration(orientation_acceleration);
  builder_.add_base_polygon(base_polygon);
  builder_.add_orientation_rate(orientation_rate);
  builder_.add_acceleration(acceleration);
  builder_.add_velocity(velocity);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_dimension(dimension);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BaseMoving> CreateBaseMovingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Dimension3d> dimension = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    ::flatbuffers::Offset<osi3::Vector3d> velocity = 0,
    ::flatbuffers::Offset<osi3::Vector3d> acceleration = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation_rate = 0,
    const std::vector<::flatbuffers::Offset<osi3::Vector2d>> *base_polygon = nullptr,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation_acceleration = 0,
    const std::vector<::flatbuffers::Offset<osi3::BoundingBox>> *bounding_box_section = nullptr) {
  auto base_polygon__ = base_polygon ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Vector2d>>(*base_polygon) : 0;
  auto bounding_box_section__ = bounding_box_section ? _fbb.CreateVector<::flatbuffers::Offset<osi3::BoundingBox>>(*bounding_box_section) : 0;
  return osi3::CreateBaseMoving(
      _fbb,
      dimension,
      position,
      orientation,
      velocity,
      acceleration,
      orientation_rate,
      base_polygon__,
      orientation_acceleration,
      bounding_box_section__);
}

struct StatePoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StatePointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_POSITION = 6,
    VT_ORIENTATION = 8
  };
  const osi3::Timestamp *timestamp() const {
    return GetPointer<const osi3::Timestamp *>(VT_TIMESTAMP);
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyTable(timestamp()) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           verifier.EndTable();
  }
};

struct StatePointBuilder {
  typedef StatePoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(::flatbuffers::Offset<osi3::Timestamp> timestamp) {
    fbb_.AddOffset(StatePoint::VT_TIMESTAMP, timestamp);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(StatePoint::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(StatePoint::VT_ORIENTATION, orientation);
  }
  explicit StatePointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StatePoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StatePoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StatePoint> CreateStatePoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Timestamp> timestamp = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0) {
  StatePointBuilder builder_(_fbb);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

struct WavelengthData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WavelengthDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_START = 4,
    VT_END = 6,
    VT_SAMPLES_NUMBER = 8
  };
  double start() const {
    return GetField<double>(VT_START, 0.0);
  }
  double end() const {
    return GetField<double>(VT_END, 0.0);
  }
  double samples_number() const {
    return GetField<double>(VT_SAMPLES_NUMBER, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_START, 8) &&
           VerifyField<double>(verifier, VT_END, 8) &&
           VerifyField<double>(verifier, VT_SAMPLES_NUMBER, 8) &&
           verifier.EndTable();
  }
};

struct WavelengthDataBuilder {
  typedef WavelengthData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_start(double start) {
    fbb_.AddElement<double>(WavelengthData::VT_START, start, 0.0);
  }
  void add_end(double end) {
    fbb_.AddElement<double>(WavelengthData::VT_END, end, 0.0);
  }
  void add_samples_number(double samples_number) {
    fbb_.AddElement<double>(WavelengthData::VT_SAMPLES_NUMBER, samples_number, 0.0);
  }
  explicit WavelengthDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WavelengthData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WavelengthData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WavelengthData> CreateWavelengthData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double start = 0.0,
    double end = 0.0,
    double samples_number = 0.0) {
  WavelengthDataBuilder builder_(_fbb);
  builder_.add_samples_number(samples_number);
  builder_.add_end(end);
  builder_.add_start(start);
  return builder_.Finish();
}

struct SpatialSignalStrength FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpatialSignalStrengthBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HORIZONTAL_ANGLE = 4,
    VT_VERTICAL_ANGLE = 6,
    VT_SIGNAL_STRENGTH = 8
  };
  double horizontal_angle() const {
    return GetField<double>(VT_HORIZONTAL_ANGLE, 0.0);
  }
  double vertical_angle() const {
    return GetField<double>(VT_VERTICAL_ANGLE, 0.0);
  }
  double signal_strength() const {
    return GetField<double>(VT_SIGNAL_STRENGTH, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_HORIZONTAL_ANGLE, 8) &&
           VerifyField<double>(verifier, VT_VERTICAL_ANGLE, 8) &&
           VerifyField<double>(verifier, VT_SIGNAL_STRENGTH, 8) &&
           verifier.EndTable();
  }
};

struct SpatialSignalStrengthBuilder {
  typedef SpatialSignalStrength Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_horizontal_angle(double horizontal_angle) {
    fbb_.AddElement<double>(SpatialSignalStrength::VT_HORIZONTAL_ANGLE, horizontal_angle, 0.0);
  }
  void add_vertical_angle(double vertical_angle) {
    fbb_.AddElement<double>(SpatialSignalStrength::VT_VERTICAL_ANGLE, vertical_angle, 0.0);
  }
  void add_signal_strength(double signal_strength) {
    fbb_.AddElement<double>(SpatialSignalStrength::VT_SIGNAL_STRENGTH, signal_strength, 0.0);
  }
  explicit SpatialSignalStrengthBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpatialSignalStrength> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpatialSignalStrength>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpatialSignalStrength> CreateSpatialSignalStrength(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double horizontal_angle = 0.0,
    double vertical_angle = 0.0,
    double signal_strength = 0.0) {
  SpatialSignalStrengthBuilder builder_(_fbb);
  builder_.add_signal_strength(signal_strength);
  builder_.add_vertical_angle(vertical_angle);
  builder_.add_horizontal_angle(horizontal_angle);
  return builder_.Finish();
}

struct ColorGrey FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorGreyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GREY = 4
  };
  double grey() const {
    return GetField<double>(VT_GREY, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_GREY, 8) &&
           verifier.EndTable();
  }
};

struct ColorGreyBuilder {
  typedef ColorGrey Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_grey(double grey) {
    fbb_.AddElement<double>(ColorGrey::VT_GREY, grey, 0.0);
  }
  explicit ColorGreyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorGrey> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorGrey>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorGrey> CreateColorGrey(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double grey = 0.0) {
  ColorGreyBuilder builder_(_fbb);
  builder_.add_grey(grey);
  return builder_.Finish();
}

struct ColorRGB FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorRGBBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RED = 4,
    VT_GREEN = 6,
    VT_BLUE = 8
  };
  double red() const {
    return GetField<double>(VT_RED, 0.0);
  }
  double green() const {
    return GetField<double>(VT_GREEN, 0.0);
  }
  double blue() const {
    return GetField<double>(VT_BLUE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_RED, 8) &&
           VerifyField<double>(verifier, VT_GREEN, 8) &&
           VerifyField<double>(verifier, VT_BLUE, 8) &&
           verifier.EndTable();
  }
};

struct ColorRGBBuilder {
  typedef ColorRGB Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_red(double red) {
    fbb_.AddElement<double>(ColorRGB::VT_RED, red, 0.0);
  }
  void add_green(double green) {
    fbb_.AddElement<double>(ColorRGB::VT_GREEN, green, 0.0);
  }
  void add_blue(double blue) {
    fbb_.AddElement<double>(ColorRGB::VT_BLUE, blue, 0.0);
  }
  explicit ColorRGBBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorRGB> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorRGB>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorRGB> CreateColorRGB(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double red = 0.0,
    double green = 0.0,
    double blue = 0.0) {
  ColorRGBBuilder builder_(_fbb);
  builder_.add_blue(blue);
  builder_.add_green(green);
  builder_.add_red(red);
  return builder_.Finish();
}

struct ColorRGBIR FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorRGBIRBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RED = 4,
    VT_GREEN = 6,
    VT_BLUE = 8,
    VT_INFRARED = 10
  };
  double red() const {
    return GetField<double>(VT_RED, 0.0);
  }
  double green() const {
    return GetField<double>(VT_GREEN, 0.0);
  }
  double blue() const {
    return GetField<double>(VT_BLUE, 0.0);
  }
  double infrared() const {
    return GetField<double>(VT_INFRARED, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_RED, 8) &&
           VerifyField<double>(verifier, VT_GREEN, 8) &&
           VerifyField<double>(verifier, VT_BLUE, 8) &&
           VerifyField<double>(verifier, VT_INFRARED, 8) &&
           verifier.EndTable();
  }
};

struct ColorRGBIRBuilder {
  typedef ColorRGBIR Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_red(double red) {
    fbb_.AddElement<double>(ColorRGBIR::VT_RED, red, 0.0);
  }
  void add_green(double green) {
    fbb_.AddElement<double>(ColorRGBIR::VT_GREEN, green, 0.0);
  }
  void add_blue(double blue) {
    fbb_.AddElement<double>(ColorRGBIR::VT_BLUE, blue, 0.0);
  }
  void add_infrared(double infrared) {
    fbb_.AddElement<double>(ColorRGBIR::VT_INFRARED, infrared, 0.0);
  }
  explicit ColorRGBIRBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorRGBIR> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorRGBIR>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorRGBIR> CreateColorRGBIR(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double red = 0.0,
    double green = 0.0,
    double blue = 0.0,
    double infrared = 0.0) {
  ColorRGBIRBuilder builder_(_fbb);
  builder_.add_infrared(infrared);
  builder_.add_blue(blue);
  builder_.add_green(green);
  builder_.add_red(red);
  return builder_.Finish();
}

struct ColorHSV FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorHSVBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HUE = 4,
    VT_SATURATION = 6,
    VT_VALUE = 8
  };
  double hue() const {
    return GetField<double>(VT_HUE, 0.0);
  }
  double saturation() const {
    return GetField<double>(VT_SATURATION, 0.0);
  }
  double value() const {
    return GetField<double>(VT_VALUE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_HUE, 8) &&
           VerifyField<double>(verifier, VT_SATURATION, 8) &&
           VerifyField<double>(verifier, VT_VALUE, 8) &&
           verifier.EndTable();
  }
};

struct ColorHSVBuilder {
  typedef ColorHSV Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hue(double hue) {
    fbb_.AddElement<double>(ColorHSV::VT_HUE, hue, 0.0);
  }
  void add_saturation(double saturation) {
    fbb_.AddElement<double>(ColorHSV::VT_SATURATION, saturation, 0.0);
  }
  void add_value(double value) {
    fbb_.AddElement<double>(ColorHSV::VT_VALUE, value, 0.0);
  }
  explicit ColorHSVBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorHSV> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorHSV>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorHSV> CreateColorHSV(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double hue = 0.0,
    double saturation = 0.0,
    double value = 0.0) {
  ColorHSVBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_saturation(saturation);
  builder_.add_hue(hue);
  return builder_.Finish();
}

struct ColorLUV FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorLUVBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LUMINANCE = 4,
    VT_U = 6,
    VT_V = 8
  };
  double luminance() const {
    return GetField<double>(VT_LUMINANCE, 0.0);
  }
  double u() const {
    return GetField<double>(VT_U, 0.0);
  }
  double v() const {
    return GetField<double>(VT_V, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_LUMINANCE, 8) &&
           VerifyField<double>(verifier, VT_U, 8) &&
           VerifyField<double>(verifier, VT_V, 8) &&
           verifier.EndTable();
  }
};

struct ColorLUVBuilder {
  typedef ColorLUV Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_luminance(double luminance) {
    fbb_.AddElement<double>(ColorLUV::VT_LUMINANCE, luminance, 0.0);
  }
  void add_u(double u) {
    fbb_.AddElement<double>(ColorLUV::VT_U, u, 0.0);
  }
  void add_v(double v) {
    fbb_.AddElement<double>(ColorLUV::VT_V, v, 0.0);
  }
  explicit ColorLUVBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorLUV> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorLUV>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorLUV> CreateColorLUV(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double luminance = 0.0,
    double u = 0.0,
    double v = 0.0) {
  ColorLUVBuilder builder_(_fbb);
  builder_.add_v(v);
  builder_.add_u(u);
  builder_.add_luminance(luminance);
  return builder_.Finish();
}

struct ColorCMYK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorCMYKBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CYAN = 4,
    VT_MAGENTA = 6,
    VT_YELLOW = 8,
    VT_KEY = 10
  };
  double cyan() const {
    return GetField<double>(VT_CYAN, 0.0);
  }
  double magenta() const {
    return GetField<double>(VT_MAGENTA, 0.0);
  }
  double yellow() const {
    return GetField<double>(VT_YELLOW, 0.0);
  }
  double key() const {
    return GetField<double>(VT_KEY, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_CYAN, 8) &&
           VerifyField<double>(verifier, VT_MAGENTA, 8) &&
           VerifyField<double>(verifier, VT_YELLOW, 8) &&
           VerifyField<double>(verifier, VT_KEY, 8) &&
           verifier.EndTable();
  }
};

struct ColorCMYKBuilder {
  typedef ColorCMYK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cyan(double cyan) {
    fbb_.AddElement<double>(ColorCMYK::VT_CYAN, cyan, 0.0);
  }
  void add_magenta(double magenta) {
    fbb_.AddElement<double>(ColorCMYK::VT_MAGENTA, magenta, 0.0);
  }
  void add_yellow(double yellow) {
    fbb_.AddElement<double>(ColorCMYK::VT_YELLOW, yellow, 0.0);
  }
  void add_key(double key) {
    fbb_.AddElement<double>(ColorCMYK::VT_KEY, key, 0.0);
  }
  explicit ColorCMYKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorCMYK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorCMYK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorCMYK> CreateColorCMYK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double cyan = 0.0,
    double magenta = 0.0,
    double yellow = 0.0,
    double key = 0.0) {
  ColorCMYKBuilder builder_(_fbb);
  builder_.add_key(key);
  builder_.add_yellow(yellow);
  builder_.add_magenta(magenta);
  builder_.add_cyan(cyan);
  return builder_.Finish();
}

struct ColorDescription FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ColorDescriptionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GREY = 4,
    VT_RGB = 6,
    VT_RGBIR = 8,
    VT_HSV = 10,
    VT_LUV = 12,
    VT_CMYK = 14
  };
  const osi3::ColorGrey *grey() const {
    return GetPointer<const osi3::ColorGrey *>(VT_GREY);
  }
  const osi3::ColorRGB *rgb() const {
    return GetPointer<const osi3::ColorRGB *>(VT_RGB);
  }
  const osi3::ColorRGBIR *rgbir() const {
    return GetPointer<const osi3::ColorRGBIR *>(VT_RGBIR);
  }
  const osi3::ColorHSV *hsv() const {
    return GetPointer<const osi3::ColorHSV *>(VT_HSV);
  }
  const osi3::ColorLUV *luv() const {
    return GetPointer<const osi3::ColorLUV *>(VT_LUV);
  }
  const osi3::ColorCMYK *cmyk() const {
    return GetPointer<const osi3::ColorCMYK *>(VT_CMYK);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GREY) &&
           verifier.VerifyTable(grey()) &&
           VerifyOffset(verifier, VT_RGB) &&
           verifier.VerifyTable(rgb()) &&
           VerifyOffset(verifier, VT_RGBIR) &&
           verifier.VerifyTable(rgbir()) &&
           VerifyOffset(verifier, VT_HSV) &&
           verifier.VerifyTable(hsv()) &&
           VerifyOffset(verifier, VT_LUV) &&
           verifier.VerifyTable(luv()) &&
           VerifyOffset(verifier, VT_CMYK) &&
           verifier.VerifyTable(cmyk()) &&
           verifier.EndTable();
  }
};

struct ColorDescriptionBuilder {
  typedef ColorDescription Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_grey(::flatbuffers::Offset<osi3::ColorGrey> grey) {
    fbb_.AddOffset(ColorDescription::VT_GREY, grey);
  }
  void add_rgb(::flatbuffers::Offset<osi3::ColorRGB> rgb) {
    fbb_.AddOffset(ColorDescription::VT_RGB, rgb);
  }
  void add_rgbir(::flatbuffers::Offset<osi3::ColorRGBIR> rgbir) {
    fbb_.AddOffset(ColorDescription::VT_RGBIR, rgbir);
  }
  void add_hsv(::flatbuffers::Offset<osi3::ColorHSV> hsv) {
    fbb_.AddOffset(ColorDescription::VT_HSV, hsv);
  }
  void add_luv(::flatbuffers::Offset<osi3::ColorLUV> luv) {
    fbb_.AddOffset(ColorDescription::VT_LUV, luv);
  }
  void add_cmyk(::flatbuffers::Offset<osi3::ColorCMYK> cmyk) {
    fbb_.AddOffset(ColorDescription::VT_CMYK, cmyk);
  }
  explicit ColorDescriptionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ColorDescription> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ColorDescription>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ColorDescription> CreateColorDescription(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::ColorGrey> grey = 0,
    ::flatbuffers::Offset<osi3::ColorRGB> rgb = 0,
    ::flatbuffers::Offset<osi3::ColorRGBIR> rgbir = 0,
    ::flatbuffers::Offset<osi3::ColorHSV> hsv = 0,
    ::flatbuffers::Offset<osi3::ColorLUV> luv = 0,
    ::flatbuffers::Offset<osi3::ColorCMYK> cmyk = 0) {
  ColorDescriptionBuilder builder_(_fbb);
  builder_.add_cmyk(cmyk);
  builder_.add_luv(luv);
  builder_.add_hsv(hsv);
  builder_.add_rgbir(rgbir);
  builder_.add_rgb(rgb);
  builder_.add_grey(grey);
  return builder_.Finish();
}

struct Pedalry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PedalryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PEDAL_POSITION_ACCELERATION = 4,
    VT_PEDAL_POSITION_BRAKE = 6,
    VT_PEDAL_POSITION_CLUTCH = 8
  };
  double pedal_position_acceleration() const {
    return GetField<double>(VT_PEDAL_POSITION_ACCELERATION, 0.0);
  }
  double pedal_position_brake() const {
    return GetField<double>(VT_PEDAL_POSITION_BRAKE, 0.0);
  }
  double pedal_position_clutch() const {
    return GetField<double>(VT_PEDAL_POSITION_CLUTCH, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_PEDAL_POSITION_ACCELERATION, 8) &&
           VerifyField<double>(verifier, VT_PEDAL_POSITION_BRAKE, 8) &&
           VerifyField<double>(verifier, VT_PEDAL_POSITION_CLUTCH, 8) &&
           verifier.EndTable();
  }
};

struct PedalryBuilder {
  typedef Pedalry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pedal_position_acceleration(double pedal_position_acceleration) {
    fbb_.AddElement<double>(Pedalry::VT_PEDAL_POSITION_ACCELERATION, pedal_position_acceleration, 0.0);
  }
  void add_pedal_position_brake(double pedal_position_brake) {
    fbb_.AddElement<double>(Pedalry::VT_PEDAL_POSITION_BRAKE, pedal_position_brake, 0.0);
  }
  void add_pedal_position_clutch(double pedal_position_clutch) {
    fbb_.AddElement<double>(Pedalry::VT_PEDAL_POSITION_CLUTCH, pedal_position_clutch, 0.0);
  }
  explicit PedalryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Pedalry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Pedalry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Pedalry> CreatePedalry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double pedal_position_acceleration = 0.0,
    double pedal_position_brake = 0.0,
    double pedal_position_clutch = 0.0) {
  PedalryBuilder builder_(_fbb);
  builder_.add_pedal_position_clutch(pedal_position_clutch);
  builder_.add_pedal_position_brake(pedal_position_brake);
  builder_.add_pedal_position_acceleration(pedal_position_acceleration);
  return builder_.Finish();
}

struct VehicleSteeringWheel FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VehicleSteeringWheelBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANGLE = 4,
    VT_ANGULAR_SPEED = 6,
    VT_TORQUE = 8
  };
  double angle() const {
    return GetField<double>(VT_ANGLE, 0.0);
  }
  double angular_speed() const {
    return GetField<double>(VT_ANGULAR_SPEED, 0.0);
  }
  double torque() const {
    return GetField<double>(VT_TORQUE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_ANGLE, 8) &&
           VerifyField<double>(verifier, VT_ANGULAR_SPEED, 8) &&
           VerifyField<double>(verifier, VT_TORQUE, 8) &&
           verifier.EndTable();
  }
};

struct VehicleSteeringWheelBuilder {
  typedef VehicleSteeringWheel Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_angle(double angle) {
    fbb_.AddElement<double>(VehicleSteeringWheel::VT_ANGLE, angle, 0.0);
  }
  void add_angular_speed(double angular_speed) {
    fbb_.AddElement<double>(VehicleSteeringWheel::VT_ANGULAR_SPEED, angular_speed, 0.0);
  }
  void add_torque(double torque) {
    fbb_.AddElement<double>(VehicleSteeringWheel::VT_TORQUE, torque, 0.0);
  }
  explicit VehicleSteeringWheelBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VehicleSteeringWheel> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VehicleSteeringWheel>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VehicleSteeringWheel> CreateVehicleSteeringWheel(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double angle = 0.0,
    double angular_speed = 0.0,
    double torque = 0.0) {
  VehicleSteeringWheelBuilder builder_(_fbb);
  builder_.add_torque(torque);
  builder_.add_angular_speed(angular_speed);
  builder_.add_angle(angle);
  return builder_.Finish();
}

struct GeodeticPosition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeodeticPositionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LONGITUDE = 4,
    VT_LATITUDE = 6,
    VT_ALTITUDE = 8
  };
  double longitude() const {
    return GetField<double>(VT_LONGITUDE, 0.0);
  }
  double latitude() const {
    return GetField<double>(VT_LATITUDE, 0.0);
  }
  double altitude() const {
    return GetField<double>(VT_ALTITUDE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_LONGITUDE, 8) &&
           VerifyField<double>(verifier, VT_LATITUDE, 8) &&
           VerifyField<double>(verifier, VT_ALTITUDE, 8) &&
           verifier.EndTable();
  }
};

struct GeodeticPositionBuilder {
  typedef GeodeticPosition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_longitude(double longitude) {
    fbb_.AddElement<double>(GeodeticPosition::VT_LONGITUDE, longitude, 0.0);
  }
  void add_latitude(double latitude) {
    fbb_.AddElement<double>(GeodeticPosition::VT_LATITUDE, latitude, 0.0);
  }
  void add_altitude(double altitude) {
    fbb_.AddElement<double>(GeodeticPosition::VT_ALTITUDE, altitude, 0.0);
  }
  explicit GeodeticPositionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GeodeticPosition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GeodeticPosition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GeodeticPosition> CreateGeodeticPosition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double longitude = 0.0,
    double latitude = 0.0,
    double altitude = 0.0) {
  GeodeticPositionBuilder builder_(_fbb);
  builder_.add_altitude(altitude);
  builder_.add_latitude(latitude);
  builder_.add_longitude(longitude);
  return builder_.Finish();
}

struct KeyValuePair FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef KeyValuePairBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const ::flatbuffers::String *key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KEY);
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct KeyValuePairBuilder {
  typedef KeyValuePair Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_key(::flatbuffers::Offset<::flatbuffers::String> key) {
    fbb_.AddOffset(KeyValuePair::VT_KEY, key);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(KeyValuePair::VT_VALUE, value);
  }
  explicit KeyValuePairBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<KeyValuePair> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<KeyValuePair>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<KeyValuePair> CreateKeyValuePair(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  KeyValuePairBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<KeyValuePair> CreateKeyValuePairDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *value = nullptr) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return osi3::CreateKeyValuePair(
      _fbb,
      key__,
      value__);
}

struct Polygon3d FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Polygon3dBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTEX = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>> *vertex() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>> *>(VT_VERTEX);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTEX) &&
           verifier.VerifyVector(vertex()) &&
           verifier.VerifyVectorOfTables(vertex()) &&
           verifier.EndTable();
  }
};

struct Polygon3dBuilder {
  typedef Polygon3d Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertex(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>>> vertex) {
    fbb_.AddOffset(Polygon3d::VT_VERTEX, vertex);
  }
  explicit Polygon3dBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Polygon3d> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Polygon3d>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Polygon3d> CreatePolygon3d(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>>> vertex = 0) {
  Polygon3dBuilder builder_(_fbb);
  builder_.add_vertex(vertex);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Polygon3d> CreatePolygon3dDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<osi3::Vector3d>> *vertex = nullptr) {
  auto vertex__ = vertex ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Vector3d>>(*vertex) : 0;
  return osi3::CreatePolygon3d(
      _fbb,
      vertex__);
}

}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSICOMMON_OSI3_H_
