version: '3.8'

services:
  zenoh_bridge:
    build: ./zenoh_bridge   # Path to Dockerfile for zenoh_bridge
    container_name: zenoh_bridge
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - shared_data:/shared_data  # Mount shared volume

  esmini_zenoh:
    build: ./esmini_zenoh   # Path to Dockerfile for esmini_zenoh
    container_name: esmini_zenoh
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - shared_data:/shared_data  # Mount shared volume
      - /tmp/.X11-unix:/tmp/.X11-unix 
    environment:
      DISPLAY: ${DISPLAY}  # Pass the host's DISPLAY variable
      QT_X11_NO_MITSHM: "1"  # Prevent shared memory issues with X11

volumes:
  shared_data: