version: '3.8'

services:
  zenoh_bridge:
    build: ./zenoh_bridge   # Path to Dockerfile for zenoh_bridge
    container_name: zenoh_bridge
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro

  esmini_zenoh:
    build: ./esmini_zenoh   # Path to Dockerfile for esmini_zenoh
    container_name: esmini_zenoh
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro