include "osi_common.fbs";
include "osi_trafficsign.fbs";

namespace osi3.RoadMarking_.Classification_;
enum Type : int {
    TYPE_UNKNOWN = 0,
    TYPE_OTHER = 1,
    TYPE_PAINTED_TRAFFIC_SIGN = 2,
    TYPE_SYMBOLIC_TRAFFIC_SIGN = 3,
    TYPE_TEXTUAL_TRAFFIC_SIGN = 4,
    TYPE_GENERIC_SYMBOL = 5,
    TYPE_GENERIC_LINE = 6,
    TYPE_GENERIC_TEXT = 7,
}

namespace osi3.RoadMarking_.Classification_;
enum Color : int {
    COLOR_UNKNOWN = 0,
    COLOR_OTHER = 1,
    COLOR_WHITE = 2,
    COLOR_YELLOW = 3,
    COLOR_BLUE = 5,
    COLOR_RED = 6,
    COLOR_GREEN = 7,
    COLOR_VIOLET = 8,
    COLOR_ORANGE = 9,
}

namespace osi3.RoadMarking_;
table Classification {
  type:osi3.RoadMarking_.Classification_.Type;
  traffic_main_sign_type:osi3.TrafficSign_.MainSign_.Classification_.Type;
  monochrome_color:osi3.RoadMarking_.Classification_.Color;
  value:osi3.TrafficSignValue;
  value_text:string;
  assigned_lane_id:[osi3.Identifier];
  is_out_of_service:bool;
  country:string;
  country_revision:string;
  code:string;
  sub_code:string;
  logical_lane_assignment:[osi3.LogicalLaneAssignment];
}

namespace osi3;
table RoadMarking {
  id:osi3.Identifier;
  base:osi3.BaseStationary;
  classification:osi3.RoadMarking_.Classification;
  source_reference:[osi3.ExternalReference];
  color_description:osi3.ColorDescription;
}
