// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIENVIRONMENT_OSI3_ENVIRONMENTALCONDITIONS__H_
#define FLATBUFFERS_GENERATED_OSIENVIRONMENT_OSI3_ENVIRONMENTALCONDITIONS__H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {

struct EnvironmentalConditions;
struct EnvironmentalConditionsBuilder;

namespace EnvironmentalConditions_ {

struct TimeOfDay;
struct TimeOfDayBuilder;

struct CloudLayer;
struct CloudLayerBuilder;

struct Wind;
struct WindBuilder;

struct Sun;
struct SunBuilder;

enum Precipitation : int32_t {
  Precipitation_PRECIPITATION_UNKNOWN = 0,
  Precipitation_PRECIPITATION_OTHER = 1,
  Precipitation_PRECIPITATION_NONE = 2,
  Precipitation_PRECIPITATION_VERY_LIGHT = 3,
  Precipitation_PRECIPITATION_LIGHT = 4,
  Precipitation_PRECIPITATION_MODERATE = 5,
  Precipitation_PRECIPITATION_HEAVY = 6,
  Precipitation_PRECIPITATION_VERY_HEAVY = 7,
  Precipitation_PRECIPITATION_EXTREME = 8,
  Precipitation_MIN = Precipitation_PRECIPITATION_UNKNOWN,
  Precipitation_MAX = Precipitation_PRECIPITATION_EXTREME
};

inline const Precipitation (&EnumValuesPrecipitation())[9] {
  static const Precipitation values[] = {
    Precipitation_PRECIPITATION_UNKNOWN,
    Precipitation_PRECIPITATION_OTHER,
    Precipitation_PRECIPITATION_NONE,
    Precipitation_PRECIPITATION_VERY_LIGHT,
    Precipitation_PRECIPITATION_LIGHT,
    Precipitation_PRECIPITATION_MODERATE,
    Precipitation_PRECIPITATION_HEAVY,
    Precipitation_PRECIPITATION_VERY_HEAVY,
    Precipitation_PRECIPITATION_EXTREME
  };
  return values;
}

inline const char * const *EnumNamesPrecipitation() {
  static const char * const names[10] = {
    "PRECIPITATION_UNKNOWN",
    "PRECIPITATION_OTHER",
    "PRECIPITATION_NONE",
    "PRECIPITATION_VERY_LIGHT",
    "PRECIPITATION_LIGHT",
    "PRECIPITATION_MODERATE",
    "PRECIPITATION_HEAVY",
    "PRECIPITATION_VERY_HEAVY",
    "PRECIPITATION_EXTREME",
    nullptr
  };
  return names;
}

inline const char *EnumNamePrecipitation(Precipitation e) {
  if (::flatbuffers::IsOutRange(e, Precipitation_PRECIPITATION_UNKNOWN, Precipitation_PRECIPITATION_EXTREME)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPrecipitation()[index];
}

enum Fog : int32_t {
  Fog_FOG_UNKNOWN = 0,
  Fog_FOG_OTHER = 1,
  Fog_FOG_EXCELLENT_VISIBILITY = 2,
  Fog_FOG_GOOD_VISIBILITY = 3,
  Fog_FOG_MODERATE_VISIBILITY = 4,
  Fog_FOG_POOR_VISIBILITY = 5,
  Fog_FOG_MIST = 6,
  Fog_FOG_LIGHT = 7,
  Fog_FOG_THICK = 8,
  Fog_FOG_DENSE = 9,
  Fog_MIN = Fog_FOG_UNKNOWN,
  Fog_MAX = Fog_FOG_DENSE
};

inline const Fog (&EnumValuesFog())[10] {
  static const Fog values[] = {
    Fog_FOG_UNKNOWN,
    Fog_FOG_OTHER,
    Fog_FOG_EXCELLENT_VISIBILITY,
    Fog_FOG_GOOD_VISIBILITY,
    Fog_FOG_MODERATE_VISIBILITY,
    Fog_FOG_POOR_VISIBILITY,
    Fog_FOG_MIST,
    Fog_FOG_LIGHT,
    Fog_FOG_THICK,
    Fog_FOG_DENSE
  };
  return values;
}

inline const char * const *EnumNamesFog() {
  static const char * const names[11] = {
    "FOG_UNKNOWN",
    "FOG_OTHER",
    "FOG_EXCELLENT_VISIBILITY",
    "FOG_GOOD_VISIBILITY",
    "FOG_MODERATE_VISIBILITY",
    "FOG_POOR_VISIBILITY",
    "FOG_MIST",
    "FOG_LIGHT",
    "FOG_THICK",
    "FOG_DENSE",
    nullptr
  };
  return names;
}

inline const char *EnumNameFog(Fog e) {
  if (::flatbuffers::IsOutRange(e, Fog_FOG_UNKNOWN, Fog_FOG_DENSE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFog()[index];
}

enum AmbientIllumination : int32_t {
  AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN = 0,
  AmbientIllumination_AMBIENT_ILLUMINATION_OTHER = 1,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL1 = 2,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL2 = 3,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL3 = 4,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL4 = 5,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL5 = 6,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL6 = 7,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL7 = 8,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL8 = 9,
  AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL9 = 10,
  AmbientIllumination_MIN = AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN,
  AmbientIllumination_MAX = AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL9
};

inline const AmbientIllumination (&EnumValuesAmbientIllumination())[11] {
  static const AmbientIllumination values[] = {
    AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN,
    AmbientIllumination_AMBIENT_ILLUMINATION_OTHER,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL1,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL2,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL3,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL4,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL5,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL6,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL7,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL8,
    AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL9
  };
  return values;
}

inline const char * const *EnumNamesAmbientIllumination() {
  static const char * const names[12] = {
    "AMBIENT_ILLUMINATION_UNKNOWN",
    "AMBIENT_ILLUMINATION_OTHER",
    "AMBIENT_ILLUMINATION_LEVEL1",
    "AMBIENT_ILLUMINATION_LEVEL2",
    "AMBIENT_ILLUMINATION_LEVEL3",
    "AMBIENT_ILLUMINATION_LEVEL4",
    "AMBIENT_ILLUMINATION_LEVEL5",
    "AMBIENT_ILLUMINATION_LEVEL6",
    "AMBIENT_ILLUMINATION_LEVEL7",
    "AMBIENT_ILLUMINATION_LEVEL8",
    "AMBIENT_ILLUMINATION_LEVEL9",
    nullptr
  };
  return names;
}

inline const char *EnumNameAmbientIllumination(AmbientIllumination e) {
  if (::flatbuffers::IsOutRange(e, AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN, AmbientIllumination_AMBIENT_ILLUMINATION_LEVEL9)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAmbientIllumination()[index];
}

namespace CloudLayer_ {

enum FractionalCloudCover : int32_t {
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_UNKNOWN = 0,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_OTHER = 1,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_ZERO_OKTAS = 2,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_ONE_OKTAS = 3,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_TWO_OKTAS = 4,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_THREE_OKTAS = 5,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_FOUR_OKTAS = 6,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_FIVE_OKTAS = 7,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SIX_OKTAS = 8,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SEVEN_OKTAS = 9,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_EIGHT_OKTAS = 10,
  FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SKY_OBSCURED = 11,
  FractionalCloudCover_MIN = FractionalCloudCover_FRACTIONAL_CLOUD_COVER_UNKNOWN,
  FractionalCloudCover_MAX = FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SKY_OBSCURED
};

inline const FractionalCloudCover (&EnumValuesFractionalCloudCover())[12] {
  static const FractionalCloudCover values[] = {
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_UNKNOWN,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_OTHER,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_ZERO_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_ONE_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_TWO_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_THREE_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_FOUR_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_FIVE_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SIX_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SEVEN_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_EIGHT_OKTAS,
    FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SKY_OBSCURED
  };
  return values;
}

inline const char * const *EnumNamesFractionalCloudCover() {
  static const char * const names[13] = {
    "FRACTIONAL_CLOUD_COVER_UNKNOWN",
    "FRACTIONAL_CLOUD_COVER_OTHER",
    "FRACTIONAL_CLOUD_COVER_ZERO_OKTAS",
    "FRACTIONAL_CLOUD_COVER_ONE_OKTAS",
    "FRACTIONAL_CLOUD_COVER_TWO_OKTAS",
    "FRACTIONAL_CLOUD_COVER_THREE_OKTAS",
    "FRACTIONAL_CLOUD_COVER_FOUR_OKTAS",
    "FRACTIONAL_CLOUD_COVER_FIVE_OKTAS",
    "FRACTIONAL_CLOUD_COVER_SIX_OKTAS",
    "FRACTIONAL_CLOUD_COVER_SEVEN_OKTAS",
    "FRACTIONAL_CLOUD_COVER_EIGHT_OKTAS",
    "FRACTIONAL_CLOUD_COVER_SKY_OBSCURED",
    nullptr
  };
  return names;
}

inline const char *EnumNameFractionalCloudCover(FractionalCloudCover e) {
  if (::flatbuffers::IsOutRange(e, FractionalCloudCover_FRACTIONAL_CLOUD_COVER_UNKNOWN, FractionalCloudCover_FRACTIONAL_CLOUD_COVER_SKY_OBSCURED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFractionalCloudCover()[index];
}

}  // namespace CloudLayer_
}  // namespace EnvironmentalConditions_

struct EnvironmentalConditions FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EnvironmentalConditionsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AMBIENT_ILLUMINATION = 4,
    VT_TIME_OF_DAY = 6,
    VT_UNIX_TIMESTAMP = 8,
    VT_ATMOSPHERIC_PRESSURE = 10,
    VT_TEMPERATURE = 12,
    VT_RELATIVE_HUMIDITY = 14,
    VT_PRECIPITATION = 16,
    VT_FOG = 18,
    VT_SOURCE_REFERENCE = 20,
    VT_CLOUDS = 22,
    VT_WIND = 24,
    VT_SUN = 26
  };
  osi3::EnvironmentalConditions_::AmbientIllumination ambient_illumination() const {
    return static_cast<osi3::EnvironmentalConditions_::AmbientIllumination>(GetField<int32_t>(VT_AMBIENT_ILLUMINATION, 0));
  }
  const osi3::EnvironmentalConditions_::TimeOfDay *time_of_day() const {
    return GetPointer<const osi3::EnvironmentalConditions_::TimeOfDay *>(VT_TIME_OF_DAY);
  }
  int64_t unix_timestamp() const {
    return GetField<int64_t>(VT_UNIX_TIMESTAMP, 0);
  }
  double atmospheric_pressure() const {
    return GetField<double>(VT_ATMOSPHERIC_PRESSURE, 0.0);
  }
  double temperature() const {
    return GetField<double>(VT_TEMPERATURE, 0.0);
  }
  double relative_humidity() const {
    return GetField<double>(VT_RELATIVE_HUMIDITY, 0.0);
  }
  osi3::EnvironmentalConditions_::Precipitation precipitation() const {
    return static_cast<osi3::EnvironmentalConditions_::Precipitation>(GetField<int32_t>(VT_PRECIPITATION, 0));
  }
  osi3::EnvironmentalConditions_::Fog fog() const {
    return static_cast<osi3::EnvironmentalConditions_::Fog>(GetField<int32_t>(VT_FOG, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::EnvironmentalConditions_::CloudLayer *clouds() const {
    return GetPointer<const osi3::EnvironmentalConditions_::CloudLayer *>(VT_CLOUDS);
  }
  const osi3::EnvironmentalConditions_::Wind *wind() const {
    return GetPointer<const osi3::EnvironmentalConditions_::Wind *>(VT_WIND);
  }
  const osi3::EnvironmentalConditions_::Sun *sun() const {
    return GetPointer<const osi3::EnvironmentalConditions_::Sun *>(VT_SUN);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_AMBIENT_ILLUMINATION, 4) &&
           VerifyOffset(verifier, VT_TIME_OF_DAY) &&
           verifier.VerifyTable(time_of_day()) &&
           VerifyField<int64_t>(verifier, VT_UNIX_TIMESTAMP, 8) &&
           VerifyField<double>(verifier, VT_ATMOSPHERIC_PRESSURE, 8) &&
           VerifyField<double>(verifier, VT_TEMPERATURE, 8) &&
           VerifyField<double>(verifier, VT_RELATIVE_HUMIDITY, 8) &&
           VerifyField<int32_t>(verifier, VT_PRECIPITATION, 4) &&
           VerifyField<int32_t>(verifier, VT_FOG, 4) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_CLOUDS) &&
           verifier.VerifyTable(clouds()) &&
           VerifyOffset(verifier, VT_WIND) &&
           verifier.VerifyTable(wind()) &&
           VerifyOffset(verifier, VT_SUN) &&
           verifier.VerifyTable(sun()) &&
           verifier.EndTable();
  }
};

struct EnvironmentalConditionsBuilder {
  typedef EnvironmentalConditions Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ambient_illumination(osi3::EnvironmentalConditions_::AmbientIllumination ambient_illumination) {
    fbb_.AddElement<int32_t>(EnvironmentalConditions::VT_AMBIENT_ILLUMINATION, static_cast<int32_t>(ambient_illumination), 0);
  }
  void add_time_of_day(::flatbuffers::Offset<osi3::EnvironmentalConditions_::TimeOfDay> time_of_day) {
    fbb_.AddOffset(EnvironmentalConditions::VT_TIME_OF_DAY, time_of_day);
  }
  void add_unix_timestamp(int64_t unix_timestamp) {
    fbb_.AddElement<int64_t>(EnvironmentalConditions::VT_UNIX_TIMESTAMP, unix_timestamp, 0);
  }
  void add_atmospheric_pressure(double atmospheric_pressure) {
    fbb_.AddElement<double>(EnvironmentalConditions::VT_ATMOSPHERIC_PRESSURE, atmospheric_pressure, 0.0);
  }
  void add_temperature(double temperature) {
    fbb_.AddElement<double>(EnvironmentalConditions::VT_TEMPERATURE, temperature, 0.0);
  }
  void add_relative_humidity(double relative_humidity) {
    fbb_.AddElement<double>(EnvironmentalConditions::VT_RELATIVE_HUMIDITY, relative_humidity, 0.0);
  }
  void add_precipitation(osi3::EnvironmentalConditions_::Precipitation precipitation) {
    fbb_.AddElement<int32_t>(EnvironmentalConditions::VT_PRECIPITATION, static_cast<int32_t>(precipitation), 0);
  }
  void add_fog(osi3::EnvironmentalConditions_::Fog fog) {
    fbb_.AddElement<int32_t>(EnvironmentalConditions::VT_FOG, static_cast<int32_t>(fog), 0);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(EnvironmentalConditions::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_clouds(::flatbuffers::Offset<osi3::EnvironmentalConditions_::CloudLayer> clouds) {
    fbb_.AddOffset(EnvironmentalConditions::VT_CLOUDS, clouds);
  }
  void add_wind(::flatbuffers::Offset<osi3::EnvironmentalConditions_::Wind> wind) {
    fbb_.AddOffset(EnvironmentalConditions::VT_WIND, wind);
  }
  void add_sun(::flatbuffers::Offset<osi3::EnvironmentalConditions_::Sun> sun) {
    fbb_.AddOffset(EnvironmentalConditions::VT_SUN, sun);
  }
  explicit EnvironmentalConditionsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EnvironmentalConditions> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EnvironmentalConditions>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EnvironmentalConditions> CreateEnvironmentalConditions(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::EnvironmentalConditions_::AmbientIllumination ambient_illumination = osi3::EnvironmentalConditions_::AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::TimeOfDay> time_of_day = 0,
    int64_t unix_timestamp = 0,
    double atmospheric_pressure = 0.0,
    double temperature = 0.0,
    double relative_humidity = 0.0,
    osi3::EnvironmentalConditions_::Precipitation precipitation = osi3::EnvironmentalConditions_::Precipitation_PRECIPITATION_UNKNOWN,
    osi3::EnvironmentalConditions_::Fog fog = osi3::EnvironmentalConditions_::Fog_FOG_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::CloudLayer> clouds = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::Wind> wind = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::Sun> sun = 0) {
  EnvironmentalConditionsBuilder builder_(_fbb);
  builder_.add_relative_humidity(relative_humidity);
  builder_.add_temperature(temperature);
  builder_.add_atmospheric_pressure(atmospheric_pressure);
  builder_.add_unix_timestamp(unix_timestamp);
  builder_.add_sun(sun);
  builder_.add_wind(wind);
  builder_.add_clouds(clouds);
  builder_.add_source_reference(source_reference);
  builder_.add_fog(fog);
  builder_.add_precipitation(precipitation);
  builder_.add_time_of_day(time_of_day);
  builder_.add_ambient_illumination(ambient_illumination);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EnvironmentalConditions> CreateEnvironmentalConditionsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::EnvironmentalConditions_::AmbientIllumination ambient_illumination = osi3::EnvironmentalConditions_::AmbientIllumination_AMBIENT_ILLUMINATION_UNKNOWN,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::TimeOfDay> time_of_day = 0,
    int64_t unix_timestamp = 0,
    double atmospheric_pressure = 0.0,
    double temperature = 0.0,
    double relative_humidity = 0.0,
    osi3::EnvironmentalConditions_::Precipitation precipitation = osi3::EnvironmentalConditions_::Precipitation_PRECIPITATION_UNKNOWN,
    osi3::EnvironmentalConditions_::Fog fog = osi3::EnvironmentalConditions_::Fog_FOG_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::CloudLayer> clouds = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::Wind> wind = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions_::Sun> sun = 0) {
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateEnvironmentalConditions(
      _fbb,
      ambient_illumination,
      time_of_day,
      unix_timestamp,
      atmospheric_pressure,
      temperature,
      relative_humidity,
      precipitation,
      fog,
      source_reference__,
      clouds,
      wind,
      sun);
}

namespace EnvironmentalConditions_ {

struct TimeOfDay FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TimeOfDayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SECONDS_SINCE_MIDNIGHT = 4
  };
  uint32_t seconds_since_midnight() const {
    return GetField<uint32_t>(VT_SECONDS_SINCE_MIDNIGHT, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_SECONDS_SINCE_MIDNIGHT, 4) &&
           verifier.EndTable();
  }
};

struct TimeOfDayBuilder {
  typedef TimeOfDay Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seconds_since_midnight(uint32_t seconds_since_midnight) {
    fbb_.AddElement<uint32_t>(TimeOfDay::VT_SECONDS_SINCE_MIDNIGHT, seconds_since_midnight, 0);
  }
  explicit TimeOfDayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TimeOfDay> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TimeOfDay>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TimeOfDay> CreateTimeOfDay(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t seconds_since_midnight = 0) {
  TimeOfDayBuilder builder_(_fbb);
  builder_.add_seconds_since_midnight(seconds_since_midnight);
  return builder_.Finish();
}

struct CloudLayer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CloudLayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FRACTIONAL_CLOUD_COVER = 4
  };
  osi3::EnvironmentalConditions_::CloudLayer_::FractionalCloudCover fractional_cloud_cover() const {
    return static_cast<osi3::EnvironmentalConditions_::CloudLayer_::FractionalCloudCover>(GetField<int32_t>(VT_FRACTIONAL_CLOUD_COVER, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_FRACTIONAL_CLOUD_COVER, 4) &&
           verifier.EndTable();
  }
};

struct CloudLayerBuilder {
  typedef CloudLayer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fractional_cloud_cover(osi3::EnvironmentalConditions_::CloudLayer_::FractionalCloudCover fractional_cloud_cover) {
    fbb_.AddElement<int32_t>(CloudLayer::VT_FRACTIONAL_CLOUD_COVER, static_cast<int32_t>(fractional_cloud_cover), 0);
  }
  explicit CloudLayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CloudLayer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CloudLayer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CloudLayer> CreateCloudLayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::EnvironmentalConditions_::CloudLayer_::FractionalCloudCover fractional_cloud_cover = osi3::EnvironmentalConditions_::CloudLayer_::FractionalCloudCover_FRACTIONAL_CLOUD_COVER_UNKNOWN) {
  CloudLayerBuilder builder_(_fbb);
  builder_.add_fractional_cloud_cover(fractional_cloud_cover);
  return builder_.Finish();
}

struct Wind FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WindBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORIGIN_DIRECTION = 4,
    VT_SPEED = 6
  };
  double origin_direction() const {
    return GetField<double>(VT_ORIGIN_DIRECTION, 0.0);
  }
  double speed() const {
    return GetField<double>(VT_SPEED, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_ORIGIN_DIRECTION, 8) &&
           VerifyField<double>(verifier, VT_SPEED, 8) &&
           verifier.EndTable();
  }
};

struct WindBuilder {
  typedef Wind Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_origin_direction(double origin_direction) {
    fbb_.AddElement<double>(Wind::VT_ORIGIN_DIRECTION, origin_direction, 0.0);
  }
  void add_speed(double speed) {
    fbb_.AddElement<double>(Wind::VT_SPEED, speed, 0.0);
  }
  explicit WindBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Wind> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Wind>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Wind> CreateWind(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double origin_direction = 0.0,
    double speed = 0.0) {
  WindBuilder builder_(_fbb);
  builder_.add_speed(speed);
  builder_.add_origin_direction(origin_direction);
  return builder_.Finish();
}

struct Sun FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SunBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AZIMUTH = 4,
    VT_ELEVATION = 6,
    VT_INTENSITY = 8
  };
  double azimuth() const {
    return GetField<double>(VT_AZIMUTH, 0.0);
  }
  double elevation() const {
    return GetField<double>(VT_ELEVATION, 0.0);
  }
  double intensity() const {
    return GetField<double>(VT_INTENSITY, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_AZIMUTH, 8) &&
           VerifyField<double>(verifier, VT_ELEVATION, 8) &&
           VerifyField<double>(verifier, VT_INTENSITY, 8) &&
           verifier.EndTable();
  }
};

struct SunBuilder {
  typedef Sun Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_azimuth(double azimuth) {
    fbb_.AddElement<double>(Sun::VT_AZIMUTH, azimuth, 0.0);
  }
  void add_elevation(double elevation) {
    fbb_.AddElement<double>(Sun::VT_ELEVATION, elevation, 0.0);
  }
  void add_intensity(double intensity) {
    fbb_.AddElement<double>(Sun::VT_INTENSITY, intensity, 0.0);
  }
  explicit SunBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Sun> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Sun>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Sun> CreateSun(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double azimuth = 0.0,
    double elevation = 0.0,
    double intensity = 0.0) {
  SunBuilder builder_(_fbb);
  builder_.add_intensity(intensity);
  builder_.add_elevation(elevation);
  builder_.add_azimuth(azimuth);
  return builder_.Finish();
}

}  // namespace EnvironmentalConditions_

namespace EnvironmentalConditions_ {

}  // namespace EnvironmentalConditions_
}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIENVIRONMENT_OSI3_ENVIRONMENTALCONDITIONS__H_
