// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIOBJECT_OSI3_MOVINGOBJECT__PEDESTRIANATTRIBUTES__H_
#define FLATBUFFERS_GENERATED_OSIOBJECT_OSI3_MOVINGOBJECT__PEDESTRIANATTRIBUTES__H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {

struct StationaryObject;
struct StationaryObjectBuilder;

namespace StationaryObject_ {

struct Classification;
struct ClassificationBuilder;

namespace Classification_ {

struct EmittingStructureAttribute;
struct EmittingStructureAttributeBuilder;

}  // namespace Classification_
}  // namespace StationaryObject_

struct MovingObject;
struct MovingObjectBuilder;

namespace MovingObject_ {

struct VehicleAttributes;
struct VehicleAttributesBuilder;

namespace VehicleAttributes_ {

struct WheelData;
struct WheelDataBuilder;

}  // namespace VehicleAttributes_

struct MovingObjectClassification;
struct MovingObjectClassificationBuilder;

struct VehicleClassification;
struct VehicleClassificationBuilder;

namespace VehicleClassification_ {

struct LightState;
struct LightStateBuilder;

}  // namespace VehicleClassification_

struct PedestrianAttributes;
struct PedestrianAttributesBuilder;

namespace PedestrianAttributes_ {

struct Bone;
struct BoneBuilder;

}  // namespace PedestrianAttributes_
}  // namespace MovingObject_

namespace StationaryObject_ {
namespace Classification_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_BRIDGE = 2,
  Type_TYPE_BUILDING = 3,
  Type_TYPE_POLE = 4,
  Type_TYPE_PYLON = 5,
  Type_TYPE_DELINEATOR = 6,
  Type_TYPE_TREE = 7,
  Type_TYPE_BARRIER = 8,
  Type_TYPE_VEGETATION = 9,
  Type_TYPE_CURBSTONE = 10,
  Type_TYPE_WALL = 11,
  Type_TYPE_VERTICAL_STRUCTURE = 12,
  Type_TYPE_RECTANGULAR_STRUCTURE = 13,
  Type_TYPE_OVERHEAD_STRUCTURE = 14,
  Type_TYPE_REFLECTIVE_STRUCTURE = 15,
  Type_TYPE_CONSTRUCTION_SITE_ELEMENT = 16,
  Type_TYPE_SPEED_BUMP = 17,
  Type_TYPE_EMITTING_STRUCTURE = 18,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_EMITTING_STRUCTURE
};

inline const Type (&EnumValuesType())[19] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_BRIDGE,
    Type_TYPE_BUILDING,
    Type_TYPE_POLE,
    Type_TYPE_PYLON,
    Type_TYPE_DELINEATOR,
    Type_TYPE_TREE,
    Type_TYPE_BARRIER,
    Type_TYPE_VEGETATION,
    Type_TYPE_CURBSTONE,
    Type_TYPE_WALL,
    Type_TYPE_VERTICAL_STRUCTURE,
    Type_TYPE_RECTANGULAR_STRUCTURE,
    Type_TYPE_OVERHEAD_STRUCTURE,
    Type_TYPE_REFLECTIVE_STRUCTURE,
    Type_TYPE_CONSTRUCTION_SITE_ELEMENT,
    Type_TYPE_SPEED_BUMP,
    Type_TYPE_EMITTING_STRUCTURE
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[20] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_BRIDGE",
    "TYPE_BUILDING",
    "TYPE_POLE",
    "TYPE_PYLON",
    "TYPE_DELINEATOR",
    "TYPE_TREE",
    "TYPE_BARRIER",
    "TYPE_VEGETATION",
    "TYPE_CURBSTONE",
    "TYPE_WALL",
    "TYPE_VERTICAL_STRUCTURE",
    "TYPE_RECTANGULAR_STRUCTURE",
    "TYPE_OVERHEAD_STRUCTURE",
    "TYPE_REFLECTIVE_STRUCTURE",
    "TYPE_CONSTRUCTION_SITE_ELEMENT",
    "TYPE_SPEED_BUMP",
    "TYPE_EMITTING_STRUCTURE",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_EMITTING_STRUCTURE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

enum Material : int32_t {
  Material_MATERIAL_UNKNOWN = 0,
  Material_MATERIAL_OTHER = 1,
  Material_MATERIAL_WOOD = 2,
  Material_MATERIAL_PLASTIC = 3,
  Material_MATERIAL_CONCRETE = 4,
  Material_MATERIAL_METAL = 5,
  Material_MATERIAL_STONE = 6,
  Material_MATERIAL_GLAS = 7,
  Material_MATERIAL_MUD = 8,
  Material_MIN = Material_MATERIAL_UNKNOWN,
  Material_MAX = Material_MATERIAL_MUD
};

inline const Material (&EnumValuesMaterial())[9] {
  static const Material values[] = {
    Material_MATERIAL_UNKNOWN,
    Material_MATERIAL_OTHER,
    Material_MATERIAL_WOOD,
    Material_MATERIAL_PLASTIC,
    Material_MATERIAL_CONCRETE,
    Material_MATERIAL_METAL,
    Material_MATERIAL_STONE,
    Material_MATERIAL_GLAS,
    Material_MATERIAL_MUD
  };
  return values;
}

inline const char * const *EnumNamesMaterial() {
  static const char * const names[10] = {
    "MATERIAL_UNKNOWN",
    "MATERIAL_OTHER",
    "MATERIAL_WOOD",
    "MATERIAL_PLASTIC",
    "MATERIAL_CONCRETE",
    "MATERIAL_METAL",
    "MATERIAL_STONE",
    "MATERIAL_GLAS",
    "MATERIAL_MUD",
    nullptr
  };
  return names;
}

inline const char *EnumNameMaterial(Material e) {
  if (::flatbuffers::IsOutRange(e, Material_MATERIAL_UNKNOWN, Material_MATERIAL_MUD)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMaterial()[index];
}

enum Density : int32_t {
  Density_DENSITY_UNKNOWN = 0,
  Density_DENSITY_OTHER = 1,
  Density_DENSITY_SOLID = 2,
  Density_DENSITY_SMALL_MESH = 3,
  Density_DENSITY_MEDIAN_MESH = 4,
  Density_DENSITY_LARGE_MESH = 5,
  Density_DENSITY_OPEN = 6,
  Density_MIN = Density_DENSITY_UNKNOWN,
  Density_MAX = Density_DENSITY_OPEN
};

inline const Density (&EnumValuesDensity())[7] {
  static const Density values[] = {
    Density_DENSITY_UNKNOWN,
    Density_DENSITY_OTHER,
    Density_DENSITY_SOLID,
    Density_DENSITY_SMALL_MESH,
    Density_DENSITY_MEDIAN_MESH,
    Density_DENSITY_LARGE_MESH,
    Density_DENSITY_OPEN
  };
  return values;
}

inline const char * const *EnumNamesDensity() {
  static const char * const names[8] = {
    "DENSITY_UNKNOWN",
    "DENSITY_OTHER",
    "DENSITY_SOLID",
    "DENSITY_SMALL_MESH",
    "DENSITY_MEDIAN_MESH",
    "DENSITY_LARGE_MESH",
    "DENSITY_OPEN",
    nullptr
  };
  return names;
}

inline const char *EnumNameDensity(Density e) {
  if (::flatbuffers::IsOutRange(e, Density_DENSITY_UNKNOWN, Density_DENSITY_OPEN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDensity()[index];
}

enum Color : int32_t {
  Color_COLOR_UNKNOWN = 0,
  Color_COLOR_OTHER = 1,
  Color_COLOR_YELLOW = 2,
  Color_COLOR_GREEN = 3,
  Color_COLOR_BLUE = 4,
  Color_COLOR_VIOLET = 5,
  Color_COLOR_RED = 6,
  Color_COLOR_ORANGE = 7,
  Color_COLOR_BLACK = 8,
  Color_COLOR_GRAY = 9,
  Color_COLOR_WHITE = 10,
  Color_MIN = Color_COLOR_UNKNOWN,
  Color_MAX = Color_COLOR_WHITE
};

inline const Color (&EnumValuesColor())[11] {
  static const Color values[] = {
    Color_COLOR_UNKNOWN,
    Color_COLOR_OTHER,
    Color_COLOR_YELLOW,
    Color_COLOR_GREEN,
    Color_COLOR_BLUE,
    Color_COLOR_VIOLET,
    Color_COLOR_RED,
    Color_COLOR_ORANGE,
    Color_COLOR_BLACK,
    Color_COLOR_GRAY,
    Color_COLOR_WHITE
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[12] = {
    "COLOR_UNKNOWN",
    "COLOR_OTHER",
    "COLOR_YELLOW",
    "COLOR_GREEN",
    "COLOR_BLUE",
    "COLOR_VIOLET",
    "COLOR_RED",
    "COLOR_ORANGE",
    "COLOR_BLACK",
    "COLOR_GRAY",
    "COLOR_WHITE",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (::flatbuffers::IsOutRange(e, Color_COLOR_UNKNOWN, Color_COLOR_WHITE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

}  // namespace Classification_
}  // namespace StationaryObject_

namespace MovingObject_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_VEHICLE = 2,
  Type_TYPE_PEDESTRIAN = 3,
  Type_TYPE_ANIMAL = 4,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_ANIMAL
};

inline const Type (&EnumValuesType())[5] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_VEHICLE,
    Type_TYPE_PEDESTRIAN,
    Type_TYPE_ANIMAL
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[6] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_VEHICLE",
    "TYPE_PEDESTRIAN",
    "TYPE_ANIMAL",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_ANIMAL)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

namespace VehicleClassification_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_SMALL_CAR = 2,
  Type_TYPE_COMPACT_CAR = 3,
  Type_TYPE_CAR = 4,
  Type_TYPE_LUXURY_CAR = 5,
  Type_TYPE_DELIVERY_VAN = 6,
  Type_TYPE_HEAVY_TRUCK = 7,
  Type_TYPE_SEMITRAILER = 8,
  Type_TYPE_TRAILER = 9,
  Type_TYPE_MOTORBIKE = 10,
  Type_TYPE_BICYCLE = 11,
  Type_TYPE_BUS = 12,
  Type_TYPE_TRAM = 13,
  Type_TYPE_TRAIN = 14,
  Type_TYPE_WHEELCHAIR = 15,
  Type_TYPE_SEMITRACTOR = 16,
  Type_TYPE_STANDUP_SCOOTER = 17,
  Type_TYPE_MICROMOBILITY_DEVICE = 18,
  Type_TYPE_WORK_MACHINE = 19,
  Type_TYPE_WATERCRAFT = 20,
  Type_TYPE_AIRCRAFT = 21,
  Type_TYPE_LAND_VEHICLE = 22,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_LAND_VEHICLE
};

inline const Type (&EnumValuesType())[23] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_SMALL_CAR,
    Type_TYPE_COMPACT_CAR,
    Type_TYPE_CAR,
    Type_TYPE_LUXURY_CAR,
    Type_TYPE_DELIVERY_VAN,
    Type_TYPE_HEAVY_TRUCK,
    Type_TYPE_SEMITRAILER,
    Type_TYPE_TRAILER,
    Type_TYPE_MOTORBIKE,
    Type_TYPE_BICYCLE,
    Type_TYPE_BUS,
    Type_TYPE_TRAM,
    Type_TYPE_TRAIN,
    Type_TYPE_WHEELCHAIR,
    Type_TYPE_SEMITRACTOR,
    Type_TYPE_STANDUP_SCOOTER,
    Type_TYPE_MICROMOBILITY_DEVICE,
    Type_TYPE_WORK_MACHINE,
    Type_TYPE_WATERCRAFT,
    Type_TYPE_AIRCRAFT,
    Type_TYPE_LAND_VEHICLE
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[24] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_SMALL_CAR",
    "TYPE_COMPACT_CAR",
    "TYPE_CAR",
    "TYPE_LUXURY_CAR",
    "TYPE_DELIVERY_VAN",
    "TYPE_HEAVY_TRUCK",
    "TYPE_SEMITRAILER",
    "TYPE_TRAILER",
    "TYPE_MOTORBIKE",
    "TYPE_BICYCLE",
    "TYPE_BUS",
    "TYPE_TRAM",
    "TYPE_TRAIN",
    "TYPE_WHEELCHAIR",
    "TYPE_SEMITRACTOR",
    "TYPE_STANDUP_SCOOTER",
    "TYPE_MICROMOBILITY_DEVICE",
    "TYPE_WORK_MACHINE",
    "TYPE_WATERCRAFT",
    "TYPE_AIRCRAFT",
    "TYPE_LAND_VEHICLE",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_LAND_VEHICLE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

namespace LightState_ {

enum IndicatorState : int32_t {
  IndicatorState_INDICATOR_STATE_UNKNOWN = 0,
  IndicatorState_INDICATOR_STATE_OTHER = 1,
  IndicatorState_INDICATOR_STATE_OFF = 2,
  IndicatorState_INDICATOR_STATE_LEFT = 3,
  IndicatorState_INDICATOR_STATE_RIGHT = 4,
  IndicatorState_INDICATOR_STATE_WARNING = 5,
  IndicatorState_MIN = IndicatorState_INDICATOR_STATE_UNKNOWN,
  IndicatorState_MAX = IndicatorState_INDICATOR_STATE_WARNING
};

inline const IndicatorState (&EnumValuesIndicatorState())[6] {
  static const IndicatorState values[] = {
    IndicatorState_INDICATOR_STATE_UNKNOWN,
    IndicatorState_INDICATOR_STATE_OTHER,
    IndicatorState_INDICATOR_STATE_OFF,
    IndicatorState_INDICATOR_STATE_LEFT,
    IndicatorState_INDICATOR_STATE_RIGHT,
    IndicatorState_INDICATOR_STATE_WARNING
  };
  return values;
}

inline const char * const *EnumNamesIndicatorState() {
  static const char * const names[7] = {
    "INDICATOR_STATE_UNKNOWN",
    "INDICATOR_STATE_OTHER",
    "INDICATOR_STATE_OFF",
    "INDICATOR_STATE_LEFT",
    "INDICATOR_STATE_RIGHT",
    "INDICATOR_STATE_WARNING",
    nullptr
  };
  return names;
}

inline const char *EnumNameIndicatorState(IndicatorState e) {
  if (::flatbuffers::IsOutRange(e, IndicatorState_INDICATOR_STATE_UNKNOWN, IndicatorState_INDICATOR_STATE_WARNING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesIndicatorState()[index];
}

enum GenericLightState : int32_t {
  GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN = 0,
  GenericLightState_GENERIC_LIGHT_STATE_OTHER = 1,
  GenericLightState_GENERIC_LIGHT_STATE_OFF = 2,
  GenericLightState_GENERIC_LIGHT_STATE_ON = 3,
  GenericLightState_GENERIC_LIGHT_STATE_FLASHING_BLUE = 4,
  GenericLightState_GENERIC_LIGHT_STATE_FLASHING_BLUE_AND_RED = 5,
  GenericLightState_GENERIC_LIGHT_STATE_FLASHING_AMBER = 6,
  GenericLightState_MIN = GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
  GenericLightState_MAX = GenericLightState_GENERIC_LIGHT_STATE_FLASHING_AMBER
};

inline const GenericLightState (&EnumValuesGenericLightState())[7] {
  static const GenericLightState values[] = {
    GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    GenericLightState_GENERIC_LIGHT_STATE_OTHER,
    GenericLightState_GENERIC_LIGHT_STATE_OFF,
    GenericLightState_GENERIC_LIGHT_STATE_ON,
    GenericLightState_GENERIC_LIGHT_STATE_FLASHING_BLUE,
    GenericLightState_GENERIC_LIGHT_STATE_FLASHING_BLUE_AND_RED,
    GenericLightState_GENERIC_LIGHT_STATE_FLASHING_AMBER
  };
  return values;
}

inline const char * const *EnumNamesGenericLightState() {
  static const char * const names[8] = {
    "GENERIC_LIGHT_STATE_UNKNOWN",
    "GENERIC_LIGHT_STATE_OTHER",
    "GENERIC_LIGHT_STATE_OFF",
    "GENERIC_LIGHT_STATE_ON",
    "GENERIC_LIGHT_STATE_FLASHING_BLUE",
    "GENERIC_LIGHT_STATE_FLASHING_BLUE_AND_RED",
    "GENERIC_LIGHT_STATE_FLASHING_AMBER",
    nullptr
  };
  return names;
}

inline const char *EnumNameGenericLightState(GenericLightState e) {
  if (::flatbuffers::IsOutRange(e, GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN, GenericLightState_GENERIC_LIGHT_STATE_FLASHING_AMBER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGenericLightState()[index];
}

enum BrakeLightState : int32_t {
  BrakeLightState_BRAKE_LIGHT_STATE_UNKNOWN = 0,
  BrakeLightState_BRAKE_LIGHT_STATE_OTHER = 1,
  BrakeLightState_BRAKE_LIGHT_STATE_OFF = 2,
  BrakeLightState_BRAKE_LIGHT_STATE_NORMAL = 3,
  BrakeLightState_BRAKE_LIGHT_STATE_STRONG = 4,
  BrakeLightState_MIN = BrakeLightState_BRAKE_LIGHT_STATE_UNKNOWN,
  BrakeLightState_MAX = BrakeLightState_BRAKE_LIGHT_STATE_STRONG
};

inline const BrakeLightState (&EnumValuesBrakeLightState())[5] {
  static const BrakeLightState values[] = {
    BrakeLightState_BRAKE_LIGHT_STATE_UNKNOWN,
    BrakeLightState_BRAKE_LIGHT_STATE_OTHER,
    BrakeLightState_BRAKE_LIGHT_STATE_OFF,
    BrakeLightState_BRAKE_LIGHT_STATE_NORMAL,
    BrakeLightState_BRAKE_LIGHT_STATE_STRONG
  };
  return values;
}

inline const char * const *EnumNamesBrakeLightState() {
  static const char * const names[6] = {
    "BRAKE_LIGHT_STATE_UNKNOWN",
    "BRAKE_LIGHT_STATE_OTHER",
    "BRAKE_LIGHT_STATE_OFF",
    "BRAKE_LIGHT_STATE_NORMAL",
    "BRAKE_LIGHT_STATE_STRONG",
    nullptr
  };
  return names;
}

inline const char *EnumNameBrakeLightState(BrakeLightState e) {
  if (::flatbuffers::IsOutRange(e, BrakeLightState_BRAKE_LIGHT_STATE_UNKNOWN, BrakeLightState_BRAKE_LIGHT_STATE_STRONG)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBrakeLightState()[index];
}

}  // namespace LightState_

enum Role : int32_t {
  Role_ROLE_UNKNOWN = 0,
  Role_ROLE_OTHER = 1,
  Role_ROLE_CIVIL = 2,
  Role_ROLE_AMBULANCE = 3,
  Role_ROLE_FIRE = 4,
  Role_ROLE_POLICE = 5,
  Role_ROLE_PUBLIC_TRANSPORT = 6,
  Role_ROLE_ROAD_ASSISTANCE = 7,
  Role_ROLE_GARBAGE_COLLECTION = 8,
  Role_ROLE_ROAD_CONSTRUCTION = 9,
  Role_ROLE_MILITARY = 10,
  Role_MIN = Role_ROLE_UNKNOWN,
  Role_MAX = Role_ROLE_MILITARY
};

inline const Role (&EnumValuesRole())[11] {
  static const Role values[] = {
    Role_ROLE_UNKNOWN,
    Role_ROLE_OTHER,
    Role_ROLE_CIVIL,
    Role_ROLE_AMBULANCE,
    Role_ROLE_FIRE,
    Role_ROLE_POLICE,
    Role_ROLE_PUBLIC_TRANSPORT,
    Role_ROLE_ROAD_ASSISTANCE,
    Role_ROLE_GARBAGE_COLLECTION,
    Role_ROLE_ROAD_CONSTRUCTION,
    Role_ROLE_MILITARY
  };
  return values;
}

inline const char * const *EnumNamesRole() {
  static const char * const names[12] = {
    "ROLE_UNKNOWN",
    "ROLE_OTHER",
    "ROLE_CIVIL",
    "ROLE_AMBULANCE",
    "ROLE_FIRE",
    "ROLE_POLICE",
    "ROLE_PUBLIC_TRANSPORT",
    "ROLE_ROAD_ASSISTANCE",
    "ROLE_GARBAGE_COLLECTION",
    "ROLE_ROAD_CONSTRUCTION",
    "ROLE_MILITARY",
    nullptr
  };
  return names;
}

inline const char *EnumNameRole(Role e) {
  if (::flatbuffers::IsOutRange(e, Role_ROLE_UNKNOWN, Role_ROLE_MILITARY)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRole()[index];
}

}  // namespace VehicleClassification_

namespace PedestrianAttributes_ {
namespace Bone_ {

enum Type : int32_t {
  Type_TYPE_ROOT = 0,
  Type_TYPE_HIP = 1,
  Type_TYPE_LOWER_SPINE = 2,
  Type_TYPE_UPPER_SPINE = 3,
  Type_TYPE_NECK = 4,
  Type_TYPE_HEAD = 5,
  Type_TYPE_SHOULDER_L = 6,
  Type_TYPE_SHOULDER_R = 7,
  Type_TYPE_UPPER_ARM_L = 8,
  Type_TYPE_UPPER_ARM_R = 9,
  Type_TYPE_LOWER_ARM_L = 10,
  Type_TYPE_LOWER_ARM_R = 11,
  Type_TYPE_FULL_HAND_L = 12,
  Type_TYPE_FULL_HAND_R = 13,
  Type_TYPE_UPPER_LEG_L = 14,
  Type_TYPE_UPPER_LEG_R = 15,
  Type_TYPE_LOWER_LEG_L = 16,
  Type_TYPE_LOWER_LEG_R = 17,
  Type_TYPE_FULL_FOOT_L = 18,
  Type_TYPE_FULL_FOOT_R = 19,
  Type_MIN = Type_TYPE_ROOT,
  Type_MAX = Type_TYPE_FULL_FOOT_R
};

inline const Type (&EnumValuesType())[20] {
  static const Type values[] = {
    Type_TYPE_ROOT,
    Type_TYPE_HIP,
    Type_TYPE_LOWER_SPINE,
    Type_TYPE_UPPER_SPINE,
    Type_TYPE_NECK,
    Type_TYPE_HEAD,
    Type_TYPE_SHOULDER_L,
    Type_TYPE_SHOULDER_R,
    Type_TYPE_UPPER_ARM_L,
    Type_TYPE_UPPER_ARM_R,
    Type_TYPE_LOWER_ARM_L,
    Type_TYPE_LOWER_ARM_R,
    Type_TYPE_FULL_HAND_L,
    Type_TYPE_FULL_HAND_R,
    Type_TYPE_UPPER_LEG_L,
    Type_TYPE_UPPER_LEG_R,
    Type_TYPE_LOWER_LEG_L,
    Type_TYPE_LOWER_LEG_R,
    Type_TYPE_FULL_FOOT_L,
    Type_TYPE_FULL_FOOT_R
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[21] = {
    "TYPE_ROOT",
    "TYPE_HIP",
    "TYPE_LOWER_SPINE",
    "TYPE_UPPER_SPINE",
    "TYPE_NECK",
    "TYPE_HEAD",
    "TYPE_SHOULDER_L",
    "TYPE_SHOULDER_R",
    "TYPE_UPPER_ARM_L",
    "TYPE_UPPER_ARM_R",
    "TYPE_LOWER_ARM_L",
    "TYPE_LOWER_ARM_R",
    "TYPE_FULL_HAND_L",
    "TYPE_FULL_HAND_R",
    "TYPE_UPPER_LEG_L",
    "TYPE_UPPER_LEG_R",
    "TYPE_LOWER_LEG_L",
    "TYPE_LOWER_LEG_R",
    "TYPE_FULL_FOOT_L",
    "TYPE_FULL_FOOT_R",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_ROOT, Type_TYPE_FULL_FOOT_R)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

}  // namespace Bone_
}  // namespace PedestrianAttributes_
}  // namespace MovingObject_

struct StationaryObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StationaryObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BASE = 6,
    VT_CLASSIFICATION = 8,
    VT_MODEL_REFERENCE = 10,
    VT_SOURCE_REFERENCE = 12,
    VT_COLOR_DESCRIPTION = 14
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::BaseStationary *base() const {
    return GetPointer<const osi3::BaseStationary *>(VT_BASE);
  }
  const osi3::StationaryObject_::Classification *classification() const {
    return GetPointer<const osi3::StationaryObject_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::ColorDescription *color_description() const {
    return GetPointer<const osi3::ColorDescription *>(VT_COLOR_DESCRIPTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_COLOR_DESCRIPTION) &&
           verifier.VerifyTable(color_description()) &&
           verifier.EndTable();
  }
};

struct StationaryObjectBuilder {
  typedef StationaryObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(StationaryObject::VT_ID, id);
  }
  void add_base(::flatbuffers::Offset<osi3::BaseStationary> base) {
    fbb_.AddOffset(StationaryObject::VT_BASE, base);
  }
  void add_classification(::flatbuffers::Offset<osi3::StationaryObject_::Classification> classification) {
    fbb_.AddOffset(StationaryObject::VT_CLASSIFICATION, classification);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(StationaryObject::VT_MODEL_REFERENCE, model_reference);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(StationaryObject::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_color_description(::flatbuffers::Offset<osi3::ColorDescription> color_description) {
    fbb_.AddOffset(StationaryObject::VT_COLOR_DESCRIPTION, color_description);
  }
  explicit StationaryObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StationaryObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StationaryObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StationaryObject> CreateStationaryObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::StationaryObject_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  StationaryObjectBuilder builder_(_fbb);
  builder_.add_color_description(color_description);
  builder_.add_source_reference(source_reference);
  builder_.add_model_reference(model_reference);
  builder_.add_classification(classification);
  builder_.add_base(base);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StationaryObject> CreateStationaryObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::StationaryObject_::Classification> classification = 0,
    const char *model_reference = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateStationaryObject(
      _fbb,
      id,
      base,
      classification,
      model_reference__,
      source_reference__,
      color_description);
}

namespace StationaryObject_ {

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_MATERIAL = 6,
    VT_DENSITY = 8,
    VT_COLOR = 10,
    VT_EMITTING_STRUCTURE_ATTRIBUTE = 12,
    VT_ASSIGNED_LANE_ID = 14,
    VT_ASSIGNED_LANE_PERCENTAGE = 16,
    VT_LOGICAL_LANE_ASSIGNMENT = 18
  };
  osi3::StationaryObject_::Classification_::Type type() const {
    return static_cast<osi3::StationaryObject_::Classification_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  osi3::StationaryObject_::Classification_::Material material() const {
    return static_cast<osi3::StationaryObject_::Classification_::Material>(GetField<int32_t>(VT_MATERIAL, 0));
  }
  osi3::StationaryObject_::Classification_::Density density() const {
    return static_cast<osi3::StationaryObject_::Classification_::Density>(GetField<int32_t>(VT_DENSITY, 0));
  }
  osi3::StationaryObject_::Classification_::Color color() const {
    return static_cast<osi3::StationaryObject_::Classification_::Color>(GetField<int32_t>(VT_COLOR, 0));
  }
  const osi3::StationaryObject_::Classification_::EmittingStructureAttribute *emitting_structure_attribute() const {
    return GetPointer<const osi3::StationaryObject_::Classification_::EmittingStructureAttribute *>(VT_EMITTING_STRUCTURE_ATTRIBUTE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_ASSIGNED_LANE_ID);
  }
  const ::flatbuffers::Vector<double> *assigned_lane_percentage() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_ASSIGNED_LANE_PERCENTAGE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *>(VT_LOGICAL_LANE_ASSIGNMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_MATERIAL, 4) &&
           VerifyField<int32_t>(verifier, VT_DENSITY, 4) &&
           VerifyField<int32_t>(verifier, VT_COLOR, 4) &&
           VerifyOffset(verifier, VT_EMITTING_STRUCTURE_ATTRIBUTE) &&
           verifier.VerifyTable(emitting_structure_attribute()) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyVector(assigned_lane_id()) &&
           verifier.VerifyVectorOfTables(assigned_lane_id()) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_PERCENTAGE) &&
           verifier.VerifyVector(assigned_lane_percentage()) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE_ASSIGNMENT) &&
           verifier.VerifyVector(logical_lane_assignment()) &&
           verifier.VerifyVectorOfTables(logical_lane_assignment()) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::StationaryObject_::Classification_::Type type) {
    fbb_.AddElement<int32_t>(Classification::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_material(osi3::StationaryObject_::Classification_::Material material) {
    fbb_.AddElement<int32_t>(Classification::VT_MATERIAL, static_cast<int32_t>(material), 0);
  }
  void add_density(osi3::StationaryObject_::Classification_::Density density) {
    fbb_.AddElement<int32_t>(Classification::VT_DENSITY, static_cast<int32_t>(density), 0);
  }
  void add_color(osi3::StationaryObject_::Classification_::Color color) {
    fbb_.AddElement<int32_t>(Classification::VT_COLOR, static_cast<int32_t>(color), 0);
  }
  void add_emitting_structure_attribute(::flatbuffers::Offset<osi3::StationaryObject_::Classification_::EmittingStructureAttribute> emitting_structure_attribute) {
    fbb_.AddOffset(Classification::VT_EMITTING_STRUCTURE_ATTRIBUTE, emitting_structure_attribute);
  }
  void add_assigned_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id) {
    fbb_.AddOffset(Classification::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_assigned_lane_percentage(::flatbuffers::Offset<::flatbuffers::Vector<double>> assigned_lane_percentage) {
    fbb_.AddOffset(Classification::VT_ASSIGNED_LANE_PERCENTAGE, assigned_lane_percentage);
  }
  void add_logical_lane_assignment(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment) {
    fbb_.AddOffset(Classification::VT_LOGICAL_LANE_ASSIGNMENT, logical_lane_assignment);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::StationaryObject_::Classification_::Type type = osi3::StationaryObject_::Classification_::Type_TYPE_UNKNOWN,
    osi3::StationaryObject_::Classification_::Material material = osi3::StationaryObject_::Classification_::Material_MATERIAL_UNKNOWN,
    osi3::StationaryObject_::Classification_::Density density = osi3::StationaryObject_::Classification_::Density_DENSITY_UNKNOWN,
    osi3::StationaryObject_::Classification_::Color color = osi3::StationaryObject_::Classification_::Color_COLOR_UNKNOWN,
    ::flatbuffers::Offset<osi3::StationaryObject_::Classification_::EmittingStructureAttribute> emitting_structure_attribute = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> assigned_lane_percentage = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment = 0) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_logical_lane_assignment(logical_lane_assignment);
  builder_.add_assigned_lane_percentage(assigned_lane_percentage);
  builder_.add_assigned_lane_id(assigned_lane_id);
  builder_.add_emitting_structure_attribute(emitting_structure_attribute);
  builder_.add_color(color);
  builder_.add_density(density);
  builder_.add_material(material);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Classification> CreateClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::StationaryObject_::Classification_::Type type = osi3::StationaryObject_::Classification_::Type_TYPE_UNKNOWN,
    osi3::StationaryObject_::Classification_::Material material = osi3::StationaryObject_::Classification_::Material_MATERIAL_UNKNOWN,
    osi3::StationaryObject_::Classification_::Density density = osi3::StationaryObject_::Classification_::Density_DENSITY_UNKNOWN,
    osi3::StationaryObject_::Classification_::Color color = osi3::StationaryObject_::Classification_::Color_COLOR_UNKNOWN,
    ::flatbuffers::Offset<osi3::StationaryObject_::Classification_::EmittingStructureAttribute> emitting_structure_attribute = 0,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id = nullptr,
    const std::vector<double> *assigned_lane_percentage = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment = nullptr) {
  auto assigned_lane_id__ = assigned_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*assigned_lane_id) : 0;
  auto assigned_lane_percentage__ = assigned_lane_percentage ? _fbb.CreateVector<double>(*assigned_lane_percentage) : 0;
  auto logical_lane_assignment__ = logical_lane_assignment ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>(*logical_lane_assignment) : 0;
  return osi3::StationaryObject_::CreateClassification(
      _fbb,
      type,
      material,
      density,
      color,
      emitting_structure_attribute,
      assigned_lane_id__,
      assigned_lane_percentage__,
      logical_lane_assignment__);
}

namespace Classification_ {

struct EmittingStructureAttribute FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EmittingStructureAttributeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WAVELENGTH_DATA = 4,
    VT_EMITTED_SPATIAL_SIGNAL_STRENGTH = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::WavelengthData>> *wavelength_data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::WavelengthData>> *>(VT_WAVELENGTH_DATA);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::SpatialSignalStrength>> *emitted_spatial_signal_strength() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::SpatialSignalStrength>> *>(VT_EMITTED_SPATIAL_SIGNAL_STRENGTH);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WAVELENGTH_DATA) &&
           verifier.VerifyVector(wavelength_data()) &&
           verifier.VerifyVectorOfTables(wavelength_data()) &&
           VerifyOffset(verifier, VT_EMITTED_SPATIAL_SIGNAL_STRENGTH) &&
           verifier.VerifyVector(emitted_spatial_signal_strength()) &&
           verifier.VerifyVectorOfTables(emitted_spatial_signal_strength()) &&
           verifier.EndTable();
  }
};

struct EmittingStructureAttributeBuilder {
  typedef EmittingStructureAttribute Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_wavelength_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::WavelengthData>>> wavelength_data) {
    fbb_.AddOffset(EmittingStructureAttribute::VT_WAVELENGTH_DATA, wavelength_data);
  }
  void add_emitted_spatial_signal_strength(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::SpatialSignalStrength>>> emitted_spatial_signal_strength) {
    fbb_.AddOffset(EmittingStructureAttribute::VT_EMITTED_SPATIAL_SIGNAL_STRENGTH, emitted_spatial_signal_strength);
  }
  explicit EmittingStructureAttributeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EmittingStructureAttribute> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EmittingStructureAttribute>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EmittingStructureAttribute> CreateEmittingStructureAttribute(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::WavelengthData>>> wavelength_data = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::SpatialSignalStrength>>> emitted_spatial_signal_strength = 0) {
  EmittingStructureAttributeBuilder builder_(_fbb);
  builder_.add_emitted_spatial_signal_strength(emitted_spatial_signal_strength);
  builder_.add_wavelength_data(wavelength_data);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EmittingStructureAttribute> CreateEmittingStructureAttributeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<osi3::WavelengthData>> *wavelength_data = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::SpatialSignalStrength>> *emitted_spatial_signal_strength = nullptr) {
  auto wavelength_data__ = wavelength_data ? _fbb.CreateVector<::flatbuffers::Offset<osi3::WavelengthData>>(*wavelength_data) : 0;
  auto emitted_spatial_signal_strength__ = emitted_spatial_signal_strength ? _fbb.CreateVector<::flatbuffers::Offset<osi3::SpatialSignalStrength>>(*emitted_spatial_signal_strength) : 0;
  return osi3::StationaryObject_::Classification_::CreateEmittingStructureAttribute(
      _fbb,
      wavelength_data__,
      emitted_spatial_signal_strength__);
}

}  // namespace Classification_
}  // namespace StationaryObject_

struct MovingObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MovingObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BASE = 6,
    VT_TYPE = 8,
    VT_ASSIGNED_LANE_ID = 10,
    VT_VEHICLE_ATTRIBUTES = 12,
    VT_VEHICLE_CLASSIFICATION = 14,
    VT_MODEL_REFERENCE = 16,
    VT_FUTURE_TRAJECTORY = 18,
    VT_MOVING_OBJECT_CLASSIFICATION = 20,
    VT_SOURCE_REFERENCE = 22,
    VT_COLOR_DESCRIPTION = 24,
    VT_PEDESTRIAN_ATTRIBUTES = 26
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::BaseMoving *base() const {
    return GetPointer<const osi3::BaseMoving *>(VT_BASE);
  }
  osi3::MovingObject_::Type type() const {
    return static_cast<osi3::MovingObject_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_ASSIGNED_LANE_ID);
  }
  const osi3::MovingObject_::VehicleAttributes *vehicle_attributes() const {
    return GetPointer<const osi3::MovingObject_::VehicleAttributes *>(VT_VEHICLE_ATTRIBUTES);
  }
  const osi3::MovingObject_::VehicleClassification *vehicle_classification() const {
    return GetPointer<const osi3::MovingObject_::VehicleClassification *>(VT_VEHICLE_CLASSIFICATION);
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::StatePoint>> *future_trajectory() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::StatePoint>> *>(VT_FUTURE_TRAJECTORY);
  }
  const osi3::MovingObject_::MovingObjectClassification *moving_object_classification() const {
    return GetPointer<const osi3::MovingObject_::MovingObjectClassification *>(VT_MOVING_OBJECT_CLASSIFICATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::ColorDescription *color_description() const {
    return GetPointer<const osi3::ColorDescription *>(VT_COLOR_DESCRIPTION);
  }
  const osi3::MovingObject_::PedestrianAttributes *pedestrian_attributes() const {
    return GetPointer<const osi3::MovingObject_::PedestrianAttributes *>(VT_PEDESTRIAN_ATTRIBUTES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyVector(assigned_lane_id()) &&
           verifier.VerifyVectorOfTables(assigned_lane_id()) &&
           VerifyOffset(verifier, VT_VEHICLE_ATTRIBUTES) &&
           verifier.VerifyTable(vehicle_attributes()) &&
           VerifyOffset(verifier, VT_VEHICLE_CLASSIFICATION) &&
           verifier.VerifyTable(vehicle_classification()) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           VerifyOffset(verifier, VT_FUTURE_TRAJECTORY) &&
           verifier.VerifyVector(future_trajectory()) &&
           verifier.VerifyVectorOfTables(future_trajectory()) &&
           VerifyOffset(verifier, VT_MOVING_OBJECT_CLASSIFICATION) &&
           verifier.VerifyTable(moving_object_classification()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_COLOR_DESCRIPTION) &&
           verifier.VerifyTable(color_description()) &&
           VerifyOffset(verifier, VT_PEDESTRIAN_ATTRIBUTES) &&
           verifier.VerifyTable(pedestrian_attributes()) &&
           verifier.EndTable();
  }
};

struct MovingObjectBuilder {
  typedef MovingObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(MovingObject::VT_ID, id);
  }
  void add_base(::flatbuffers::Offset<osi3::BaseMoving> base) {
    fbb_.AddOffset(MovingObject::VT_BASE, base);
  }
  void add_type(osi3::MovingObject_::Type type) {
    fbb_.AddElement<int32_t>(MovingObject::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_assigned_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id) {
    fbb_.AddOffset(MovingObject::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_vehicle_attributes(::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes> vehicle_attributes) {
    fbb_.AddOffset(MovingObject::VT_VEHICLE_ATTRIBUTES, vehicle_attributes);
  }
  void add_vehicle_classification(::flatbuffers::Offset<osi3::MovingObject_::VehicleClassification> vehicle_classification) {
    fbb_.AddOffset(MovingObject::VT_VEHICLE_CLASSIFICATION, vehicle_classification);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(MovingObject::VT_MODEL_REFERENCE, model_reference);
  }
  void add_future_trajectory(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::StatePoint>>> future_trajectory) {
    fbb_.AddOffset(MovingObject::VT_FUTURE_TRAJECTORY, future_trajectory);
  }
  void add_moving_object_classification(::flatbuffers::Offset<osi3::MovingObject_::MovingObjectClassification> moving_object_classification) {
    fbb_.AddOffset(MovingObject::VT_MOVING_OBJECT_CLASSIFICATION, moving_object_classification);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(MovingObject::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_color_description(::flatbuffers::Offset<osi3::ColorDescription> color_description) {
    fbb_.AddOffset(MovingObject::VT_COLOR_DESCRIPTION, color_description);
  }
  void add_pedestrian_attributes(::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes> pedestrian_attributes) {
    fbb_.AddOffset(MovingObject::VT_PEDESTRIAN_ATTRIBUTES, pedestrian_attributes);
  }
  explicit MovingObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MovingObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MovingObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MovingObject> CreateMovingObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseMoving> base = 0,
    osi3::MovingObject_::Type type = osi3::MovingObject_::Type_TYPE_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes> vehicle_attributes = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::VehicleClassification> vehicle_classification = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::StatePoint>>> future_trajectory = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::MovingObjectClassification> moving_object_classification = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes> pedestrian_attributes = 0) {
  MovingObjectBuilder builder_(_fbb);
  builder_.add_pedestrian_attributes(pedestrian_attributes);
  builder_.add_color_description(color_description);
  builder_.add_source_reference(source_reference);
  builder_.add_moving_object_classification(moving_object_classification);
  builder_.add_future_trajectory(future_trajectory);
  builder_.add_model_reference(model_reference);
  builder_.add_vehicle_classification(vehicle_classification);
  builder_.add_vehicle_attributes(vehicle_attributes);
  builder_.add_assigned_lane_id(assigned_lane_id);
  builder_.add_type(type);
  builder_.add_base(base);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MovingObject> CreateMovingObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseMoving> base = 0,
    osi3::MovingObject_::Type type = osi3::MovingObject_::Type_TYPE_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id = nullptr,
    ::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes> vehicle_attributes = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::VehicleClassification> vehicle_classification = 0,
    const char *model_reference = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::StatePoint>> *future_trajectory = nullptr,
    ::flatbuffers::Offset<osi3::MovingObject_::MovingObjectClassification> moving_object_classification = 0,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0,
    ::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes> pedestrian_attributes = 0) {
  auto assigned_lane_id__ = assigned_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*assigned_lane_id) : 0;
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  auto future_trajectory__ = future_trajectory ? _fbb.CreateVector<::flatbuffers::Offset<osi3::StatePoint>>(*future_trajectory) : 0;
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateMovingObject(
      _fbb,
      id,
      base,
      type,
      assigned_lane_id__,
      vehicle_attributes,
      vehicle_classification,
      model_reference__,
      future_trajectory__,
      moving_object_classification,
      source_reference__,
      color_description,
      pedestrian_attributes);
}

namespace MovingObject_ {

struct VehicleAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VehicleAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DRIVER_ID = 4,
    VT_RADIUS_WHEEL = 6,
    VT_NUMBER_WHEELS = 8,
    VT_BBCENTER_TO_REAR = 10,
    VT_BBCENTER_TO_FRONT = 12,
    VT_GROUND_CLEARANCE = 14,
    VT_WHEEL_DATA = 16,
    VT_STEERING_WHEEL_ANGLE = 18
  };
  const osi3::Identifier *driver_id() const {
    return GetPointer<const osi3::Identifier *>(VT_DRIVER_ID);
  }
  double radius_wheel() const {
    return GetField<double>(VT_RADIUS_WHEEL, 0.0);
  }
  uint32_t number_wheels() const {
    return GetField<uint32_t>(VT_NUMBER_WHEELS, 0);
  }
  const osi3::Vector3d *bbcenter_to_rear() const {
    return GetPointer<const osi3::Vector3d *>(VT_BBCENTER_TO_REAR);
  }
  const osi3::Vector3d *bbcenter_to_front() const {
    return GetPointer<const osi3::Vector3d *>(VT_BBCENTER_TO_FRONT);
  }
  double ground_clearance() const {
    return GetField<double>(VT_GROUND_CLEARANCE, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>> *wheel_data() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>> *>(VT_WHEEL_DATA);
  }
  double steering_wheel_angle() const {
    return GetField<double>(VT_STEERING_WHEEL_ANGLE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DRIVER_ID) &&
           verifier.VerifyTable(driver_id()) &&
           VerifyField<double>(verifier, VT_RADIUS_WHEEL, 8) &&
           VerifyField<uint32_t>(verifier, VT_NUMBER_WHEELS, 4) &&
           VerifyOffset(verifier, VT_BBCENTER_TO_REAR) &&
           verifier.VerifyTable(bbcenter_to_rear()) &&
           VerifyOffset(verifier, VT_BBCENTER_TO_FRONT) &&
           verifier.VerifyTable(bbcenter_to_front()) &&
           VerifyField<double>(verifier, VT_GROUND_CLEARANCE, 8) &&
           VerifyOffset(verifier, VT_WHEEL_DATA) &&
           verifier.VerifyVector(wheel_data()) &&
           verifier.VerifyVectorOfTables(wheel_data()) &&
           VerifyField<double>(verifier, VT_STEERING_WHEEL_ANGLE, 8) &&
           verifier.EndTable();
  }
};

struct VehicleAttributesBuilder {
  typedef VehicleAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_driver_id(::flatbuffers::Offset<osi3::Identifier> driver_id) {
    fbb_.AddOffset(VehicleAttributes::VT_DRIVER_ID, driver_id);
  }
  void add_radius_wheel(double radius_wheel) {
    fbb_.AddElement<double>(VehicleAttributes::VT_RADIUS_WHEEL, radius_wheel, 0.0);
  }
  void add_number_wheels(uint32_t number_wheels) {
    fbb_.AddElement<uint32_t>(VehicleAttributes::VT_NUMBER_WHEELS, number_wheels, 0);
  }
  void add_bbcenter_to_rear(::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_rear) {
    fbb_.AddOffset(VehicleAttributes::VT_BBCENTER_TO_REAR, bbcenter_to_rear);
  }
  void add_bbcenter_to_front(::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_front) {
    fbb_.AddOffset(VehicleAttributes::VT_BBCENTER_TO_FRONT, bbcenter_to_front);
  }
  void add_ground_clearance(double ground_clearance) {
    fbb_.AddElement<double>(VehicleAttributes::VT_GROUND_CLEARANCE, ground_clearance, 0.0);
  }
  void add_wheel_data(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>>> wheel_data) {
    fbb_.AddOffset(VehicleAttributes::VT_WHEEL_DATA, wheel_data);
  }
  void add_steering_wheel_angle(double steering_wheel_angle) {
    fbb_.AddElement<double>(VehicleAttributes::VT_STEERING_WHEEL_ANGLE, steering_wheel_angle, 0.0);
  }
  explicit VehicleAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VehicleAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VehicleAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VehicleAttributes> CreateVehicleAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> driver_id = 0,
    double radius_wheel = 0.0,
    uint32_t number_wheels = 0,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_rear = 0,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_front = 0,
    double ground_clearance = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>>> wheel_data = 0,
    double steering_wheel_angle = 0.0) {
  VehicleAttributesBuilder builder_(_fbb);
  builder_.add_steering_wheel_angle(steering_wheel_angle);
  builder_.add_ground_clearance(ground_clearance);
  builder_.add_radius_wheel(radius_wheel);
  builder_.add_wheel_data(wheel_data);
  builder_.add_bbcenter_to_front(bbcenter_to_front);
  builder_.add_bbcenter_to_rear(bbcenter_to_rear);
  builder_.add_number_wheels(number_wheels);
  builder_.add_driver_id(driver_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VehicleAttributes> CreateVehicleAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> driver_id = 0,
    double radius_wheel = 0.0,
    uint32_t number_wheels = 0,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_rear = 0,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_front = 0,
    double ground_clearance = 0.0,
    const std::vector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>> *wheel_data = nullptr,
    double steering_wheel_angle = 0.0) {
  auto wheel_data__ = wheel_data ? _fbb.CreateVector<::flatbuffers::Offset<osi3::MovingObject_::VehicleAttributes_::WheelData>>(*wheel_data) : 0;
  return osi3::MovingObject_::CreateVehicleAttributes(
      _fbb,
      driver_id,
      radius_wheel,
      number_wheels,
      bbcenter_to_rear,
      bbcenter_to_front,
      ground_clearance,
      wheel_data__,
      steering_wheel_angle);
}

namespace VehicleAttributes_ {

struct WheelData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WheelDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AXLE = 4,
    VT_INDEX = 6,
    VT_POSITION = 8,
    VT_WHEEL_RADIUS = 10,
    VT_RIM_RADIUS = 12,
    VT_WIDTH = 14,
    VT_ORIENTATION = 16,
    VT_ROTATION_RATE = 18,
    VT_MODEL_REFERENCE = 20,
    VT_FRICTION_COEFFICIENT = 22
  };
  uint32_t axle() const {
    return GetField<uint32_t>(VT_AXLE, 0);
  }
  uint32_t index() const {
    return GetField<uint32_t>(VT_INDEX, 0);
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  double wheel_radius() const {
    return GetField<double>(VT_WHEEL_RADIUS, 0.0);
  }
  double rim_radius() const {
    return GetField<double>(VT_RIM_RADIUS, 0.0);
  }
  double width() const {
    return GetField<double>(VT_WIDTH, 0.0);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  double rotation_rate() const {
    return GetField<double>(VT_ROTATION_RATE, 0.0);
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  double friction_coefficient() const {
    return GetField<double>(VT_FRICTION_COEFFICIENT, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_AXLE, 4) &&
           VerifyField<uint32_t>(verifier, VT_INDEX, 4) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<double>(verifier, VT_WHEEL_RADIUS, 8) &&
           VerifyField<double>(verifier, VT_RIM_RADIUS, 8) &&
           VerifyField<double>(verifier, VT_WIDTH, 8) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyField<double>(verifier, VT_ROTATION_RATE, 8) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           VerifyField<double>(verifier, VT_FRICTION_COEFFICIENT, 8) &&
           verifier.EndTable();
  }
};

struct WheelDataBuilder {
  typedef WheelData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_axle(uint32_t axle) {
    fbb_.AddElement<uint32_t>(WheelData::VT_AXLE, axle, 0);
  }
  void add_index(uint32_t index) {
    fbb_.AddElement<uint32_t>(WheelData::VT_INDEX, index, 0);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(WheelData::VT_POSITION, position);
  }
  void add_wheel_radius(double wheel_radius) {
    fbb_.AddElement<double>(WheelData::VT_WHEEL_RADIUS, wheel_radius, 0.0);
  }
  void add_rim_radius(double rim_radius) {
    fbb_.AddElement<double>(WheelData::VT_RIM_RADIUS, rim_radius, 0.0);
  }
  void add_width(double width) {
    fbb_.AddElement<double>(WheelData::VT_WIDTH, width, 0.0);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(WheelData::VT_ORIENTATION, orientation);
  }
  void add_rotation_rate(double rotation_rate) {
    fbb_.AddElement<double>(WheelData::VT_ROTATION_RATE, rotation_rate, 0.0);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(WheelData::VT_MODEL_REFERENCE, model_reference);
  }
  void add_friction_coefficient(double friction_coefficient) {
    fbb_.AddElement<double>(WheelData::VT_FRICTION_COEFFICIENT, friction_coefficient, 0.0);
  }
  explicit WheelDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WheelData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WheelData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WheelData> CreateWheelData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t axle = 0,
    uint32_t index = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    double wheel_radius = 0.0,
    double rim_radius = 0.0,
    double width = 0.0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    double rotation_rate = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0,
    double friction_coefficient = 0.0) {
  WheelDataBuilder builder_(_fbb);
  builder_.add_friction_coefficient(friction_coefficient);
  builder_.add_rotation_rate(rotation_rate);
  builder_.add_width(width);
  builder_.add_rim_radius(rim_radius);
  builder_.add_wheel_radius(wheel_radius);
  builder_.add_model_reference(model_reference);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_index(index);
  builder_.add_axle(axle);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WheelData> CreateWheelDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t axle = 0,
    uint32_t index = 0,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    double wheel_radius = 0.0,
    double rim_radius = 0.0,
    double width = 0.0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    double rotation_rate = 0.0,
    const char *model_reference = nullptr,
    double friction_coefficient = 0.0) {
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  return osi3::MovingObject_::VehicleAttributes_::CreateWheelData(
      _fbb,
      axle,
      index,
      position,
      wheel_radius,
      rim_radius,
      width,
      orientation,
      rotation_rate,
      model_reference__,
      friction_coefficient);
}

}  // namespace VehicleAttributes_

struct MovingObjectClassification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MovingObjectClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ASSIGNED_LANE_ID = 4,
    VT_ASSIGNED_LANE_PERCENTAGE = 6,
    VT_LOGICAL_LANE_ASSIGNMENT = 8
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_ASSIGNED_LANE_ID);
  }
  const ::flatbuffers::Vector<double> *assigned_lane_percentage() const {
    return GetPointer<const ::flatbuffers::Vector<double> *>(VT_ASSIGNED_LANE_PERCENTAGE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *>(VT_LOGICAL_LANE_ASSIGNMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyVector(assigned_lane_id()) &&
           verifier.VerifyVectorOfTables(assigned_lane_id()) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_PERCENTAGE) &&
           verifier.VerifyVector(assigned_lane_percentage()) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE_ASSIGNMENT) &&
           verifier.VerifyVector(logical_lane_assignment()) &&
           verifier.VerifyVectorOfTables(logical_lane_assignment()) &&
           verifier.EndTable();
  }
};

struct MovingObjectClassificationBuilder {
  typedef MovingObjectClassification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_assigned_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id) {
    fbb_.AddOffset(MovingObjectClassification::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_assigned_lane_percentage(::flatbuffers::Offset<::flatbuffers::Vector<double>> assigned_lane_percentage) {
    fbb_.AddOffset(MovingObjectClassification::VT_ASSIGNED_LANE_PERCENTAGE, assigned_lane_percentage);
  }
  void add_logical_lane_assignment(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment) {
    fbb_.AddOffset(MovingObjectClassification::VT_LOGICAL_LANE_ASSIGNMENT, logical_lane_assignment);
  }
  explicit MovingObjectClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MovingObjectClassification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MovingObjectClassification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MovingObjectClassification> CreateMovingObjectClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<double>> assigned_lane_percentage = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment = 0) {
  MovingObjectClassificationBuilder builder_(_fbb);
  builder_.add_logical_lane_assignment(logical_lane_assignment);
  builder_.add_assigned_lane_percentage(assigned_lane_percentage);
  builder_.add_assigned_lane_id(assigned_lane_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MovingObjectClassification> CreateMovingObjectClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id = nullptr,
    const std::vector<double> *assigned_lane_percentage = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment = nullptr) {
  auto assigned_lane_id__ = assigned_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*assigned_lane_id) : 0;
  auto assigned_lane_percentage__ = assigned_lane_percentage ? _fbb.CreateVector<double>(*assigned_lane_percentage) : 0;
  auto logical_lane_assignment__ = logical_lane_assignment ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>(*logical_lane_assignment) : 0;
  return osi3::MovingObject_::CreateMovingObjectClassification(
      _fbb,
      assigned_lane_id__,
      assigned_lane_percentage__,
      logical_lane_assignment__);
}

struct VehicleClassification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VehicleClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_LIGHT_STATE = 6,
    VT_HAS_TRAILER = 8,
    VT_TRAILER_ID = 10,
    VT_ROLE = 12
  };
  osi3::MovingObject_::VehicleClassification_::Type type() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  const osi3::MovingObject_::VehicleClassification_::LightState *light_state() const {
    return GetPointer<const osi3::MovingObject_::VehicleClassification_::LightState *>(VT_LIGHT_STATE);
  }
  bool has_trailer() const {
    return GetField<uint8_t>(VT_HAS_TRAILER, 0) != 0;
  }
  const osi3::Identifier *trailer_id() const {
    return GetPointer<const osi3::Identifier *>(VT_TRAILER_ID);
  }
  osi3::MovingObject_::VehicleClassification_::Role role() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::Role>(GetField<int32_t>(VT_ROLE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_LIGHT_STATE) &&
           verifier.VerifyTable(light_state()) &&
           VerifyField<uint8_t>(verifier, VT_HAS_TRAILER, 1) &&
           VerifyOffset(verifier, VT_TRAILER_ID) &&
           verifier.VerifyTable(trailer_id()) &&
           VerifyField<int32_t>(verifier, VT_ROLE, 4) &&
           verifier.EndTable();
  }
};

struct VehicleClassificationBuilder {
  typedef VehicleClassification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::MovingObject_::VehicleClassification_::Type type) {
    fbb_.AddElement<int32_t>(VehicleClassification::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_light_state(::flatbuffers::Offset<osi3::MovingObject_::VehicleClassification_::LightState> light_state) {
    fbb_.AddOffset(VehicleClassification::VT_LIGHT_STATE, light_state);
  }
  void add_has_trailer(bool has_trailer) {
    fbb_.AddElement<uint8_t>(VehicleClassification::VT_HAS_TRAILER, static_cast<uint8_t>(has_trailer), 0);
  }
  void add_trailer_id(::flatbuffers::Offset<osi3::Identifier> trailer_id) {
    fbb_.AddOffset(VehicleClassification::VT_TRAILER_ID, trailer_id);
  }
  void add_role(osi3::MovingObject_::VehicleClassification_::Role role) {
    fbb_.AddElement<int32_t>(VehicleClassification::VT_ROLE, static_cast<int32_t>(role), 0);
  }
  explicit VehicleClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VehicleClassification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VehicleClassification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VehicleClassification> CreateVehicleClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::MovingObject_::VehicleClassification_::Type type = osi3::MovingObject_::VehicleClassification_::Type_TYPE_UNKNOWN,
    ::flatbuffers::Offset<osi3::MovingObject_::VehicleClassification_::LightState> light_state = 0,
    bool has_trailer = false,
    ::flatbuffers::Offset<osi3::Identifier> trailer_id = 0,
    osi3::MovingObject_::VehicleClassification_::Role role = osi3::MovingObject_::VehicleClassification_::Role_ROLE_UNKNOWN) {
  VehicleClassificationBuilder builder_(_fbb);
  builder_.add_role(role);
  builder_.add_trailer_id(trailer_id);
  builder_.add_light_state(light_state);
  builder_.add_type(type);
  builder_.add_has_trailer(has_trailer);
  return builder_.Finish();
}

namespace VehicleClassification_ {

struct LightState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LightStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INDICATOR_STATE = 4,
    VT_FRONT_FOG_LIGHT = 6,
    VT_REAR_FOG_LIGHT = 8,
    VT_HEAD_LIGHT = 10,
    VT_HIGH_BEAM = 12,
    VT_REVERSING_LIGHT = 14,
    VT_TAIL_LIGHT = 16,
    VT_BRAKE_LIGHT_STATE = 18,
    VT_LICENSE_PLATE_ILLUMINATION_REAR = 20,
    VT_EMERGENCY_VEHICLE_ILLUMINATION = 22,
    VT_SERVICE_VEHICLE_ILLUMINATION = 24
  };
  osi3::MovingObject_::VehicleClassification_::LightState_::IndicatorState indicator_state() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::IndicatorState>(GetField<int32_t>(VT_INDICATOR_STATE, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState front_fog_light() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_FRONT_FOG_LIGHT, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState rear_fog_light() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_REAR_FOG_LIGHT, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState head_light() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_HEAD_LIGHT, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState high_beam() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_HIGH_BEAM, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState reversing_light() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_REVERSING_LIGHT, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState tail_light() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_TAIL_LIGHT, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::BrakeLightState brake_light_state() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::BrakeLightState>(GetField<int32_t>(VT_BRAKE_LIGHT_STATE, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState license_plate_illumination_rear() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_LICENSE_PLATE_ILLUMINATION_REAR, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState emergency_vehicle_illumination() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_EMERGENCY_VEHICLE_ILLUMINATION, 0));
  }
  osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState service_vehicle_illumination() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState>(GetField<int32_t>(VT_SERVICE_VEHICLE_ILLUMINATION, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_INDICATOR_STATE, 4) &&
           VerifyField<int32_t>(verifier, VT_FRONT_FOG_LIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_REAR_FOG_LIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_HEAD_LIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_HIGH_BEAM, 4) &&
           VerifyField<int32_t>(verifier, VT_REVERSING_LIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_TAIL_LIGHT, 4) &&
           VerifyField<int32_t>(verifier, VT_BRAKE_LIGHT_STATE, 4) &&
           VerifyField<int32_t>(verifier, VT_LICENSE_PLATE_ILLUMINATION_REAR, 4) &&
           VerifyField<int32_t>(verifier, VT_EMERGENCY_VEHICLE_ILLUMINATION, 4) &&
           VerifyField<int32_t>(verifier, VT_SERVICE_VEHICLE_ILLUMINATION, 4) &&
           verifier.EndTable();
  }
};

struct LightStateBuilder {
  typedef LightState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_indicator_state(osi3::MovingObject_::VehicleClassification_::LightState_::IndicatorState indicator_state) {
    fbb_.AddElement<int32_t>(LightState::VT_INDICATOR_STATE, static_cast<int32_t>(indicator_state), 0);
  }
  void add_front_fog_light(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState front_fog_light) {
    fbb_.AddElement<int32_t>(LightState::VT_FRONT_FOG_LIGHT, static_cast<int32_t>(front_fog_light), 0);
  }
  void add_rear_fog_light(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState rear_fog_light) {
    fbb_.AddElement<int32_t>(LightState::VT_REAR_FOG_LIGHT, static_cast<int32_t>(rear_fog_light), 0);
  }
  void add_head_light(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState head_light) {
    fbb_.AddElement<int32_t>(LightState::VT_HEAD_LIGHT, static_cast<int32_t>(head_light), 0);
  }
  void add_high_beam(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState high_beam) {
    fbb_.AddElement<int32_t>(LightState::VT_HIGH_BEAM, static_cast<int32_t>(high_beam), 0);
  }
  void add_reversing_light(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState reversing_light) {
    fbb_.AddElement<int32_t>(LightState::VT_REVERSING_LIGHT, static_cast<int32_t>(reversing_light), 0);
  }
  void add_tail_light(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState tail_light) {
    fbb_.AddElement<int32_t>(LightState::VT_TAIL_LIGHT, static_cast<int32_t>(tail_light), 0);
  }
  void add_brake_light_state(osi3::MovingObject_::VehicleClassification_::LightState_::BrakeLightState brake_light_state) {
    fbb_.AddElement<int32_t>(LightState::VT_BRAKE_LIGHT_STATE, static_cast<int32_t>(brake_light_state), 0);
  }
  void add_license_plate_illumination_rear(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState license_plate_illumination_rear) {
    fbb_.AddElement<int32_t>(LightState::VT_LICENSE_PLATE_ILLUMINATION_REAR, static_cast<int32_t>(license_plate_illumination_rear), 0);
  }
  void add_emergency_vehicle_illumination(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState emergency_vehicle_illumination) {
    fbb_.AddElement<int32_t>(LightState::VT_EMERGENCY_VEHICLE_ILLUMINATION, static_cast<int32_t>(emergency_vehicle_illumination), 0);
  }
  void add_service_vehicle_illumination(osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState service_vehicle_illumination) {
    fbb_.AddElement<int32_t>(LightState::VT_SERVICE_VEHICLE_ILLUMINATION, static_cast<int32_t>(service_vehicle_illumination), 0);
  }
  explicit LightStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LightState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LightState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LightState> CreateLightState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::MovingObject_::VehicleClassification_::LightState_::IndicatorState indicator_state = osi3::MovingObject_::VehicleClassification_::LightState_::IndicatorState_INDICATOR_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState front_fog_light = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState rear_fog_light = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState head_light = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState high_beam = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState reversing_light = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState tail_light = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::BrakeLightState brake_light_state = osi3::MovingObject_::VehicleClassification_::LightState_::BrakeLightState_BRAKE_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState license_plate_illumination_rear = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState emergency_vehicle_illumination = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState service_vehicle_illumination = osi3::MovingObject_::VehicleClassification_::LightState_::GenericLightState_GENERIC_LIGHT_STATE_UNKNOWN) {
  LightStateBuilder builder_(_fbb);
  builder_.add_service_vehicle_illumination(service_vehicle_illumination);
  builder_.add_emergency_vehicle_illumination(emergency_vehicle_illumination);
  builder_.add_license_plate_illumination_rear(license_plate_illumination_rear);
  builder_.add_brake_light_state(brake_light_state);
  builder_.add_tail_light(tail_light);
  builder_.add_reversing_light(reversing_light);
  builder_.add_high_beam(high_beam);
  builder_.add_head_light(head_light);
  builder_.add_rear_fog_light(rear_fog_light);
  builder_.add_front_fog_light(front_fog_light);
  builder_.add_indicator_state(indicator_state);
  return builder_.Finish();
}

}  // namespace VehicleClassification_

struct PedestrianAttributes FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PedestrianAttributesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BBCENTER_TO_ROOT = 4,
    VT_SKELETON_BONE = 6
  };
  const osi3::Vector3d *bbcenter_to_root() const {
    return GetPointer<const osi3::Vector3d *>(VT_BBCENTER_TO_ROOT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>> *skeleton_bone() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>> *>(VT_SKELETON_BONE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BBCENTER_TO_ROOT) &&
           verifier.VerifyTable(bbcenter_to_root()) &&
           VerifyOffset(verifier, VT_SKELETON_BONE) &&
           verifier.VerifyVector(skeleton_bone()) &&
           verifier.VerifyVectorOfTables(skeleton_bone()) &&
           verifier.EndTable();
  }
};

struct PedestrianAttributesBuilder {
  typedef PedestrianAttributes Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bbcenter_to_root(::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_root) {
    fbb_.AddOffset(PedestrianAttributes::VT_BBCENTER_TO_ROOT, bbcenter_to_root);
  }
  void add_skeleton_bone(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>>> skeleton_bone) {
    fbb_.AddOffset(PedestrianAttributes::VT_SKELETON_BONE, skeleton_bone);
  }
  explicit PedestrianAttributesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PedestrianAttributes> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PedestrianAttributes>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PedestrianAttributes> CreatePedestrianAttributes(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_root = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>>> skeleton_bone = 0) {
  PedestrianAttributesBuilder builder_(_fbb);
  builder_.add_skeleton_bone(skeleton_bone);
  builder_.add_bbcenter_to_root(bbcenter_to_root);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PedestrianAttributes> CreatePedestrianAttributesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> bbcenter_to_root = 0,
    const std::vector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>> *skeleton_bone = nullptr) {
  auto skeleton_bone__ = skeleton_bone ? _fbb.CreateVector<::flatbuffers::Offset<osi3::MovingObject_::PedestrianAttributes_::Bone>>(*skeleton_bone) : 0;
  return osi3::MovingObject_::CreatePedestrianAttributes(
      _fbb,
      bbcenter_to_root,
      skeleton_bone__);
}

namespace PedestrianAttributes_ {

struct Bone FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_POSITION = 6,
    VT_ORIENTATION = 8,
    VT_LENGTH = 10,
    VT_MISSING = 12,
    VT_VELOCITY = 14,
    VT_ORIENTATION_RATE = 16
  };
  osi3::MovingObject_::PedestrianAttributes_::Bone_::Type type() const {
    return static_cast<osi3::MovingObject_::PedestrianAttributes_::Bone_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  const osi3::Orientation3d *orientation() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION);
  }
  float length() const {
    return GetField<float>(VT_LENGTH, 0.0f);
  }
  bool missing() const {
    return GetField<uint8_t>(VT_MISSING, 0) != 0;
  }
  const osi3::Vector3d *velocity() const {
    return GetPointer<const osi3::Vector3d *>(VT_VELOCITY);
  }
  const osi3::Orientation3d *orientation_rate() const {
    return GetPointer<const osi3::Orientation3d *>(VT_ORIENTATION_RATE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyOffset(verifier, VT_ORIENTATION) &&
           verifier.VerifyTable(orientation()) &&
           VerifyField<float>(verifier, VT_LENGTH, 4) &&
           VerifyField<uint8_t>(verifier, VT_MISSING, 1) &&
           VerifyOffset(verifier, VT_VELOCITY) &&
           verifier.VerifyTable(velocity()) &&
           VerifyOffset(verifier, VT_ORIENTATION_RATE) &&
           verifier.VerifyTable(orientation_rate()) &&
           verifier.EndTable();
  }
};

struct BoneBuilder {
  typedef Bone Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::MovingObject_::PedestrianAttributes_::Bone_::Type type) {
    fbb_.AddElement<int32_t>(Bone::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(Bone::VT_POSITION, position);
  }
  void add_orientation(::flatbuffers::Offset<osi3::Orientation3d> orientation) {
    fbb_.AddOffset(Bone::VT_ORIENTATION, orientation);
  }
  void add_length(float length) {
    fbb_.AddElement<float>(Bone::VT_LENGTH, length, 0.0f);
  }
  void add_missing(bool missing) {
    fbb_.AddElement<uint8_t>(Bone::VT_MISSING, static_cast<uint8_t>(missing), 0);
  }
  void add_velocity(::flatbuffers::Offset<osi3::Vector3d> velocity) {
    fbb_.AddOffset(Bone::VT_VELOCITY, velocity);
  }
  void add_orientation_rate(::flatbuffers::Offset<osi3::Orientation3d> orientation_rate) {
    fbb_.AddOffset(Bone::VT_ORIENTATION_RATE, orientation_rate);
  }
  explicit BoneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Bone> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Bone>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Bone> CreateBone(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::MovingObject_::PedestrianAttributes_::Bone_::Type type = osi3::MovingObject_::PedestrianAttributes_::Bone_::Type_TYPE_ROOT,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation = 0,
    float length = 0.0f,
    bool missing = false,
    ::flatbuffers::Offset<osi3::Vector3d> velocity = 0,
    ::flatbuffers::Offset<osi3::Orientation3d> orientation_rate = 0) {
  BoneBuilder builder_(_fbb);
  builder_.add_orientation_rate(orientation_rate);
  builder_.add_velocity(velocity);
  builder_.add_length(length);
  builder_.add_orientation(orientation);
  builder_.add_position(position);
  builder_.add_type(type);
  builder_.add_missing(missing);
  return builder_.Finish();
}

}  // namespace PedestrianAttributes_
}  // namespace MovingObject_

namespace StationaryObject_ {

namespace Classification_ {

}  // namespace Classification_
}  // namespace StationaryObject_

namespace MovingObject_ {

namespace VehicleAttributes_ {

}  // namespace VehicleAttributes_

namespace VehicleClassification_ {

}  // namespace VehicleClassification_

namespace PedestrianAttributes_ {

}  // namespace PedestrianAttributes_
}  // namespace MovingObject_
}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIOBJECT_OSI3_MOVINGOBJECT__PEDESTRIANATTRIBUTES__H_
