// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSITRAFFICLIGHT_OSI3_H_
#define FLATBUFFERS_GENERATED_OSITRAFFICLIGHT_OSI3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {
namespace TrafficLight_ {

struct Classification;
struct ClassificationBuilder;

}  // namespace TrafficLight_

struct TrafficLight;
struct TrafficLightBuilder;

namespace TrafficLight_ {
namespace Classification_ {

enum Color : int32_t {
  Color_COLOR_UNKNOWN = 0,
  Color_COLOR_OTHER = 1,
  Color_COLOR_RED = 2,
  Color_COLOR_YELLOW = 3,
  Color_COLOR_GREEN = 4,
  Color_COLOR_BLUE = 5,
  Color_COLOR_WHITE = 6,
  Color_MIN = Color_COLOR_UNKNOWN,
  Color_MAX = Color_COLOR_WHITE
};

inline const Color (&EnumValuesColor())[7] {
  static const Color values[] = {
    Color_COLOR_UNKNOWN,
    Color_COLOR_OTHER,
    Color_COLOR_RED,
    Color_COLOR_YELLOW,
    Color_COLOR_GREEN,
    Color_COLOR_BLUE,
    Color_COLOR_WHITE
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[8] = {
    "COLOR_UNKNOWN",
    "COLOR_OTHER",
    "COLOR_RED",
    "COLOR_YELLOW",
    "COLOR_GREEN",
    "COLOR_BLUE",
    "COLOR_WHITE",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (::flatbuffers::IsOutRange(e, Color_COLOR_UNKNOWN, Color_COLOR_WHITE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

enum Icon : int32_t {
  Icon_ICON_UNKNOWN = 0,
  Icon_ICON_OTHER = 1,
  Icon_ICON_NONE = 2,
  Icon_ICON_ARROW_STRAIGHT_AHEAD = 3,
  Icon_ICON_ARROW_LEFT = 4,
  Icon_ICON_ARROW_DIAG_LEFT = 5,
  Icon_ICON_ARROW_STRAIGHT_AHEAD_LEFT = 6,
  Icon_ICON_ARROW_RIGHT = 7,
  Icon_ICON_ARROW_DIAG_RIGHT = 8,
  Icon_ICON_ARROW_STRAIGHT_AHEAD_RIGHT = 9,
  Icon_ICON_ARROW_LEFT_RIGHT = 10,
  Icon_ICON_ARROW_DOWN = 11,
  Icon_ICON_ARROW_DOWN_LEFT = 12,
  Icon_ICON_ARROW_DOWN_RIGHT = 13,
  Icon_ICON_ARROW_CROSS = 14,
  Icon_ICON_PEDESTRIAN = 15,
  Icon_ICON_WALK = 16,
  Icon_ICON_DONT_WALK = 17,
  Icon_ICON_BICYCLE = 18,
  Icon_ICON_PEDESTRIAN_AND_BICYCLE = 19,
  Icon_ICON_COUNTDOWN_SECONDS = 20,
  Icon_ICON_COUNTDOWN_PERCENT = 21,
  Icon_ICON_TRAM = 22,
  Icon_ICON_BUS = 23,
  Icon_ICON_BUS_AND_TRAM = 24,
  Icon_MIN = Icon_ICON_UNKNOWN,
  Icon_MAX = Icon_ICON_BUS_AND_TRAM
};

inline const Icon (&EnumValuesIcon())[25] {
  static const Icon values[] = {
    Icon_ICON_UNKNOWN,
    Icon_ICON_OTHER,
    Icon_ICON_NONE,
    Icon_ICON_ARROW_STRAIGHT_AHEAD,
    Icon_ICON_ARROW_LEFT,
    Icon_ICON_ARROW_DIAG_LEFT,
    Icon_ICON_ARROW_STRAIGHT_AHEAD_LEFT,
    Icon_ICON_ARROW_RIGHT,
    Icon_ICON_ARROW_DIAG_RIGHT,
    Icon_ICON_ARROW_STRAIGHT_AHEAD_RIGHT,
    Icon_ICON_ARROW_LEFT_RIGHT,
    Icon_ICON_ARROW_DOWN,
    Icon_ICON_ARROW_DOWN_LEFT,
    Icon_ICON_ARROW_DOWN_RIGHT,
    Icon_ICON_ARROW_CROSS,
    Icon_ICON_PEDESTRIAN,
    Icon_ICON_WALK,
    Icon_ICON_DONT_WALK,
    Icon_ICON_BICYCLE,
    Icon_ICON_PEDESTRIAN_AND_BICYCLE,
    Icon_ICON_COUNTDOWN_SECONDS,
    Icon_ICON_COUNTDOWN_PERCENT,
    Icon_ICON_TRAM,
    Icon_ICON_BUS,
    Icon_ICON_BUS_AND_TRAM
  };
  return values;
}

inline const char * const *EnumNamesIcon() {
  static const char * const names[26] = {
    "ICON_UNKNOWN",
    "ICON_OTHER",
    "ICON_NONE",
    "ICON_ARROW_STRAIGHT_AHEAD",
    "ICON_ARROW_LEFT",
    "ICON_ARROW_DIAG_LEFT",
    "ICON_ARROW_STRAIGHT_AHEAD_LEFT",
    "ICON_ARROW_RIGHT",
    "ICON_ARROW_DIAG_RIGHT",
    "ICON_ARROW_STRAIGHT_AHEAD_RIGHT",
    "ICON_ARROW_LEFT_RIGHT",
    "ICON_ARROW_DOWN",
    "ICON_ARROW_DOWN_LEFT",
    "ICON_ARROW_DOWN_RIGHT",
    "ICON_ARROW_CROSS",
    "ICON_PEDESTRIAN",
    "ICON_WALK",
    "ICON_DONT_WALK",
    "ICON_BICYCLE",
    "ICON_PEDESTRIAN_AND_BICYCLE",
    "ICON_COUNTDOWN_SECONDS",
    "ICON_COUNTDOWN_PERCENT",
    "ICON_TRAM",
    "ICON_BUS",
    "ICON_BUS_AND_TRAM",
    nullptr
  };
  return names;
}

inline const char *EnumNameIcon(Icon e) {
  if (::flatbuffers::IsOutRange(e, Icon_ICON_UNKNOWN, Icon_ICON_BUS_AND_TRAM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesIcon()[index];
}

enum Mode : int32_t {
  Mode_MODE_UNKNOWN = 0,
  Mode_MODE_OTHER = 1,
  Mode_MODE_OFF = 2,
  Mode_MODE_CONSTANT = 3,
  Mode_MODE_FLASHING = 4,
  Mode_MODE_COUNTING = 5,
  Mode_MIN = Mode_MODE_UNKNOWN,
  Mode_MAX = Mode_MODE_COUNTING
};

inline const Mode (&EnumValuesMode())[6] {
  static const Mode values[] = {
    Mode_MODE_UNKNOWN,
    Mode_MODE_OTHER,
    Mode_MODE_OFF,
    Mode_MODE_CONSTANT,
    Mode_MODE_FLASHING,
    Mode_MODE_COUNTING
  };
  return values;
}

inline const char * const *EnumNamesMode() {
  static const char * const names[7] = {
    "MODE_UNKNOWN",
    "MODE_OTHER",
    "MODE_OFF",
    "MODE_CONSTANT",
    "MODE_FLASHING",
    "MODE_COUNTING",
    nullptr
  };
  return names;
}

inline const char *EnumNameMode(Mode e) {
  if (::flatbuffers::IsOutRange(e, Mode_MODE_UNKNOWN, Mode_MODE_COUNTING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMode()[index];
}

}  // namespace Classification_

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLOR = 4,
    VT_ICON = 6,
    VT_MODE = 8,
    VT_COUNTER = 10,
    VT_ASSIGNED_LANE_ID = 12,
    VT_IS_OUT_OF_SERVICE = 14,
    VT_LOGICAL_LANE_ASSIGNMENT = 16
  };
  osi3::TrafficLight_::Classification_::Color color() const {
    return static_cast<osi3::TrafficLight_::Classification_::Color>(GetField<int32_t>(VT_COLOR, 0));
  }
  osi3::TrafficLight_::Classification_::Icon icon() const {
    return static_cast<osi3::TrafficLight_::Classification_::Icon>(GetField<int32_t>(VT_ICON, 0));
  }
  osi3::TrafficLight_::Classification_::Mode mode() const {
    return static_cast<osi3::TrafficLight_::Classification_::Mode>(GetField<int32_t>(VT_MODE, 0));
  }
  double counter() const {
    return GetField<double>(VT_COUNTER, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_ASSIGNED_LANE_ID);
  }
  bool is_out_of_service() const {
    return GetField<uint8_t>(VT_IS_OUT_OF_SERVICE, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *>(VT_LOGICAL_LANE_ASSIGNMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_COLOR, 4) &&
           VerifyField<int32_t>(verifier, VT_ICON, 4) &&
           VerifyField<int32_t>(verifier, VT_MODE, 4) &&
           VerifyField<double>(verifier, VT_COUNTER, 8) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyVector(assigned_lane_id()) &&
           verifier.VerifyVectorOfTables(assigned_lane_id()) &&
           VerifyField<uint8_t>(verifier, VT_IS_OUT_OF_SERVICE, 1) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE_ASSIGNMENT) &&
           verifier.VerifyVector(logical_lane_assignment()) &&
           verifier.VerifyVectorOfTables(logical_lane_assignment()) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_color(osi3::TrafficLight_::Classification_::Color color) {
    fbb_.AddElement<int32_t>(Classification::VT_COLOR, static_cast<int32_t>(color), 0);
  }
  void add_icon(osi3::TrafficLight_::Classification_::Icon icon) {
    fbb_.AddElement<int32_t>(Classification::VT_ICON, static_cast<int32_t>(icon), 0);
  }
  void add_mode(osi3::TrafficLight_::Classification_::Mode mode) {
    fbb_.AddElement<int32_t>(Classification::VT_MODE, static_cast<int32_t>(mode), 0);
  }
  void add_counter(double counter) {
    fbb_.AddElement<double>(Classification::VT_COUNTER, counter, 0.0);
  }
  void add_assigned_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id) {
    fbb_.AddOffset(Classification::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_is_out_of_service(bool is_out_of_service) {
    fbb_.AddElement<uint8_t>(Classification::VT_IS_OUT_OF_SERVICE, static_cast<uint8_t>(is_out_of_service), 0);
  }
  void add_logical_lane_assignment(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment) {
    fbb_.AddOffset(Classification::VT_LOGICAL_LANE_ASSIGNMENT, logical_lane_assignment);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::TrafficLight_::Classification_::Color color = osi3::TrafficLight_::Classification_::Color_COLOR_UNKNOWN,
    osi3::TrafficLight_::Classification_::Icon icon = osi3::TrafficLight_::Classification_::Icon_ICON_UNKNOWN,
    osi3::TrafficLight_::Classification_::Mode mode = osi3::TrafficLight_::Classification_::Mode_MODE_UNKNOWN,
    double counter = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id = 0,
    bool is_out_of_service = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment = 0) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_counter(counter);
  builder_.add_logical_lane_assignment(logical_lane_assignment);
  builder_.add_assigned_lane_id(assigned_lane_id);
  builder_.add_mode(mode);
  builder_.add_icon(icon);
  builder_.add_color(color);
  builder_.add_is_out_of_service(is_out_of_service);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Classification> CreateClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::TrafficLight_::Classification_::Color color = osi3::TrafficLight_::Classification_::Color_COLOR_UNKNOWN,
    osi3::TrafficLight_::Classification_::Icon icon = osi3::TrafficLight_::Classification_::Icon_ICON_UNKNOWN,
    osi3::TrafficLight_::Classification_::Mode mode = osi3::TrafficLight_::Classification_::Mode_MODE_UNKNOWN,
    double counter = 0.0,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id = nullptr,
    bool is_out_of_service = false,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment = nullptr) {
  auto assigned_lane_id__ = assigned_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*assigned_lane_id) : 0;
  auto logical_lane_assignment__ = logical_lane_assignment ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>(*logical_lane_assignment) : 0;
  return osi3::TrafficLight_::CreateClassification(
      _fbb,
      color,
      icon,
      mode,
      counter,
      assigned_lane_id__,
      is_out_of_service,
      logical_lane_assignment__);
}

}  // namespace TrafficLight_

struct TrafficLight FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrafficLightBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BASE = 6,
    VT_CLASSIFICATION = 8,
    VT_MODEL_REFERENCE = 10,
    VT_SOURCE_REFERENCE = 12,
    VT_COLOR_DESCRIPTION = 14
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::BaseStationary *base() const {
    return GetPointer<const osi3::BaseStationary *>(VT_BASE);
  }
  const osi3::TrafficLight_::Classification *classification() const {
    return GetPointer<const osi3::TrafficLight_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::ColorDescription *color_description() const {
    return GetPointer<const osi3::ColorDescription *>(VT_COLOR_DESCRIPTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_COLOR_DESCRIPTION) &&
           verifier.VerifyTable(color_description()) &&
           verifier.EndTable();
  }
};

struct TrafficLightBuilder {
  typedef TrafficLight Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(TrafficLight::VT_ID, id);
  }
  void add_base(::flatbuffers::Offset<osi3::BaseStationary> base) {
    fbb_.AddOffset(TrafficLight::VT_BASE, base);
  }
  void add_classification(::flatbuffers::Offset<osi3::TrafficLight_::Classification> classification) {
    fbb_.AddOffset(TrafficLight::VT_CLASSIFICATION, classification);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(TrafficLight::VT_MODEL_REFERENCE, model_reference);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(TrafficLight::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_color_description(::flatbuffers::Offset<osi3::ColorDescription> color_description) {
    fbb_.AddOffset(TrafficLight::VT_COLOR_DESCRIPTION, color_description);
  }
  explicit TrafficLightBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrafficLight> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrafficLight>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrafficLight> CreateTrafficLight(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::TrafficLight_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  TrafficLightBuilder builder_(_fbb);
  builder_.add_color_description(color_description);
  builder_.add_source_reference(source_reference);
  builder_.add_model_reference(model_reference);
  builder_.add_classification(classification);
  builder_.add_base(base);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrafficLight> CreateTrafficLightDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::TrafficLight_::Classification> classification = 0,
    const char *model_reference = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateTrafficLight(
      _fbb,
      id,
      base,
      classification,
      model_reference__,
      source_reference__,
      color_description);
}

namespace TrafficLight_ {

}  // namespace TrafficLight_

}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSITRAFFICLIGHT_OSI3_H_
