include "osi_common.fbs";

namespace osi3.Lane_.Classification_;
enum Type : int {
    TYPE_UNKNOWN = 0,
    TYPE_OTHER = 1,
    TYPE_DRIVING = 2,
    TYPE_NONDRIVING = 3,
    TYPE_INTERSECTION = 4,
}

namespace osi3.Lane_.Classification_;
enum Subtype : int {
    SUBTYPE_UNKNOWN = 0,
    SUBTYPE_OTHER = 1,
    SUBTYPE_NORMAL = 2,
    SUBTYPE_BIKING = 3,
    SUBTYPE_SIDEWALK = 4,
    SUBTYPE_PARKING = 5,
    SUBTYPE_STOP = 6,
    SUBTYPE_RESTRICTED = 7,
    SUBTYPE_BORDER = 8,
    SUBTYPE_SHOULDER = 9,
    SUBTYPE_EXIT = 10,
    SUBTYPE_ENTRY = 11,
    SUBTYPE_ONRAMP = 12,
    SUBTYPE_OFFRAMP = 13,
    SUBTYPE_CONNECTINGRAMP = 14,
}

namespace osi3.Lane_.Classification_;
table RoadCondition {
  surface_temperature:double;
  surface_water_film:double;
  surface_freezing_point:double;
  surface_ice:double;
  surface_roughness:double;
  surface_texture:double;
}

namespace osi3.Lane_.Classification_;
table LanePairing {
  antecessor_lane_id:osi3.Identifier;
  successor_lane_id:osi3.Identifier;
}

namespace osi3.Lane_;
table Classification {
  type:osi3.Lane_.Classification_.Type;
  is_host_vehicle_lane:bool;
  centerline:[osi3.Vector3d];
  centerline_is_driving_direction:bool;
  left_adjacent_lane_id:[osi3.Identifier];
  right_adjacent_lane_id:[osi3.Identifier];
  lane_pairing:[osi3.Lane_.Classification_.LanePairing];
  right_lane_boundary_id:[osi3.Identifier];
  left_lane_boundary_id:[osi3.Identifier];
  free_lane_boundary_id:[osi3.Identifier];
  road_condition:osi3.Lane_.Classification_.RoadCondition;
  subtype:osi3.Lane_.Classification_.Subtype;
}

namespace osi3;
table Lane {
  id:osi3.Identifier;
  classification:osi3.Lane_.Classification;
  source_reference:[osi3.ExternalReference];
}

namespace osi3.LaneBoundary_.BoundaryPoint_;
enum Dash : int {
    DASH_UNKNOWN = 0,
    DASH_OTHER = 1,
    DASH_START = 2,
    DASH_CONTINUE = 3,
    DASH_END = 4,
    DASH_GAP = 5,
}

namespace osi3.LaneBoundary_;
table BoundaryPoint {
  position:osi3.Vector3d;
  width:double;
  height:double;
  dash:osi3.LaneBoundary_.BoundaryPoint_.Dash;
}

namespace osi3.LaneBoundary_.Classification_;
enum Type : int {
    TYPE_UNKNOWN = 0,
    TYPE_OTHER = 1,
    TYPE_NO_LINE = 2,
    TYPE_SOLID_LINE = 3,
    TYPE_DASHED_LINE = 4,
    TYPE_BOTTS_DOTS = 5,
    TYPE_ROAD_EDGE = 6,
    TYPE_SNOW_EDGE = 7,
    TYPE_GRASS_EDGE = 8,
    TYPE_GRAVEL_EDGE = 9,
    TYPE_SOIL_EDGE = 10,
    TYPE_GUARD_RAIL = 11,
    TYPE_CURB = 12,
    TYPE_STRUCTURE = 13,
    TYPE_BARRIER = 14,
    TYPE_SOUND_BARRIER = 15,
}

namespace osi3.LaneBoundary_.Classification_;
enum Color : int {
    COLOR_UNKNOWN = 0,
    COLOR_OTHER = 1,
    COLOR_NONE = 2,
    COLOR_WHITE = 3,
    COLOR_YELLOW = 4,
    COLOR_RED = 5,
    COLOR_BLUE = 6,
    COLOR_GREEN = 7,
    COLOR_VIOLET = 8,
    COLOR_ORANGE = 9,
}

namespace osi3.LaneBoundary_;
table Classification {
  type:osi3.LaneBoundary_.Classification_.Type;
  color:osi3.LaneBoundary_.Classification_.Color;
  limiting_structure_id:[osi3.Identifier];
}

namespace osi3;
table LaneBoundary {
  id:osi3.Identifier;
  boundary_line:[osi3.LaneBoundary_.BoundaryPoint];
  classification:osi3.LaneBoundary_.Classification;
  source_reference:[osi3.ExternalReference];
  color_description:osi3.ColorDescription;
}
