// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIREFERENCELINE_OSI3_H_
#define FLATBUFFERS_GENERATED_OSIREFERENCELINE_OSI3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {
namespace ReferenceLine_ {

struct ReferenceLinePoint;
struct ReferenceLinePointBuilder;

}  // namespace ReferenceLine_

struct ReferenceLine;
struct ReferenceLineBuilder;

namespace ReferenceLine_ {

enum Type : int32_t {
  Type_TYPE_POLYLINE = 0,
  Type_TYPE_POLYLINE_WITH_T_AXIS = 1,
  Type_MIN = Type_TYPE_POLYLINE,
  Type_MAX = Type_TYPE_POLYLINE_WITH_T_AXIS
};

inline const Type (&EnumValuesType())[2] {
  static const Type values[] = {
    Type_TYPE_POLYLINE,
    Type_TYPE_POLYLINE_WITH_T_AXIS
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[3] = {
    "TYPE_POLYLINE",
    "TYPE_POLYLINE_WITH_T_AXIS",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_POLYLINE, Type_TYPE_POLYLINE_WITH_T_AXIS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

struct ReferenceLinePoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReferenceLinePointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WORLD_POSITION = 4,
    VT_S_POSITION = 6,
    VT_T_AXIS_YAW = 8
  };
  const osi3::Vector3d *world_position() const {
    return GetPointer<const osi3::Vector3d *>(VT_WORLD_POSITION);
  }
  double s_position() const {
    return GetField<double>(VT_S_POSITION, 0.0);
  }
  double t_axis_yaw() const {
    return GetField<double>(VT_T_AXIS_YAW, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_WORLD_POSITION) &&
           verifier.VerifyTable(world_position()) &&
           VerifyField<double>(verifier, VT_S_POSITION, 8) &&
           VerifyField<double>(verifier, VT_T_AXIS_YAW, 8) &&
           verifier.EndTable();
  }
};

struct ReferenceLinePointBuilder {
  typedef ReferenceLinePoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_world_position(::flatbuffers::Offset<osi3::Vector3d> world_position) {
    fbb_.AddOffset(ReferenceLinePoint::VT_WORLD_POSITION, world_position);
  }
  void add_s_position(double s_position) {
    fbb_.AddElement<double>(ReferenceLinePoint::VT_S_POSITION, s_position, 0.0);
  }
  void add_t_axis_yaw(double t_axis_yaw) {
    fbb_.AddElement<double>(ReferenceLinePoint::VT_T_AXIS_YAW, t_axis_yaw, 0.0);
  }
  explicit ReferenceLinePointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReferenceLinePoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReferenceLinePoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReferenceLinePoint> CreateReferenceLinePoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> world_position = 0,
    double s_position = 0.0,
    double t_axis_yaw = 0.0) {
  ReferenceLinePointBuilder builder_(_fbb);
  builder_.add_t_axis_yaw(t_axis_yaw);
  builder_.add_s_position(s_position);
  builder_.add_world_position(world_position);
  return builder_.Finish();
}

}  // namespace ReferenceLine_

struct ReferenceLine FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReferenceLineBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_POLY_LINE = 8
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  osi3::ReferenceLine_::Type type() const {
    return static_cast<osi3::ReferenceLine_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>> *poly_line() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>> *>(VT_POLY_LINE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_POLY_LINE) &&
           verifier.VerifyVector(poly_line()) &&
           verifier.VerifyVectorOfTables(poly_line()) &&
           verifier.EndTable();
  }
};

struct ReferenceLineBuilder {
  typedef ReferenceLine Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(ReferenceLine::VT_ID, id);
  }
  void add_type(osi3::ReferenceLine_::Type type) {
    fbb_.AddElement<int32_t>(ReferenceLine::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_poly_line(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>>> poly_line) {
    fbb_.AddOffset(ReferenceLine::VT_POLY_LINE, poly_line);
  }
  explicit ReferenceLineBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReferenceLine> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReferenceLine>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReferenceLine> CreateReferenceLine(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    osi3::ReferenceLine_::Type type = osi3::ReferenceLine_::Type_TYPE_POLYLINE,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>>> poly_line = 0) {
  ReferenceLineBuilder builder_(_fbb);
  builder_.add_poly_line(poly_line);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReferenceLine> CreateReferenceLineDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    osi3::ReferenceLine_::Type type = osi3::ReferenceLine_::Type_TYPE_POLYLINE,
    const std::vector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>> *poly_line = nullptr) {
  auto poly_line__ = poly_line ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ReferenceLine_::ReferenceLinePoint>>(*poly_line) : 0;
  return osi3::CreateReferenceLine(
      _fbb,
      id,
      type,
      poly_line__);
}

namespace ReferenceLine_ {

}  // namespace ReferenceLine_

}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIREFERENCELINE_OSI3_H_
