// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSILANE_OSI3_H_
#define FLATBUFFERS_GENERATED_OSILANE_OSI3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {
namespace Lane_ {
namespace Classification_ {

struct RoadCondition;
struct RoadConditionBuilder;

struct LanePairing;
struct LanePairingBuilder;

}  // namespace Classification_

struct Classification;
struct ClassificationBuilder;

}  // namespace Lane_

struct Lane;
struct LaneBuilder;

namespace LaneBoundary_ {

struct BoundaryPoint;
struct BoundaryPointBuilder;

struct Classification;
struct ClassificationBuilder;

}  // namespace LaneBoundary_

struct LaneBoundary;
struct LaneBoundaryBuilder;

namespace Lane_ {
namespace Classification_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_DRIVING = 2,
  Type_TYPE_NONDRIVING = 3,
  Type_TYPE_INTERSECTION = 4,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_INTERSECTION
};

inline const Type (&EnumValuesType())[5] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_DRIVING,
    Type_TYPE_NONDRIVING,
    Type_TYPE_INTERSECTION
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[6] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_DRIVING",
    "TYPE_NONDRIVING",
    "TYPE_INTERSECTION",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_INTERSECTION)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

enum Subtype : int32_t {
  Subtype_SUBTYPE_UNKNOWN = 0,
  Subtype_SUBTYPE_OTHER = 1,
  Subtype_SUBTYPE_NORMAL = 2,
  Subtype_SUBTYPE_BIKING = 3,
  Subtype_SUBTYPE_SIDEWALK = 4,
  Subtype_SUBTYPE_PARKING = 5,
  Subtype_SUBTYPE_STOP = 6,
  Subtype_SUBTYPE_RESTRICTED = 7,
  Subtype_SUBTYPE_BORDER = 8,
  Subtype_SUBTYPE_SHOULDER = 9,
  Subtype_SUBTYPE_EXIT = 10,
  Subtype_SUBTYPE_ENTRY = 11,
  Subtype_SUBTYPE_ONRAMP = 12,
  Subtype_SUBTYPE_OFFRAMP = 13,
  Subtype_SUBTYPE_CONNECTINGRAMP = 14,
  Subtype_MIN = Subtype_SUBTYPE_UNKNOWN,
  Subtype_MAX = Subtype_SUBTYPE_CONNECTINGRAMP
};

inline const Subtype (&EnumValuesSubtype())[15] {
  static const Subtype values[] = {
    Subtype_SUBTYPE_UNKNOWN,
    Subtype_SUBTYPE_OTHER,
    Subtype_SUBTYPE_NORMAL,
    Subtype_SUBTYPE_BIKING,
    Subtype_SUBTYPE_SIDEWALK,
    Subtype_SUBTYPE_PARKING,
    Subtype_SUBTYPE_STOP,
    Subtype_SUBTYPE_RESTRICTED,
    Subtype_SUBTYPE_BORDER,
    Subtype_SUBTYPE_SHOULDER,
    Subtype_SUBTYPE_EXIT,
    Subtype_SUBTYPE_ENTRY,
    Subtype_SUBTYPE_ONRAMP,
    Subtype_SUBTYPE_OFFRAMP,
    Subtype_SUBTYPE_CONNECTINGRAMP
  };
  return values;
}

inline const char * const *EnumNamesSubtype() {
  static const char * const names[16] = {
    "SUBTYPE_UNKNOWN",
    "SUBTYPE_OTHER",
    "SUBTYPE_NORMAL",
    "SUBTYPE_BIKING",
    "SUBTYPE_SIDEWALK",
    "SUBTYPE_PARKING",
    "SUBTYPE_STOP",
    "SUBTYPE_RESTRICTED",
    "SUBTYPE_BORDER",
    "SUBTYPE_SHOULDER",
    "SUBTYPE_EXIT",
    "SUBTYPE_ENTRY",
    "SUBTYPE_ONRAMP",
    "SUBTYPE_OFFRAMP",
    "SUBTYPE_CONNECTINGRAMP",
    nullptr
  };
  return names;
}

inline const char *EnumNameSubtype(Subtype e) {
  if (::flatbuffers::IsOutRange(e, Subtype_SUBTYPE_UNKNOWN, Subtype_SUBTYPE_CONNECTINGRAMP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSubtype()[index];
}

}  // namespace Classification_
}  // namespace Lane_

namespace LaneBoundary_ {
namespace BoundaryPoint_ {

enum Dash : int32_t {
  Dash_DASH_UNKNOWN = 0,
  Dash_DASH_OTHER = 1,
  Dash_DASH_START = 2,
  Dash_DASH_CONTINUE = 3,
  Dash_DASH_END = 4,
  Dash_DASH_GAP = 5,
  Dash_MIN = Dash_DASH_UNKNOWN,
  Dash_MAX = Dash_DASH_GAP
};

inline const Dash (&EnumValuesDash())[6] {
  static const Dash values[] = {
    Dash_DASH_UNKNOWN,
    Dash_DASH_OTHER,
    Dash_DASH_START,
    Dash_DASH_CONTINUE,
    Dash_DASH_END,
    Dash_DASH_GAP
  };
  return values;
}

inline const char * const *EnumNamesDash() {
  static const char * const names[7] = {
    "DASH_UNKNOWN",
    "DASH_OTHER",
    "DASH_START",
    "DASH_CONTINUE",
    "DASH_END",
    "DASH_GAP",
    nullptr
  };
  return names;
}

inline const char *EnumNameDash(Dash e) {
  if (::flatbuffers::IsOutRange(e, Dash_DASH_UNKNOWN, Dash_DASH_GAP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDash()[index];
}

}  // namespace BoundaryPoint_

namespace Classification_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_NO_LINE = 2,
  Type_TYPE_SOLID_LINE = 3,
  Type_TYPE_DASHED_LINE = 4,
  Type_TYPE_BOTTS_DOTS = 5,
  Type_TYPE_ROAD_EDGE = 6,
  Type_TYPE_SNOW_EDGE = 7,
  Type_TYPE_GRASS_EDGE = 8,
  Type_TYPE_GRAVEL_EDGE = 9,
  Type_TYPE_SOIL_EDGE = 10,
  Type_TYPE_GUARD_RAIL = 11,
  Type_TYPE_CURB = 12,
  Type_TYPE_STRUCTURE = 13,
  Type_TYPE_BARRIER = 14,
  Type_TYPE_SOUND_BARRIER = 15,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_SOUND_BARRIER
};

inline const Type (&EnumValuesType())[16] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_NO_LINE,
    Type_TYPE_SOLID_LINE,
    Type_TYPE_DASHED_LINE,
    Type_TYPE_BOTTS_DOTS,
    Type_TYPE_ROAD_EDGE,
    Type_TYPE_SNOW_EDGE,
    Type_TYPE_GRASS_EDGE,
    Type_TYPE_GRAVEL_EDGE,
    Type_TYPE_SOIL_EDGE,
    Type_TYPE_GUARD_RAIL,
    Type_TYPE_CURB,
    Type_TYPE_STRUCTURE,
    Type_TYPE_BARRIER,
    Type_TYPE_SOUND_BARRIER
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[17] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_NO_LINE",
    "TYPE_SOLID_LINE",
    "TYPE_DASHED_LINE",
    "TYPE_BOTTS_DOTS",
    "TYPE_ROAD_EDGE",
    "TYPE_SNOW_EDGE",
    "TYPE_GRASS_EDGE",
    "TYPE_GRAVEL_EDGE",
    "TYPE_SOIL_EDGE",
    "TYPE_GUARD_RAIL",
    "TYPE_CURB",
    "TYPE_STRUCTURE",
    "TYPE_BARRIER",
    "TYPE_SOUND_BARRIER",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_SOUND_BARRIER)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

enum Color : int32_t {
  Color_COLOR_UNKNOWN = 0,
  Color_COLOR_OTHER = 1,
  Color_COLOR_NONE = 2,
  Color_COLOR_WHITE = 3,
  Color_COLOR_YELLOW = 4,
  Color_COLOR_RED = 5,
  Color_COLOR_BLUE = 6,
  Color_COLOR_GREEN = 7,
  Color_COLOR_VIOLET = 8,
  Color_COLOR_ORANGE = 9,
  Color_MIN = Color_COLOR_UNKNOWN,
  Color_MAX = Color_COLOR_ORANGE
};

inline const Color (&EnumValuesColor())[10] {
  static const Color values[] = {
    Color_COLOR_UNKNOWN,
    Color_COLOR_OTHER,
    Color_COLOR_NONE,
    Color_COLOR_WHITE,
    Color_COLOR_YELLOW,
    Color_COLOR_RED,
    Color_COLOR_BLUE,
    Color_COLOR_GREEN,
    Color_COLOR_VIOLET,
    Color_COLOR_ORANGE
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[11] = {
    "COLOR_UNKNOWN",
    "COLOR_OTHER",
    "COLOR_NONE",
    "COLOR_WHITE",
    "COLOR_YELLOW",
    "COLOR_RED",
    "COLOR_BLUE",
    "COLOR_GREEN",
    "COLOR_VIOLET",
    "COLOR_ORANGE",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (::flatbuffers::IsOutRange(e, Color_COLOR_UNKNOWN, Color_COLOR_ORANGE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

}  // namespace Classification_
}  // namespace LaneBoundary_

namespace Lane_ {
namespace Classification_ {

struct RoadCondition FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RoadConditionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SURFACE_TEMPERATURE = 4,
    VT_SURFACE_WATER_FILM = 6,
    VT_SURFACE_FREEZING_POINT = 8,
    VT_SURFACE_ICE = 10,
    VT_SURFACE_ROUGHNESS = 12,
    VT_SURFACE_TEXTURE = 14
  };
  double surface_temperature() const {
    return GetField<double>(VT_SURFACE_TEMPERATURE, 0.0);
  }
  double surface_water_film() const {
    return GetField<double>(VT_SURFACE_WATER_FILM, 0.0);
  }
  double surface_freezing_point() const {
    return GetField<double>(VT_SURFACE_FREEZING_POINT, 0.0);
  }
  double surface_ice() const {
    return GetField<double>(VT_SURFACE_ICE, 0.0);
  }
  double surface_roughness() const {
    return GetField<double>(VT_SURFACE_ROUGHNESS, 0.0);
  }
  double surface_texture() const {
    return GetField<double>(VT_SURFACE_TEXTURE, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_SURFACE_TEMPERATURE, 8) &&
           VerifyField<double>(verifier, VT_SURFACE_WATER_FILM, 8) &&
           VerifyField<double>(verifier, VT_SURFACE_FREEZING_POINT, 8) &&
           VerifyField<double>(verifier, VT_SURFACE_ICE, 8) &&
           VerifyField<double>(verifier, VT_SURFACE_ROUGHNESS, 8) &&
           VerifyField<double>(verifier, VT_SURFACE_TEXTURE, 8) &&
           verifier.EndTable();
  }
};

struct RoadConditionBuilder {
  typedef RoadCondition Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_surface_temperature(double surface_temperature) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_TEMPERATURE, surface_temperature, 0.0);
  }
  void add_surface_water_film(double surface_water_film) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_WATER_FILM, surface_water_film, 0.0);
  }
  void add_surface_freezing_point(double surface_freezing_point) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_FREEZING_POINT, surface_freezing_point, 0.0);
  }
  void add_surface_ice(double surface_ice) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_ICE, surface_ice, 0.0);
  }
  void add_surface_roughness(double surface_roughness) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_ROUGHNESS, surface_roughness, 0.0);
  }
  void add_surface_texture(double surface_texture) {
    fbb_.AddElement<double>(RoadCondition::VT_SURFACE_TEXTURE, surface_texture, 0.0);
  }
  explicit RoadConditionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RoadCondition> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RoadCondition>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RoadCondition> CreateRoadCondition(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double surface_temperature = 0.0,
    double surface_water_film = 0.0,
    double surface_freezing_point = 0.0,
    double surface_ice = 0.0,
    double surface_roughness = 0.0,
    double surface_texture = 0.0) {
  RoadConditionBuilder builder_(_fbb);
  builder_.add_surface_texture(surface_texture);
  builder_.add_surface_roughness(surface_roughness);
  builder_.add_surface_ice(surface_ice);
  builder_.add_surface_freezing_point(surface_freezing_point);
  builder_.add_surface_water_film(surface_water_film);
  builder_.add_surface_temperature(surface_temperature);
  return builder_.Finish();
}

struct LanePairing FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LanePairingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANTECESSOR_LANE_ID = 4,
    VT_SUCCESSOR_LANE_ID = 6
  };
  const osi3::Identifier *antecessor_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_ANTECESSOR_LANE_ID);
  }
  const osi3::Identifier *successor_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_SUCCESSOR_LANE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ANTECESSOR_LANE_ID) &&
           verifier.VerifyTable(antecessor_lane_id()) &&
           VerifyOffset(verifier, VT_SUCCESSOR_LANE_ID) &&
           verifier.VerifyTable(successor_lane_id()) &&
           verifier.EndTable();
  }
};

struct LanePairingBuilder {
  typedef LanePairing Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_antecessor_lane_id(::flatbuffers::Offset<osi3::Identifier> antecessor_lane_id) {
    fbb_.AddOffset(LanePairing::VT_ANTECESSOR_LANE_ID, antecessor_lane_id);
  }
  void add_successor_lane_id(::flatbuffers::Offset<osi3::Identifier> successor_lane_id) {
    fbb_.AddOffset(LanePairing::VT_SUCCESSOR_LANE_ID, successor_lane_id);
  }
  explicit LanePairingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LanePairing> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LanePairing>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LanePairing> CreateLanePairing(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> antecessor_lane_id = 0,
    ::flatbuffers::Offset<osi3::Identifier> successor_lane_id = 0) {
  LanePairingBuilder builder_(_fbb);
  builder_.add_successor_lane_id(successor_lane_id);
  builder_.add_antecessor_lane_id(antecessor_lane_id);
  return builder_.Finish();
}

}  // namespace Classification_

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_IS_HOST_VEHICLE_LANE = 6,
    VT_CENTERLINE = 8,
    VT_CENTERLINE_IS_DRIVING_DIRECTION = 10,
    VT_LEFT_ADJACENT_LANE_ID = 12,
    VT_RIGHT_ADJACENT_LANE_ID = 14,
    VT_LANE_PAIRING = 16,
    VT_RIGHT_LANE_BOUNDARY_ID = 18,
    VT_LEFT_LANE_BOUNDARY_ID = 20,
    VT_FREE_LANE_BOUNDARY_ID = 22,
    VT_ROAD_CONDITION = 24,
    VT_SUBTYPE = 26
  };
  osi3::Lane_::Classification_::Type type() const {
    return static_cast<osi3::Lane_::Classification_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  bool is_host_vehicle_lane() const {
    return GetField<uint8_t>(VT_IS_HOST_VEHICLE_LANE, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>> *centerline() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>> *>(VT_CENTERLINE);
  }
  bool centerline_is_driving_direction() const {
    return GetField<uint8_t>(VT_CENTERLINE_IS_DRIVING_DIRECTION, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *left_adjacent_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_LEFT_ADJACENT_LANE_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *right_adjacent_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_RIGHT_ADJACENT_LANE_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>> *lane_pairing() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>> *>(VT_LANE_PAIRING);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *right_lane_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_RIGHT_LANE_BOUNDARY_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *left_lane_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_LEFT_LANE_BOUNDARY_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *free_lane_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_FREE_LANE_BOUNDARY_ID);
  }
  const osi3::Lane_::Classification_::RoadCondition *road_condition() const {
    return GetPointer<const osi3::Lane_::Classification_::RoadCondition *>(VT_ROAD_CONDITION);
  }
  osi3::Lane_::Classification_::Subtype subtype() const {
    return static_cast<osi3::Lane_::Classification_::Subtype>(GetField<int32_t>(VT_SUBTYPE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_HOST_VEHICLE_LANE, 1) &&
           VerifyOffset(verifier, VT_CENTERLINE) &&
           verifier.VerifyVector(centerline()) &&
           verifier.VerifyVectorOfTables(centerline()) &&
           VerifyField<uint8_t>(verifier, VT_CENTERLINE_IS_DRIVING_DIRECTION, 1) &&
           VerifyOffset(verifier, VT_LEFT_ADJACENT_LANE_ID) &&
           verifier.VerifyVector(left_adjacent_lane_id()) &&
           verifier.VerifyVectorOfTables(left_adjacent_lane_id()) &&
           VerifyOffset(verifier, VT_RIGHT_ADJACENT_LANE_ID) &&
           verifier.VerifyVector(right_adjacent_lane_id()) &&
           verifier.VerifyVectorOfTables(right_adjacent_lane_id()) &&
           VerifyOffset(verifier, VT_LANE_PAIRING) &&
           verifier.VerifyVector(lane_pairing()) &&
           verifier.VerifyVectorOfTables(lane_pairing()) &&
           VerifyOffset(verifier, VT_RIGHT_LANE_BOUNDARY_ID) &&
           verifier.VerifyVector(right_lane_boundary_id()) &&
           verifier.VerifyVectorOfTables(right_lane_boundary_id()) &&
           VerifyOffset(verifier, VT_LEFT_LANE_BOUNDARY_ID) &&
           verifier.VerifyVector(left_lane_boundary_id()) &&
           verifier.VerifyVectorOfTables(left_lane_boundary_id()) &&
           VerifyOffset(verifier, VT_FREE_LANE_BOUNDARY_ID) &&
           verifier.VerifyVector(free_lane_boundary_id()) &&
           verifier.VerifyVectorOfTables(free_lane_boundary_id()) &&
           VerifyOffset(verifier, VT_ROAD_CONDITION) &&
           verifier.VerifyTable(road_condition()) &&
           VerifyField<int32_t>(verifier, VT_SUBTYPE, 4) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::Lane_::Classification_::Type type) {
    fbb_.AddElement<int32_t>(Classification::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_is_host_vehicle_lane(bool is_host_vehicle_lane) {
    fbb_.AddElement<uint8_t>(Classification::VT_IS_HOST_VEHICLE_LANE, static_cast<uint8_t>(is_host_vehicle_lane), 0);
  }
  void add_centerline(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>>> centerline) {
    fbb_.AddOffset(Classification::VT_CENTERLINE, centerline);
  }
  void add_centerline_is_driving_direction(bool centerline_is_driving_direction) {
    fbb_.AddElement<uint8_t>(Classification::VT_CENTERLINE_IS_DRIVING_DIRECTION, static_cast<uint8_t>(centerline_is_driving_direction), 0);
  }
  void add_left_adjacent_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_adjacent_lane_id) {
    fbb_.AddOffset(Classification::VT_LEFT_ADJACENT_LANE_ID, left_adjacent_lane_id);
  }
  void add_right_adjacent_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_adjacent_lane_id) {
    fbb_.AddOffset(Classification::VT_RIGHT_ADJACENT_LANE_ID, right_adjacent_lane_id);
  }
  void add_lane_pairing(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>>> lane_pairing) {
    fbb_.AddOffset(Classification::VT_LANE_PAIRING, lane_pairing);
  }
  void add_right_lane_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_lane_boundary_id) {
    fbb_.AddOffset(Classification::VT_RIGHT_LANE_BOUNDARY_ID, right_lane_boundary_id);
  }
  void add_left_lane_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_lane_boundary_id) {
    fbb_.AddOffset(Classification::VT_LEFT_LANE_BOUNDARY_ID, left_lane_boundary_id);
  }
  void add_free_lane_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> free_lane_boundary_id) {
    fbb_.AddOffset(Classification::VT_FREE_LANE_BOUNDARY_ID, free_lane_boundary_id);
  }
  void add_road_condition(::flatbuffers::Offset<osi3::Lane_::Classification_::RoadCondition> road_condition) {
    fbb_.AddOffset(Classification::VT_ROAD_CONDITION, road_condition);
  }
  void add_subtype(osi3::Lane_::Classification_::Subtype subtype) {
    fbb_.AddElement<int32_t>(Classification::VT_SUBTYPE, static_cast<int32_t>(subtype), 0);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::Lane_::Classification_::Type type = osi3::Lane_::Classification_::Type_TYPE_UNKNOWN,
    bool is_host_vehicle_lane = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Vector3d>>> centerline = 0,
    bool centerline_is_driving_direction = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_adjacent_lane_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_adjacent_lane_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>>> lane_pairing = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_lane_boundary_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_lane_boundary_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> free_lane_boundary_id = 0,
    ::flatbuffers::Offset<osi3::Lane_::Classification_::RoadCondition> road_condition = 0,
    osi3::Lane_::Classification_::Subtype subtype = osi3::Lane_::Classification_::Subtype_SUBTYPE_UNKNOWN) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_subtype(subtype);
  builder_.add_road_condition(road_condition);
  builder_.add_free_lane_boundary_id(free_lane_boundary_id);
  builder_.add_left_lane_boundary_id(left_lane_boundary_id);
  builder_.add_right_lane_boundary_id(right_lane_boundary_id);
  builder_.add_lane_pairing(lane_pairing);
  builder_.add_right_adjacent_lane_id(right_adjacent_lane_id);
  builder_.add_left_adjacent_lane_id(left_adjacent_lane_id);
  builder_.add_centerline(centerline);
  builder_.add_type(type);
  builder_.add_centerline_is_driving_direction(centerline_is_driving_direction);
  builder_.add_is_host_vehicle_lane(is_host_vehicle_lane);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Classification> CreateClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::Lane_::Classification_::Type type = osi3::Lane_::Classification_::Type_TYPE_UNKNOWN,
    bool is_host_vehicle_lane = false,
    const std::vector<::flatbuffers::Offset<osi3::Vector3d>> *centerline = nullptr,
    bool centerline_is_driving_direction = false,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *left_adjacent_lane_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *right_adjacent_lane_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>> *lane_pairing = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *right_lane_boundary_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *left_lane_boundary_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *free_lane_boundary_id = nullptr,
    ::flatbuffers::Offset<osi3::Lane_::Classification_::RoadCondition> road_condition = 0,
    osi3::Lane_::Classification_::Subtype subtype = osi3::Lane_::Classification_::Subtype_SUBTYPE_UNKNOWN) {
  auto centerline__ = centerline ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Vector3d>>(*centerline) : 0;
  auto left_adjacent_lane_id__ = left_adjacent_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*left_adjacent_lane_id) : 0;
  auto right_adjacent_lane_id__ = right_adjacent_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*right_adjacent_lane_id) : 0;
  auto lane_pairing__ = lane_pairing ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Lane_::Classification_::LanePairing>>(*lane_pairing) : 0;
  auto right_lane_boundary_id__ = right_lane_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*right_lane_boundary_id) : 0;
  auto left_lane_boundary_id__ = left_lane_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*left_lane_boundary_id) : 0;
  auto free_lane_boundary_id__ = free_lane_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*free_lane_boundary_id) : 0;
  return osi3::Lane_::CreateClassification(
      _fbb,
      type,
      is_host_vehicle_lane,
      centerline__,
      centerline_is_driving_direction,
      left_adjacent_lane_id__,
      right_adjacent_lane_id__,
      lane_pairing__,
      right_lane_boundary_id__,
      left_lane_boundary_id__,
      free_lane_boundary_id__,
      road_condition,
      subtype);
}

}  // namespace Lane_

struct Lane FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LaneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CLASSIFICATION = 6,
    VT_SOURCE_REFERENCE = 8
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::Lane_::Classification *classification() const {
    return GetPointer<const osi3::Lane_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           verifier.EndTable();
  }
};

struct LaneBuilder {
  typedef Lane Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(Lane::VT_ID, id);
  }
  void add_classification(::flatbuffers::Offset<osi3::Lane_::Classification> classification) {
    fbb_.AddOffset(Lane::VT_CLASSIFICATION, classification);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(Lane::VT_SOURCE_REFERENCE, source_reference);
  }
  explicit LaneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Lane> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Lane>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Lane> CreateLane(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::Lane_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0) {
  LaneBuilder builder_(_fbb);
  builder_.add_source_reference(source_reference);
  builder_.add_classification(classification);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Lane> CreateLaneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::Lane_::Classification> classification = 0,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr) {
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateLane(
      _fbb,
      id,
      classification,
      source_reference__);
}

namespace LaneBoundary_ {

struct BoundaryPoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BoundaryPointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_WIDTH = 6,
    VT_HEIGHT = 8,
    VT_DASH = 10
  };
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  double width() const {
    return GetField<double>(VT_WIDTH, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  osi3::LaneBoundary_::BoundaryPoint_::Dash dash() const {
    return static_cast<osi3::LaneBoundary_::BoundaryPoint_::Dash>(GetField<int32_t>(VT_DASH, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<double>(verifier, VT_WIDTH, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           VerifyField<int32_t>(verifier, VT_DASH, 4) &&
           verifier.EndTable();
  }
};

struct BoundaryPointBuilder {
  typedef BoundaryPoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(BoundaryPoint::VT_POSITION, position);
  }
  void add_width(double width) {
    fbb_.AddElement<double>(BoundaryPoint::VT_WIDTH, width, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(BoundaryPoint::VT_HEIGHT, height, 0.0);
  }
  void add_dash(osi3::LaneBoundary_::BoundaryPoint_::Dash dash) {
    fbb_.AddElement<int32_t>(BoundaryPoint::VT_DASH, static_cast<int32_t>(dash), 0);
  }
  explicit BoundaryPointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BoundaryPoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BoundaryPoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BoundaryPoint> CreateBoundaryPoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    double width = 0.0,
    double height = 0.0,
    osi3::LaneBoundary_::BoundaryPoint_::Dash dash = osi3::LaneBoundary_::BoundaryPoint_::Dash_DASH_UNKNOWN) {
  BoundaryPointBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_dash(dash);
  builder_.add_position(position);
  return builder_.Finish();
}

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_COLOR = 6,
    VT_LIMITING_STRUCTURE_ID = 8
  };
  osi3::LaneBoundary_::Classification_::Type type() const {
    return static_cast<osi3::LaneBoundary_::Classification_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  osi3::LaneBoundary_::Classification_::Color color() const {
    return static_cast<osi3::LaneBoundary_::Classification_::Color>(GetField<int32_t>(VT_COLOR, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *limiting_structure_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_LIMITING_STRUCTURE_ID);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_COLOR, 4) &&
           VerifyOffset(verifier, VT_LIMITING_STRUCTURE_ID) &&
           verifier.VerifyVector(limiting_structure_id()) &&
           verifier.VerifyVectorOfTables(limiting_structure_id()) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::LaneBoundary_::Classification_::Type type) {
    fbb_.AddElement<int32_t>(Classification::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_color(osi3::LaneBoundary_::Classification_::Color color) {
    fbb_.AddElement<int32_t>(Classification::VT_COLOR, static_cast<int32_t>(color), 0);
  }
  void add_limiting_structure_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> limiting_structure_id) {
    fbb_.AddOffset(Classification::VT_LIMITING_STRUCTURE_ID, limiting_structure_id);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::LaneBoundary_::Classification_::Type type = osi3::LaneBoundary_::Classification_::Type_TYPE_UNKNOWN,
    osi3::LaneBoundary_::Classification_::Color color = osi3::LaneBoundary_::Classification_::Color_COLOR_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> limiting_structure_id = 0) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_limiting_structure_id(limiting_structure_id);
  builder_.add_color(color);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Classification> CreateClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::LaneBoundary_::Classification_::Type type = osi3::LaneBoundary_::Classification_::Type_TYPE_UNKNOWN,
    osi3::LaneBoundary_::Classification_::Color color = osi3::LaneBoundary_::Classification_::Color_COLOR_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *limiting_structure_id = nullptr) {
  auto limiting_structure_id__ = limiting_structure_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*limiting_structure_id) : 0;
  return osi3::LaneBoundary_::CreateClassification(
      _fbb,
      type,
      color,
      limiting_structure_id__);
}

}  // namespace LaneBoundary_

struct LaneBoundary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LaneBoundaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BOUNDARY_LINE = 6,
    VT_CLASSIFICATION = 8,
    VT_SOURCE_REFERENCE = 10,
    VT_COLOR_DESCRIPTION = 12
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>> *boundary_line() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>> *>(VT_BOUNDARY_LINE);
  }
  const osi3::LaneBoundary_::Classification *classification() const {
    return GetPointer<const osi3::LaneBoundary_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::ColorDescription *color_description() const {
    return GetPointer<const osi3::ColorDescription *>(VT_COLOR_DESCRIPTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BOUNDARY_LINE) &&
           verifier.VerifyVector(boundary_line()) &&
           verifier.VerifyVectorOfTables(boundary_line()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_COLOR_DESCRIPTION) &&
           verifier.VerifyTable(color_description()) &&
           verifier.EndTable();
  }
};

struct LaneBoundaryBuilder {
  typedef LaneBoundary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(LaneBoundary::VT_ID, id);
  }
  void add_boundary_line(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>>> boundary_line) {
    fbb_.AddOffset(LaneBoundary::VT_BOUNDARY_LINE, boundary_line);
  }
  void add_classification(::flatbuffers::Offset<osi3::LaneBoundary_::Classification> classification) {
    fbb_.AddOffset(LaneBoundary::VT_CLASSIFICATION, classification);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(LaneBoundary::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_color_description(::flatbuffers::Offset<osi3::ColorDescription> color_description) {
    fbb_.AddOffset(LaneBoundary::VT_COLOR_DESCRIPTION, color_description);
  }
  explicit LaneBoundaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LaneBoundary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LaneBoundary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LaneBoundary> CreateLaneBoundary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>>> boundary_line = 0,
    ::flatbuffers::Offset<osi3::LaneBoundary_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  LaneBoundaryBuilder builder_(_fbb);
  builder_.add_color_description(color_description);
  builder_.add_source_reference(source_reference);
  builder_.add_classification(classification);
  builder_.add_boundary_line(boundary_line);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LaneBoundary> CreateLaneBoundaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    const std::vector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>> *boundary_line = nullptr,
    ::flatbuffers::Offset<osi3::LaneBoundary_::Classification> classification = 0,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  auto boundary_line__ = boundary_line ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LaneBoundary_::BoundaryPoint>>(*boundary_line) : 0;
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateLaneBoundary(
      _fbb,
      id,
      boundary_line__,
      classification,
      source_reference__,
      color_description);
}

namespace Lane_ {
namespace Classification_ {

}  // namespace Classification_

}  // namespace Lane_

namespace LaneBoundary_ {

}  // namespace LaneBoundary_

}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSILANE_OSI3_H_
