// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIROADMARKING_OSI3_H_
#define FLATBUFFERS_GENERATED_OSIROADMARKING_OSI3_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"
#include "osi_trafficsign_generated.h"

namespace osi3 {
namespace RoadMarking_ {

struct Classification;
struct ClassificationBuilder;

}  // namespace RoadMarking_

struct RoadMarking;
struct RoadMarkingBuilder;

namespace RoadMarking_ {
namespace Classification_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_PAINTED_TRAFFIC_SIGN = 2,
  Type_TYPE_SYMBOLIC_TRAFFIC_SIGN = 3,
  Type_TYPE_TEXTUAL_TRAFFIC_SIGN = 4,
  Type_TYPE_GENERIC_SYMBOL = 5,
  Type_TYPE_GENERIC_LINE = 6,
  Type_TYPE_GENERIC_TEXT = 7,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_GENERIC_TEXT
};

inline const Type (&EnumValuesType())[8] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_PAINTED_TRAFFIC_SIGN,
    Type_TYPE_SYMBOLIC_TRAFFIC_SIGN,
    Type_TYPE_TEXTUAL_TRAFFIC_SIGN,
    Type_TYPE_GENERIC_SYMBOL,
    Type_TYPE_GENERIC_LINE,
    Type_TYPE_GENERIC_TEXT
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[9] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_PAINTED_TRAFFIC_SIGN",
    "TYPE_SYMBOLIC_TRAFFIC_SIGN",
    "TYPE_TEXTUAL_TRAFFIC_SIGN",
    "TYPE_GENERIC_SYMBOL",
    "TYPE_GENERIC_LINE",
    "TYPE_GENERIC_TEXT",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_GENERIC_TEXT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

enum Color : int32_t {
  Color_COLOR_UNKNOWN = 0,
  Color_COLOR_OTHER = 1,
  Color_COLOR_WHITE = 2,
  Color_COLOR_YELLOW = 3,
  Color_COLOR_BLUE = 5,
  Color_COLOR_RED = 6,
  Color_COLOR_GREEN = 7,
  Color_COLOR_VIOLET = 8,
  Color_COLOR_ORANGE = 9,
  Color_MIN = Color_COLOR_UNKNOWN,
  Color_MAX = Color_COLOR_ORANGE
};

inline const Color (&EnumValuesColor())[9] {
  static const Color values[] = {
    Color_COLOR_UNKNOWN,
    Color_COLOR_OTHER,
    Color_COLOR_WHITE,
    Color_COLOR_YELLOW,
    Color_COLOR_BLUE,
    Color_COLOR_RED,
    Color_COLOR_GREEN,
    Color_COLOR_VIOLET,
    Color_COLOR_ORANGE
  };
  return values;
}

inline const char * const *EnumNamesColor() {
  static const char * const names[11] = {
    "COLOR_UNKNOWN",
    "COLOR_OTHER",
    "COLOR_WHITE",
    "COLOR_YELLOW",
    "",
    "COLOR_BLUE",
    "COLOR_RED",
    "COLOR_GREEN",
    "COLOR_VIOLET",
    "COLOR_ORANGE",
    nullptr
  };
  return names;
}

inline const char *EnumNameColor(Color e) {
  if (::flatbuffers::IsOutRange(e, Color_COLOR_UNKNOWN, Color_COLOR_ORANGE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColor()[index];
}

}  // namespace Classification_

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_TRAFFIC_MAIN_SIGN_TYPE = 6,
    VT_MONOCHROME_COLOR = 8,
    VT_VALUE = 10,
    VT_VALUE_TEXT = 12,
    VT_ASSIGNED_LANE_ID = 14,
    VT_IS_OUT_OF_SERVICE = 16,
    VT_COUNTRY = 18,
    VT_COUNTRY_REVISION = 20,
    VT_CODE = 22,
    VT_SUB_CODE = 24,
    VT_LOGICAL_LANE_ASSIGNMENT = 26
  };
  osi3::RoadMarking_::Classification_::Type type() const {
    return static_cast<osi3::RoadMarking_::Classification_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  osi3::TrafficSign_::MainSign_::Classification_::Type traffic_main_sign_type() const {
    return static_cast<osi3::TrafficSign_::MainSign_::Classification_::Type>(GetField<int32_t>(VT_TRAFFIC_MAIN_SIGN_TYPE, 0));
  }
  osi3::RoadMarking_::Classification_::Color monochrome_color() const {
    return static_cast<osi3::RoadMarking_::Classification_::Color>(GetField<int32_t>(VT_MONOCHROME_COLOR, 0));
  }
  const osi3::TrafficSignValue *value() const {
    return GetPointer<const osi3::TrafficSignValue *>(VT_VALUE);
  }
  const ::flatbuffers::String *value_text() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE_TEXT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_ASSIGNED_LANE_ID);
  }
  bool is_out_of_service() const {
    return GetField<uint8_t>(VT_IS_OUT_OF_SERVICE, 0) != 0;
  }
  const ::flatbuffers::String *country() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY);
  }
  const ::flatbuffers::String *country_revision() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COUNTRY_REVISION);
  }
  const ::flatbuffers::String *code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CODE);
  }
  const ::flatbuffers::String *sub_code() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUB_CODE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *>(VT_LOGICAL_LANE_ASSIGNMENT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_TRAFFIC_MAIN_SIGN_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_MONOCHROME_COLOR, 4) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyTable(value()) &&
           VerifyOffset(verifier, VT_VALUE_TEXT) &&
           verifier.VerifyString(value_text()) &&
           VerifyOffset(verifier, VT_ASSIGNED_LANE_ID) &&
           verifier.VerifyVector(assigned_lane_id()) &&
           verifier.VerifyVectorOfTables(assigned_lane_id()) &&
           VerifyField<uint8_t>(verifier, VT_IS_OUT_OF_SERVICE, 1) &&
           VerifyOffset(verifier, VT_COUNTRY) &&
           verifier.VerifyString(country()) &&
           VerifyOffset(verifier, VT_COUNTRY_REVISION) &&
           verifier.VerifyString(country_revision()) &&
           VerifyOffset(verifier, VT_CODE) &&
           verifier.VerifyString(code()) &&
           VerifyOffset(verifier, VT_SUB_CODE) &&
           verifier.VerifyString(sub_code()) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE_ASSIGNMENT) &&
           verifier.VerifyVector(logical_lane_assignment()) &&
           verifier.VerifyVectorOfTables(logical_lane_assignment()) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::RoadMarking_::Classification_::Type type) {
    fbb_.AddElement<int32_t>(Classification::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_traffic_main_sign_type(osi3::TrafficSign_::MainSign_::Classification_::Type traffic_main_sign_type) {
    fbb_.AddElement<int32_t>(Classification::VT_TRAFFIC_MAIN_SIGN_TYPE, static_cast<int32_t>(traffic_main_sign_type), 0);
  }
  void add_monochrome_color(osi3::RoadMarking_::Classification_::Color monochrome_color) {
    fbb_.AddElement<int32_t>(Classification::VT_MONOCHROME_COLOR, static_cast<int32_t>(monochrome_color), 0);
  }
  void add_value(::flatbuffers::Offset<osi3::TrafficSignValue> value) {
    fbb_.AddOffset(Classification::VT_VALUE, value);
  }
  void add_value_text(::flatbuffers::Offset<::flatbuffers::String> value_text) {
    fbb_.AddOffset(Classification::VT_VALUE_TEXT, value_text);
  }
  void add_assigned_lane_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id) {
    fbb_.AddOffset(Classification::VT_ASSIGNED_LANE_ID, assigned_lane_id);
  }
  void add_is_out_of_service(bool is_out_of_service) {
    fbb_.AddElement<uint8_t>(Classification::VT_IS_OUT_OF_SERVICE, static_cast<uint8_t>(is_out_of_service), 0);
  }
  void add_country(::flatbuffers::Offset<::flatbuffers::String> country) {
    fbb_.AddOffset(Classification::VT_COUNTRY, country);
  }
  void add_country_revision(::flatbuffers::Offset<::flatbuffers::String> country_revision) {
    fbb_.AddOffset(Classification::VT_COUNTRY_REVISION, country_revision);
  }
  void add_code(::flatbuffers::Offset<::flatbuffers::String> code) {
    fbb_.AddOffset(Classification::VT_CODE, code);
  }
  void add_sub_code(::flatbuffers::Offset<::flatbuffers::String> sub_code) {
    fbb_.AddOffset(Classification::VT_SUB_CODE, sub_code);
  }
  void add_logical_lane_assignment(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment) {
    fbb_.AddOffset(Classification::VT_LOGICAL_LANE_ASSIGNMENT, logical_lane_assignment);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::RoadMarking_::Classification_::Type type = osi3::RoadMarking_::Classification_::Type_TYPE_UNKNOWN,
    osi3::TrafficSign_::MainSign_::Classification_::Type traffic_main_sign_type = osi3::TrafficSign_::MainSign_::Classification_::Type_TYPE_UNKNOWN,
    osi3::RoadMarking_::Classification_::Color monochrome_color = osi3::RoadMarking_::Classification_::Color_COLOR_UNKNOWN,
    ::flatbuffers::Offset<osi3::TrafficSignValue> value = 0,
    ::flatbuffers::Offset<::flatbuffers::String> value_text = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> assigned_lane_id = 0,
    bool is_out_of_service = false,
    ::flatbuffers::Offset<::flatbuffers::String> country = 0,
    ::flatbuffers::Offset<::flatbuffers::String> country_revision = 0,
    ::flatbuffers::Offset<::flatbuffers::String> code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> sub_code = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>> logical_lane_assignment = 0) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_logical_lane_assignment(logical_lane_assignment);
  builder_.add_sub_code(sub_code);
  builder_.add_code(code);
  builder_.add_country_revision(country_revision);
  builder_.add_country(country);
  builder_.add_assigned_lane_id(assigned_lane_id);
  builder_.add_value_text(value_text);
  builder_.add_value(value);
  builder_.add_monochrome_color(monochrome_color);
  builder_.add_traffic_main_sign_type(traffic_main_sign_type);
  builder_.add_type(type);
  builder_.add_is_out_of_service(is_out_of_service);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Classification> CreateClassificationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::RoadMarking_::Classification_::Type type = osi3::RoadMarking_::Classification_::Type_TYPE_UNKNOWN,
    osi3::TrafficSign_::MainSign_::Classification_::Type traffic_main_sign_type = osi3::TrafficSign_::MainSign_::Classification_::Type_TYPE_UNKNOWN,
    osi3::RoadMarking_::Classification_::Color monochrome_color = osi3::RoadMarking_::Classification_::Color_COLOR_UNKNOWN,
    ::flatbuffers::Offset<osi3::TrafficSignValue> value = 0,
    const char *value_text = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *assigned_lane_id = nullptr,
    bool is_out_of_service = false,
    const char *country = nullptr,
    const char *country_revision = nullptr,
    const char *code = nullptr,
    const char *sub_code = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>> *logical_lane_assignment = nullptr) {
  auto value_text__ = value_text ? _fbb.CreateString(value_text) : 0;
  auto assigned_lane_id__ = assigned_lane_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*assigned_lane_id) : 0;
  auto country__ = country ? _fbb.CreateString(country) : 0;
  auto country_revision__ = country_revision ? _fbb.CreateString(country_revision) : 0;
  auto code__ = code ? _fbb.CreateString(code) : 0;
  auto sub_code__ = sub_code ? _fbb.CreateString(sub_code) : 0;
  auto logical_lane_assignment__ = logical_lane_assignment ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneAssignment>>(*logical_lane_assignment) : 0;
  return osi3::RoadMarking_::CreateClassification(
      _fbb,
      type,
      traffic_main_sign_type,
      monochrome_color,
      value,
      value_text__,
      assigned_lane_id__,
      is_out_of_service,
      country__,
      country_revision__,
      code__,
      sub_code__,
      logical_lane_assignment__);
}

}  // namespace RoadMarking_

struct RoadMarking FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RoadMarkingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BASE = 6,
    VT_CLASSIFICATION = 8,
    VT_SOURCE_REFERENCE = 10,
    VT_COLOR_DESCRIPTION = 12
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::BaseStationary *base() const {
    return GetPointer<const osi3::BaseStationary *>(VT_BASE);
  }
  const osi3::RoadMarking_::Classification *classification() const {
    return GetPointer<const osi3::RoadMarking_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const osi3::ColorDescription *color_description() const {
    return GetPointer<const osi3::ColorDescription *>(VT_COLOR_DESCRIPTION);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BASE) &&
           verifier.VerifyTable(base()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_COLOR_DESCRIPTION) &&
           verifier.VerifyTable(color_description()) &&
           verifier.EndTable();
  }
};

struct RoadMarkingBuilder {
  typedef RoadMarking Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(RoadMarking::VT_ID, id);
  }
  void add_base(::flatbuffers::Offset<osi3::BaseStationary> base) {
    fbb_.AddOffset(RoadMarking::VT_BASE, base);
  }
  void add_classification(::flatbuffers::Offset<osi3::RoadMarking_::Classification> classification) {
    fbb_.AddOffset(RoadMarking::VT_CLASSIFICATION, classification);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(RoadMarking::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_color_description(::flatbuffers::Offset<osi3::ColorDescription> color_description) {
    fbb_.AddOffset(RoadMarking::VT_COLOR_DESCRIPTION, color_description);
  }
  explicit RoadMarkingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RoadMarking> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RoadMarking>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RoadMarking> CreateRoadMarking(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::RoadMarking_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  RoadMarkingBuilder builder_(_fbb);
  builder_.add_color_description(color_description);
  builder_.add_source_reference(source_reference);
  builder_.add_classification(classification);
  builder_.add_base(base);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RoadMarking> CreateRoadMarkingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::BaseStationary> base = 0,
    ::flatbuffers::Offset<osi3::RoadMarking_::Classification> classification = 0,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    ::flatbuffers::Offset<osi3::ColorDescription> color_description = 0) {
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateRoadMarking(
      _fbb,
      id,
      base,
      classification,
      source_reference__,
      color_description);
}

namespace RoadMarking_ {

}  // namespace RoadMarking_

}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIROADMARKING_OSI3_H_
