include "osi_common.fbs";

namespace osi3.TrafficLight_.Classification_;
enum Color : int {
    COLOR_UNKNOWN = 0,
    COLOR_OTHER = 1,
    COLOR_RED = 2,
    COLOR_YELLOW = 3,
    COLOR_GREEN = 4,
    COLOR_BLUE = 5,
    COLOR_WHITE = 6,
}

namespace osi3.TrafficLight_.Classification_;
enum Icon : int {
    ICON_UNKNOWN = 0,
    ICON_OTHER = 1,
    ICON_NONE = 2,
    ICON_ARROW_STRAIGHT_AHEAD = 3,
    ICON_ARROW_LEFT = 4,
    ICON_ARROW_DIAG_LEFT = 5,
    ICON_ARROW_STRAIGHT_AHEAD_LEFT = 6,
    ICON_ARROW_RIGHT = 7,
    ICON_ARROW_DIAG_RIGHT = 8,
    ICON_ARROW_STRAIGHT_AHEAD_RIGHT = 9,
    ICON_ARROW_LEFT_RIGHT = 10,
    ICON_ARROW_DOWN = 11,
    ICON_ARROW_DOWN_LEFT = 12,
    ICON_ARROW_DOWN_RIGHT = 13,
    ICON_ARROW_CROSS = 14,
    ICON_PEDESTRIAN = 15,
    ICON_WALK = 16,
    ICON_DONT_WALK = 17,
    ICON_BICYCLE = 18,
    ICON_PEDESTRIAN_AND_BICYCLE = 19,
    ICON_COUNTDOWN_SECONDS = 20,
    ICON_COUNTDOWN_PERCENT = 21,
    ICON_TRAM = 22,
    ICON_BUS = 23,
    ICON_BUS_AND_TRAM = 24,
}

namespace osi3.TrafficLight_.Classification_;
enum Mode : int {
    MODE_UNKNOWN = 0,
    MODE_OTHER = 1,
    MODE_OFF = 2,
    MODE_CONSTANT = 3,
    MODE_FLASHING = 4,
    MODE_COUNTING = 5,
}

namespace osi3.TrafficLight_;
table Classification {
  color:osi3.TrafficLight_.Classification_.Color;
  icon:osi3.TrafficLight_.Classification_.Icon;
  mode:osi3.TrafficLight_.Classification_.Mode;
  counter:double;
  assigned_lane_id:[osi3.Identifier];
  is_out_of_service:bool;
  logical_lane_assignment:[osi3.LogicalLaneAssignment];
}

namespace osi3;
table TrafficLight {
  id:osi3.Identifier;
  base:osi3.BaseStationary;
  classification:osi3.TrafficLight_.Classification;
  model_reference:string;
  source_reference:[osi3.ExternalReference];
  color_description:osi3.ColorDescription;
}
