// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSILOGICALLANE_OSI3_LOGICALLANE__TRAFFICRULE__H_
#define FLATBUFFERS_GENERATED_OSILOGICALLANE_OSI3_LOGICALLANE__TRAFFICRULE__H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"
#include "osi_object_generated.h"
#include "osi_trafficsign_generated.h"

namespace osi3 {

struct LogicalLaneBoundary;
struct LogicalLaneBoundaryBuilder;

namespace LogicalLaneBoundary_ {

struct LogicalBoundaryPoint;
struct LogicalBoundaryPointBuilder;

}  // namespace LogicalLaneBoundary_

struct LogicalLane;
struct LogicalLaneBuilder;

namespace LogicalLane_ {

struct PhysicalLaneReference;
struct PhysicalLaneReferenceBuilder;

struct LaneConnection;
struct LaneConnectionBuilder;

struct LaneRelation;
struct LaneRelationBuilder;

struct TrafficRule;
struct TrafficRuleBuilder;

namespace TrafficRule_ {

struct TrafficRuleValidity;
struct TrafficRuleValidityBuilder;

namespace TrafficRuleValidity_ {

struct TypeValidity;
struct TypeValidityBuilder;

}  // namespace TrafficRuleValidity_

struct SpeedLimit;
struct SpeedLimitBuilder;

}  // namespace TrafficRule_
}  // namespace LogicalLane_

namespace LogicalLaneBoundary_ {

enum PassingRule : int32_t {
  PassingRule_PASSING_RULE_UNKNOWN = 0,
  PassingRule_PASSING_RULE_OTHER = 1,
  PassingRule_PASSING_RULE_NONE_ALLOWED = 2,
  PassingRule_PASSING_RULE_INCREASING_T = 3,
  PassingRule_PASSING_RULE_DECREASING_T = 4,
  PassingRule_PASSING_RULE_BOTH_ALLOWED = 5,
  PassingRule_MIN = PassingRule_PASSING_RULE_UNKNOWN,
  PassingRule_MAX = PassingRule_PASSING_RULE_BOTH_ALLOWED
};

inline const PassingRule (&EnumValuesPassingRule())[6] {
  static const PassingRule values[] = {
    PassingRule_PASSING_RULE_UNKNOWN,
    PassingRule_PASSING_RULE_OTHER,
    PassingRule_PASSING_RULE_NONE_ALLOWED,
    PassingRule_PASSING_RULE_INCREASING_T,
    PassingRule_PASSING_RULE_DECREASING_T,
    PassingRule_PASSING_RULE_BOTH_ALLOWED
  };
  return values;
}

inline const char * const *EnumNamesPassingRule() {
  static const char * const names[7] = {
    "PASSING_RULE_UNKNOWN",
    "PASSING_RULE_OTHER",
    "PASSING_RULE_NONE_ALLOWED",
    "PASSING_RULE_INCREASING_T",
    "PASSING_RULE_DECREASING_T",
    "PASSING_RULE_BOTH_ALLOWED",
    nullptr
  };
  return names;
}

inline const char *EnumNamePassingRule(PassingRule e) {
  if (::flatbuffers::IsOutRange(e, PassingRule_PASSING_RULE_UNKNOWN, PassingRule_PASSING_RULE_BOTH_ALLOWED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPassingRule()[index];
}

}  // namespace LogicalLaneBoundary_

namespace LogicalLane_ {

enum Type : int32_t {
  Type_TYPE_UNKNOWN = 0,
  Type_TYPE_OTHER = 1,
  Type_TYPE_NORMAL = 2,
  Type_TYPE_BIKING = 3,
  Type_TYPE_SIDEWALK = 4,
  Type_TYPE_PARKING = 5,
  Type_TYPE_STOP = 6,
  Type_TYPE_RESTRICTED = 7,
  Type_TYPE_BORDER = 8,
  Type_TYPE_SHOULDER = 9,
  Type_TYPE_EXIT = 10,
  Type_TYPE_ENTRY = 11,
  Type_TYPE_ONRAMP = 12,
  Type_TYPE_OFFRAMP = 13,
  Type_TYPE_CONNECTINGRAMP = 14,
  Type_TYPE_MEDIAN = 15,
  Type_TYPE_CURB = 16,
  Type_TYPE_RAIL = 17,
  Type_TYPE_TRAM = 18,
  Type_MIN = Type_TYPE_UNKNOWN,
  Type_MAX = Type_TYPE_TRAM
};

inline const Type (&EnumValuesType())[19] {
  static const Type values[] = {
    Type_TYPE_UNKNOWN,
    Type_TYPE_OTHER,
    Type_TYPE_NORMAL,
    Type_TYPE_BIKING,
    Type_TYPE_SIDEWALK,
    Type_TYPE_PARKING,
    Type_TYPE_STOP,
    Type_TYPE_RESTRICTED,
    Type_TYPE_BORDER,
    Type_TYPE_SHOULDER,
    Type_TYPE_EXIT,
    Type_TYPE_ENTRY,
    Type_TYPE_ONRAMP,
    Type_TYPE_OFFRAMP,
    Type_TYPE_CONNECTINGRAMP,
    Type_TYPE_MEDIAN,
    Type_TYPE_CURB,
    Type_TYPE_RAIL,
    Type_TYPE_TRAM
  };
  return values;
}

inline const char * const *EnumNamesType() {
  static const char * const names[20] = {
    "TYPE_UNKNOWN",
    "TYPE_OTHER",
    "TYPE_NORMAL",
    "TYPE_BIKING",
    "TYPE_SIDEWALK",
    "TYPE_PARKING",
    "TYPE_STOP",
    "TYPE_RESTRICTED",
    "TYPE_BORDER",
    "TYPE_SHOULDER",
    "TYPE_EXIT",
    "TYPE_ENTRY",
    "TYPE_ONRAMP",
    "TYPE_OFFRAMP",
    "TYPE_CONNECTINGRAMP",
    "TYPE_MEDIAN",
    "TYPE_CURB",
    "TYPE_RAIL",
    "TYPE_TRAM",
    nullptr
  };
  return names;
}

inline const char *EnumNameType(Type e) {
  if (::flatbuffers::IsOutRange(e, Type_TYPE_UNKNOWN, Type_TYPE_TRAM)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesType()[index];
}

enum MoveDirection : int32_t {
  MoveDirection_MOVE_DIRECTION_UNKNOWN = 0,
  MoveDirection_MOVE_DIRECTION_OTHER = 1,
  MoveDirection_MOVE_DIRECTION_INCREASING_S = 2,
  MoveDirection_MOVE_DIRECTION_DECREASING_S = 3,
  MoveDirection_MOVE_DIRECTION_BOTH_ALLOWED = 4,
  MoveDirection_MIN = MoveDirection_MOVE_DIRECTION_UNKNOWN,
  MoveDirection_MAX = MoveDirection_MOVE_DIRECTION_BOTH_ALLOWED
};

inline const MoveDirection (&EnumValuesMoveDirection())[5] {
  static const MoveDirection values[] = {
    MoveDirection_MOVE_DIRECTION_UNKNOWN,
    MoveDirection_MOVE_DIRECTION_OTHER,
    MoveDirection_MOVE_DIRECTION_INCREASING_S,
    MoveDirection_MOVE_DIRECTION_DECREASING_S,
    MoveDirection_MOVE_DIRECTION_BOTH_ALLOWED
  };
  return values;
}

inline const char * const *EnumNamesMoveDirection() {
  static const char * const names[6] = {
    "MOVE_DIRECTION_UNKNOWN",
    "MOVE_DIRECTION_OTHER",
    "MOVE_DIRECTION_INCREASING_S",
    "MOVE_DIRECTION_DECREASING_S",
    "MOVE_DIRECTION_BOTH_ALLOWED",
    nullptr
  };
  return names;
}

inline const char *EnumNameMoveDirection(MoveDirection e) {
  if (::flatbuffers::IsOutRange(e, MoveDirection_MOVE_DIRECTION_UNKNOWN, MoveDirection_MOVE_DIRECTION_BOTH_ALLOWED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMoveDirection()[index];
}

namespace TrafficRule_ {

enum TrafficRuleType : int32_t {
  TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT = 0,
  TrafficRuleType_MIN = TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT,
  TrafficRuleType_MAX = TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT
};

inline const TrafficRuleType (&EnumValuesTrafficRuleType())[1] {
  static const TrafficRuleType values[] = {
    TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT
  };
  return values;
}

inline const char * const *EnumNamesTrafficRuleType() {
  static const char * const names[2] = {
    "TRAFFIC_RULE_TYPE_SPEED_LIMIT",
    nullptr
  };
  return names;
}

inline const char *EnumNameTrafficRuleType(TrafficRuleType e) {
  if (::flatbuffers::IsOutRange(e, TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT, TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTrafficRuleType()[index];
}

}  // namespace TrafficRule_
}  // namespace LogicalLane_

struct LogicalLaneBoundary FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogicalLaneBoundaryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_BOUNDARY_LINE = 6,
    VT_REFERENCE_LINE_ID = 8,
    VT_PHYSICAL_BOUNDARY_ID = 10,
    VT_PASSING_RULE = 12,
    VT_SOURCE_REFERENCE = 14
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>> *boundary_line() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>> *>(VT_BOUNDARY_LINE);
  }
  const osi3::Identifier *reference_line_id() const {
    return GetPointer<const osi3::Identifier *>(VT_REFERENCE_LINE_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *physical_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_PHYSICAL_BOUNDARY_ID);
  }
  osi3::LogicalLaneBoundary_::PassingRule passing_rule() const {
    return static_cast<osi3::LogicalLaneBoundary_::PassingRule>(GetField<int32_t>(VT_PASSING_RULE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_BOUNDARY_LINE) &&
           verifier.VerifyVector(boundary_line()) &&
           verifier.VerifyVectorOfTables(boundary_line()) &&
           VerifyOffset(verifier, VT_REFERENCE_LINE_ID) &&
           verifier.VerifyTable(reference_line_id()) &&
           VerifyOffset(verifier, VT_PHYSICAL_BOUNDARY_ID) &&
           verifier.VerifyVector(physical_boundary_id()) &&
           verifier.VerifyVectorOfTables(physical_boundary_id()) &&
           VerifyField<int32_t>(verifier, VT_PASSING_RULE, 4) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           verifier.EndTable();
  }
};

struct LogicalLaneBoundaryBuilder {
  typedef LogicalLaneBoundary Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(LogicalLaneBoundary::VT_ID, id);
  }
  void add_boundary_line(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>>> boundary_line) {
    fbb_.AddOffset(LogicalLaneBoundary::VT_BOUNDARY_LINE, boundary_line);
  }
  void add_reference_line_id(::flatbuffers::Offset<osi3::Identifier> reference_line_id) {
    fbb_.AddOffset(LogicalLaneBoundary::VT_REFERENCE_LINE_ID, reference_line_id);
  }
  void add_physical_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> physical_boundary_id) {
    fbb_.AddOffset(LogicalLaneBoundary::VT_PHYSICAL_BOUNDARY_ID, physical_boundary_id);
  }
  void add_passing_rule(osi3::LogicalLaneBoundary_::PassingRule passing_rule) {
    fbb_.AddElement<int32_t>(LogicalLaneBoundary::VT_PASSING_RULE, static_cast<int32_t>(passing_rule), 0);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(LogicalLaneBoundary::VT_SOURCE_REFERENCE, source_reference);
  }
  explicit LogicalLaneBoundaryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LogicalLaneBoundary> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LogicalLaneBoundary>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LogicalLaneBoundary> CreateLogicalLaneBoundary(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>>> boundary_line = 0,
    ::flatbuffers::Offset<osi3::Identifier> reference_line_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> physical_boundary_id = 0,
    osi3::LogicalLaneBoundary_::PassingRule passing_rule = osi3::LogicalLaneBoundary_::PassingRule_PASSING_RULE_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0) {
  LogicalLaneBoundaryBuilder builder_(_fbb);
  builder_.add_source_reference(source_reference);
  builder_.add_passing_rule(passing_rule);
  builder_.add_physical_boundary_id(physical_boundary_id);
  builder_.add_reference_line_id(reference_line_id);
  builder_.add_boundary_line(boundary_line);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LogicalLaneBoundary> CreateLogicalLaneBoundaryDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>> *boundary_line = nullptr,
    ::flatbuffers::Offset<osi3::Identifier> reference_line_id = 0,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *physical_boundary_id = nullptr,
    osi3::LogicalLaneBoundary_::PassingRule passing_rule = osi3::LogicalLaneBoundary_::PassingRule_PASSING_RULE_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr) {
  auto boundary_line__ = boundary_line ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneBoundary_::LogicalBoundaryPoint>>(*boundary_line) : 0;
  auto physical_boundary_id__ = physical_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*physical_boundary_id) : 0;
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateLogicalLaneBoundary(
      _fbb,
      id,
      boundary_line__,
      reference_line_id,
      physical_boundary_id__,
      passing_rule,
      source_reference__);
}

namespace LogicalLaneBoundary_ {

struct LogicalBoundaryPoint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogicalBoundaryPointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_S_POSITION = 6,
    VT_T_POSITION = 8
  };
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  double s_position() const {
    return GetField<double>(VT_S_POSITION, 0.0);
  }
  double t_position() const {
    return GetField<double>(VT_T_POSITION, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<double>(verifier, VT_S_POSITION, 8) &&
           VerifyField<double>(verifier, VT_T_POSITION, 8) &&
           verifier.EndTable();
  }
};

struct LogicalBoundaryPointBuilder {
  typedef LogicalBoundaryPoint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(LogicalBoundaryPoint::VT_POSITION, position);
  }
  void add_s_position(double s_position) {
    fbb_.AddElement<double>(LogicalBoundaryPoint::VT_S_POSITION, s_position, 0.0);
  }
  void add_t_position(double t_position) {
    fbb_.AddElement<double>(LogicalBoundaryPoint::VT_T_POSITION, t_position, 0.0);
  }
  explicit LogicalBoundaryPointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LogicalBoundaryPoint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LogicalBoundaryPoint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LogicalBoundaryPoint> CreateLogicalBoundaryPoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    double s_position = 0.0,
    double t_position = 0.0) {
  LogicalBoundaryPointBuilder builder_(_fbb);
  builder_.add_t_position(t_position);
  builder_.add_s_position(s_position);
  builder_.add_position(position);
  return builder_.Finish();
}

}  // namespace LogicalLaneBoundary_

struct LogicalLane FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LogicalLaneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_SOURCE_REFERENCE = 8,
    VT_PHYSICAL_LANE_REFERENCE = 10,
    VT_REFERENCE_LINE_ID = 12,
    VT_START_S = 14,
    VT_END_S = 16,
    VT_MOVE_DIRECTION = 18,
    VT_RIGHT_ADJACENT_LANE = 20,
    VT_LEFT_ADJACENT_LANE = 22,
    VT_OVERLAPPING_LANE = 24,
    VT_RIGHT_BOUNDARY_ID = 26,
    VT_LEFT_BOUNDARY_ID = 28,
    VT_PREDECESSOR_LANE = 30,
    VT_SUCCESSOR_LANE = 32,
    VT_STREET_NAME = 34,
    VT_TRAFFIC_RULE = 36
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  osi3::LogicalLane_::Type type() const {
    return static_cast<osi3::LogicalLane_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>> *physical_lane_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>> *>(VT_PHYSICAL_LANE_REFERENCE);
  }
  const osi3::Identifier *reference_line_id() const {
    return GetPointer<const osi3::Identifier *>(VT_REFERENCE_LINE_ID);
  }
  double start_s() const {
    return GetField<double>(VT_START_S, 0.0);
  }
  double end_s() const {
    return GetField<double>(VT_END_S, 0.0);
  }
  osi3::LogicalLane_::MoveDirection move_direction() const {
    return static_cast<osi3::LogicalLane_::MoveDirection>(GetField<int32_t>(VT_MOVE_DIRECTION, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *right_adjacent_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *>(VT_RIGHT_ADJACENT_LANE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *left_adjacent_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *>(VT_LEFT_ADJACENT_LANE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *overlapping_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *>(VT_OVERLAPPING_LANE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *right_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_RIGHT_BOUNDARY_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *left_boundary_id() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>> *>(VT_LEFT_BOUNDARY_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *predecessor_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *>(VT_PREDECESSOR_LANE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *successor_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *>(VT_SUCCESSOR_LANE);
  }
  const ::flatbuffers::String *street_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_STREET_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>> *traffic_rule() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>> *>(VT_TRAFFIC_RULE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           VerifyOffset(verifier, VT_PHYSICAL_LANE_REFERENCE) &&
           verifier.VerifyVector(physical_lane_reference()) &&
           verifier.VerifyVectorOfTables(physical_lane_reference()) &&
           VerifyOffset(verifier, VT_REFERENCE_LINE_ID) &&
           verifier.VerifyTable(reference_line_id()) &&
           VerifyField<double>(verifier, VT_START_S, 8) &&
           VerifyField<double>(verifier, VT_END_S, 8) &&
           VerifyField<int32_t>(verifier, VT_MOVE_DIRECTION, 4) &&
           VerifyOffset(verifier, VT_RIGHT_ADJACENT_LANE) &&
           verifier.VerifyVector(right_adjacent_lane()) &&
           verifier.VerifyVectorOfTables(right_adjacent_lane()) &&
           VerifyOffset(verifier, VT_LEFT_ADJACENT_LANE) &&
           verifier.VerifyVector(left_adjacent_lane()) &&
           verifier.VerifyVectorOfTables(left_adjacent_lane()) &&
           VerifyOffset(verifier, VT_OVERLAPPING_LANE) &&
           verifier.VerifyVector(overlapping_lane()) &&
           verifier.VerifyVectorOfTables(overlapping_lane()) &&
           VerifyOffset(verifier, VT_RIGHT_BOUNDARY_ID) &&
           verifier.VerifyVector(right_boundary_id()) &&
           verifier.VerifyVectorOfTables(right_boundary_id()) &&
           VerifyOffset(verifier, VT_LEFT_BOUNDARY_ID) &&
           verifier.VerifyVector(left_boundary_id()) &&
           verifier.VerifyVectorOfTables(left_boundary_id()) &&
           VerifyOffset(verifier, VT_PREDECESSOR_LANE) &&
           verifier.VerifyVector(predecessor_lane()) &&
           verifier.VerifyVectorOfTables(predecessor_lane()) &&
           VerifyOffset(verifier, VT_SUCCESSOR_LANE) &&
           verifier.VerifyVector(successor_lane()) &&
           verifier.VerifyVectorOfTables(successor_lane()) &&
           VerifyOffset(verifier, VT_STREET_NAME) &&
           verifier.VerifyString(street_name()) &&
           VerifyOffset(verifier, VT_TRAFFIC_RULE) &&
           verifier.VerifyVector(traffic_rule()) &&
           verifier.VerifyVectorOfTables(traffic_rule()) &&
           verifier.EndTable();
  }
};

struct LogicalLaneBuilder {
  typedef LogicalLane Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(LogicalLane::VT_ID, id);
  }
  void add_type(osi3::LogicalLane_::Type type) {
    fbb_.AddElement<int32_t>(LogicalLane::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(LogicalLane::VT_SOURCE_REFERENCE, source_reference);
  }
  void add_physical_lane_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>>> physical_lane_reference) {
    fbb_.AddOffset(LogicalLane::VT_PHYSICAL_LANE_REFERENCE, physical_lane_reference);
  }
  void add_reference_line_id(::flatbuffers::Offset<osi3::Identifier> reference_line_id) {
    fbb_.AddOffset(LogicalLane::VT_REFERENCE_LINE_ID, reference_line_id);
  }
  void add_start_s(double start_s) {
    fbb_.AddElement<double>(LogicalLane::VT_START_S, start_s, 0.0);
  }
  void add_end_s(double end_s) {
    fbb_.AddElement<double>(LogicalLane::VT_END_S, end_s, 0.0);
  }
  void add_move_direction(osi3::LogicalLane_::MoveDirection move_direction) {
    fbb_.AddElement<int32_t>(LogicalLane::VT_MOVE_DIRECTION, static_cast<int32_t>(move_direction), 0);
  }
  void add_right_adjacent_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> right_adjacent_lane) {
    fbb_.AddOffset(LogicalLane::VT_RIGHT_ADJACENT_LANE, right_adjacent_lane);
  }
  void add_left_adjacent_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> left_adjacent_lane) {
    fbb_.AddOffset(LogicalLane::VT_LEFT_ADJACENT_LANE, left_adjacent_lane);
  }
  void add_overlapping_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> overlapping_lane) {
    fbb_.AddOffset(LogicalLane::VT_OVERLAPPING_LANE, overlapping_lane);
  }
  void add_right_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_boundary_id) {
    fbb_.AddOffset(LogicalLane::VT_RIGHT_BOUNDARY_ID, right_boundary_id);
  }
  void add_left_boundary_id(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_boundary_id) {
    fbb_.AddOffset(LogicalLane::VT_LEFT_BOUNDARY_ID, left_boundary_id);
  }
  void add_predecessor_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>> predecessor_lane) {
    fbb_.AddOffset(LogicalLane::VT_PREDECESSOR_LANE, predecessor_lane);
  }
  void add_successor_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>> successor_lane) {
    fbb_.AddOffset(LogicalLane::VT_SUCCESSOR_LANE, successor_lane);
  }
  void add_street_name(::flatbuffers::Offset<::flatbuffers::String> street_name) {
    fbb_.AddOffset(LogicalLane::VT_STREET_NAME, street_name);
  }
  void add_traffic_rule(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>>> traffic_rule) {
    fbb_.AddOffset(LogicalLane::VT_TRAFFIC_RULE, traffic_rule);
  }
  explicit LogicalLaneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LogicalLane> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LogicalLane>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LogicalLane> CreateLogicalLane(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    osi3::LogicalLane_::Type type = osi3::LogicalLane_::Type_TYPE_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>>> physical_lane_reference = 0,
    ::flatbuffers::Offset<osi3::Identifier> reference_line_id = 0,
    double start_s = 0.0,
    double end_s = 0.0,
    osi3::LogicalLane_::MoveDirection move_direction = osi3::LogicalLane_::MoveDirection_MOVE_DIRECTION_UNKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> right_adjacent_lane = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> left_adjacent_lane = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>> overlapping_lane = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> right_boundary_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Identifier>>> left_boundary_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>> predecessor_lane = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>> successor_lane = 0,
    ::flatbuffers::Offset<::flatbuffers::String> street_name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>>> traffic_rule = 0) {
  LogicalLaneBuilder builder_(_fbb);
  builder_.add_end_s(end_s);
  builder_.add_start_s(start_s);
  builder_.add_traffic_rule(traffic_rule);
  builder_.add_street_name(street_name);
  builder_.add_successor_lane(successor_lane);
  builder_.add_predecessor_lane(predecessor_lane);
  builder_.add_left_boundary_id(left_boundary_id);
  builder_.add_right_boundary_id(right_boundary_id);
  builder_.add_overlapping_lane(overlapping_lane);
  builder_.add_left_adjacent_lane(left_adjacent_lane);
  builder_.add_right_adjacent_lane(right_adjacent_lane);
  builder_.add_move_direction(move_direction);
  builder_.add_reference_line_id(reference_line_id);
  builder_.add_physical_lane_reference(physical_lane_reference);
  builder_.add_source_reference(source_reference);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LogicalLane> CreateLogicalLaneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    osi3::LogicalLane_::Type type = osi3::LogicalLane_::Type_TYPE_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>> *physical_lane_reference = nullptr,
    ::flatbuffers::Offset<osi3::Identifier> reference_line_id = 0,
    double start_s = 0.0,
    double end_s = 0.0,
    osi3::LogicalLane_::MoveDirection move_direction = osi3::LogicalLane_::MoveDirection_MOVE_DIRECTION_UNKNOWN,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *right_adjacent_lane = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *left_adjacent_lane = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>> *overlapping_lane = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *right_boundary_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Identifier>> *left_boundary_id = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *predecessor_lane = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>> *successor_lane = nullptr,
    const char *street_name = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>> *traffic_rule = nullptr) {
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  auto physical_lane_reference__ = physical_lane_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::PhysicalLaneReference>>(*physical_lane_reference) : 0;
  auto right_adjacent_lane__ = right_adjacent_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>(*right_adjacent_lane) : 0;
  auto left_adjacent_lane__ = left_adjacent_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>(*left_adjacent_lane) : 0;
  auto overlapping_lane__ = overlapping_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::LaneRelation>>(*overlapping_lane) : 0;
  auto right_boundary_id__ = right_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*right_boundary_id) : 0;
  auto left_boundary_id__ = left_boundary_id ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Identifier>>(*left_boundary_id) : 0;
  auto predecessor_lane__ = predecessor_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>(*predecessor_lane) : 0;
  auto successor_lane__ = successor_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::LaneConnection>>(*successor_lane) : 0;
  auto street_name__ = street_name ? _fbb.CreateString(street_name) : 0;
  auto traffic_rule__ = traffic_rule ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule>>(*traffic_rule) : 0;
  return osi3::CreateLogicalLane(
      _fbb,
      id,
      type,
      source_reference__,
      physical_lane_reference__,
      reference_line_id,
      start_s,
      end_s,
      move_direction,
      right_adjacent_lane__,
      left_adjacent_lane__,
      overlapping_lane__,
      right_boundary_id__,
      left_boundary_id__,
      predecessor_lane__,
      successor_lane__,
      street_name__,
      traffic_rule__);
}

namespace LogicalLane_ {

struct PhysicalLaneReference FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PhysicalLaneReferenceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PHYSICAL_LANE_ID = 4,
    VT_START_S = 6,
    VT_END_S = 8
  };
  const osi3::Identifier *physical_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_PHYSICAL_LANE_ID);
  }
  double start_s() const {
    return GetField<double>(VT_START_S, 0.0);
  }
  double end_s() const {
    return GetField<double>(VT_END_S, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PHYSICAL_LANE_ID) &&
           verifier.VerifyTable(physical_lane_id()) &&
           VerifyField<double>(verifier, VT_START_S, 8) &&
           VerifyField<double>(verifier, VT_END_S, 8) &&
           verifier.EndTable();
  }
};

struct PhysicalLaneReferenceBuilder {
  typedef PhysicalLaneReference Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_physical_lane_id(::flatbuffers::Offset<osi3::Identifier> physical_lane_id) {
    fbb_.AddOffset(PhysicalLaneReference::VT_PHYSICAL_LANE_ID, physical_lane_id);
  }
  void add_start_s(double start_s) {
    fbb_.AddElement<double>(PhysicalLaneReference::VT_START_S, start_s, 0.0);
  }
  void add_end_s(double end_s) {
    fbb_.AddElement<double>(PhysicalLaneReference::VT_END_S, end_s, 0.0);
  }
  explicit PhysicalLaneReferenceBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PhysicalLaneReference> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PhysicalLaneReference>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PhysicalLaneReference> CreatePhysicalLaneReference(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> physical_lane_id = 0,
    double start_s = 0.0,
    double end_s = 0.0) {
  PhysicalLaneReferenceBuilder builder_(_fbb);
  builder_.add_end_s(end_s);
  builder_.add_start_s(start_s);
  builder_.add_physical_lane_id(physical_lane_id);
  return builder_.Finish();
}

struct LaneConnection FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LaneConnectionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OTHER_LANE_ID = 4,
    VT_AT_BEGIN_OF_OTHER_LANE = 6
  };
  const osi3::Identifier *other_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_OTHER_LANE_ID);
  }
  bool at_begin_of_other_lane() const {
    return GetField<uint8_t>(VT_AT_BEGIN_OF_OTHER_LANE, 0) != 0;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OTHER_LANE_ID) &&
           verifier.VerifyTable(other_lane_id()) &&
           VerifyField<uint8_t>(verifier, VT_AT_BEGIN_OF_OTHER_LANE, 1) &&
           verifier.EndTable();
  }
};

struct LaneConnectionBuilder {
  typedef LaneConnection Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_other_lane_id(::flatbuffers::Offset<osi3::Identifier> other_lane_id) {
    fbb_.AddOffset(LaneConnection::VT_OTHER_LANE_ID, other_lane_id);
  }
  void add_at_begin_of_other_lane(bool at_begin_of_other_lane) {
    fbb_.AddElement<uint8_t>(LaneConnection::VT_AT_BEGIN_OF_OTHER_LANE, static_cast<uint8_t>(at_begin_of_other_lane), 0);
  }
  explicit LaneConnectionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LaneConnection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LaneConnection>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LaneConnection> CreateLaneConnection(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> other_lane_id = 0,
    bool at_begin_of_other_lane = false) {
  LaneConnectionBuilder builder_(_fbb);
  builder_.add_other_lane_id(other_lane_id);
  builder_.add_at_begin_of_other_lane(at_begin_of_other_lane);
  return builder_.Finish();
}

struct LaneRelation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LaneRelationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OTHER_LANE_ID = 4,
    VT_START_S = 6,
    VT_END_S = 8,
    VT_START_S_OTHER = 10,
    VT_END_S_OTHER = 12
  };
  const osi3::Identifier *other_lane_id() const {
    return GetPointer<const osi3::Identifier *>(VT_OTHER_LANE_ID);
  }
  double start_s() const {
    return GetField<double>(VT_START_S, 0.0);
  }
  double end_s() const {
    return GetField<double>(VT_END_S, 0.0);
  }
  double start_s_other() const {
    return GetField<double>(VT_START_S_OTHER, 0.0);
  }
  double end_s_other() const {
    return GetField<double>(VT_END_S_OTHER, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_OTHER_LANE_ID) &&
           verifier.VerifyTable(other_lane_id()) &&
           VerifyField<double>(verifier, VT_START_S, 8) &&
           VerifyField<double>(verifier, VT_END_S, 8) &&
           VerifyField<double>(verifier, VT_START_S_OTHER, 8) &&
           VerifyField<double>(verifier, VT_END_S_OTHER, 8) &&
           verifier.EndTable();
  }
};

struct LaneRelationBuilder {
  typedef LaneRelation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_other_lane_id(::flatbuffers::Offset<osi3::Identifier> other_lane_id) {
    fbb_.AddOffset(LaneRelation::VT_OTHER_LANE_ID, other_lane_id);
  }
  void add_start_s(double start_s) {
    fbb_.AddElement<double>(LaneRelation::VT_START_S, start_s, 0.0);
  }
  void add_end_s(double end_s) {
    fbb_.AddElement<double>(LaneRelation::VT_END_S, end_s, 0.0);
  }
  void add_start_s_other(double start_s_other) {
    fbb_.AddElement<double>(LaneRelation::VT_START_S_OTHER, start_s_other, 0.0);
  }
  void add_end_s_other(double end_s_other) {
    fbb_.AddElement<double>(LaneRelation::VT_END_S_OTHER, end_s_other, 0.0);
  }
  explicit LaneRelationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LaneRelation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LaneRelation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LaneRelation> CreateLaneRelation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> other_lane_id = 0,
    double start_s = 0.0,
    double end_s = 0.0,
    double start_s_other = 0.0,
    double end_s_other = 0.0) {
  LaneRelationBuilder builder_(_fbb);
  builder_.add_end_s_other(end_s_other);
  builder_.add_start_s_other(start_s_other);
  builder_.add_end_s(end_s);
  builder_.add_start_s(start_s);
  builder_.add_other_lane_id(other_lane_id);
  return builder_.Finish();
}

struct TrafficRule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrafficRuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRAFFIC_RULE_TYPE = 4,
    VT_TRAFFIC_RULE_VALIDITY = 6,
    VT_SPEED_LIMIT = 8
  };
  osi3::LogicalLane_::TrafficRule_::TrafficRuleType traffic_rule_type() const {
    return static_cast<osi3::LogicalLane_::TrafficRule_::TrafficRuleType>(GetField<int32_t>(VT_TRAFFIC_RULE_TYPE, 0));
  }
  const osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity *traffic_rule_validity() const {
    return GetPointer<const osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity *>(VT_TRAFFIC_RULE_VALIDITY);
  }
  const osi3::LogicalLane_::TrafficRule_::SpeedLimit *speed_limit() const {
    return GetPointer<const osi3::LogicalLane_::TrafficRule_::SpeedLimit *>(VT_SPEED_LIMIT);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TRAFFIC_RULE_TYPE, 4) &&
           VerifyOffset(verifier, VT_TRAFFIC_RULE_VALIDITY) &&
           verifier.VerifyTable(traffic_rule_validity()) &&
           VerifyOffset(verifier, VT_SPEED_LIMIT) &&
           verifier.VerifyTable(speed_limit()) &&
           verifier.EndTable();
  }
};

struct TrafficRuleBuilder {
  typedef TrafficRule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_traffic_rule_type(osi3::LogicalLane_::TrafficRule_::TrafficRuleType traffic_rule_type) {
    fbb_.AddElement<int32_t>(TrafficRule::VT_TRAFFIC_RULE_TYPE, static_cast<int32_t>(traffic_rule_type), 0);
  }
  void add_traffic_rule_validity(::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity> traffic_rule_validity) {
    fbb_.AddOffset(TrafficRule::VT_TRAFFIC_RULE_VALIDITY, traffic_rule_validity);
  }
  void add_speed_limit(::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::SpeedLimit> speed_limit) {
    fbb_.AddOffset(TrafficRule::VT_SPEED_LIMIT, speed_limit);
  }
  explicit TrafficRuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrafficRule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrafficRule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrafficRule> CreateTrafficRule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::LogicalLane_::TrafficRule_::TrafficRuleType traffic_rule_type = osi3::LogicalLane_::TrafficRule_::TrafficRuleType_TRAFFIC_RULE_TYPE_SPEED_LIMIT,
    ::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity> traffic_rule_validity = 0,
    ::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::SpeedLimit> speed_limit = 0) {
  TrafficRuleBuilder builder_(_fbb);
  builder_.add_speed_limit(speed_limit);
  builder_.add_traffic_rule_validity(traffic_rule_validity);
  builder_.add_traffic_rule_type(traffic_rule_type);
  return builder_.Finish();
}

namespace TrafficRule_ {

struct TrafficRuleValidity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TrafficRuleValidityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_START_S = 4,
    VT_END_S = 6,
    VT_VALID_FOR_TYPE = 8
  };
  double start_s() const {
    return GetField<double>(VT_START_S, 0.0);
  }
  double end_s() const {
    return GetField<double>(VT_END_S, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>> *valid_for_type() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>> *>(VT_VALID_FOR_TYPE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_START_S, 8) &&
           VerifyField<double>(verifier, VT_END_S, 8) &&
           VerifyOffset(verifier, VT_VALID_FOR_TYPE) &&
           verifier.VerifyVector(valid_for_type()) &&
           verifier.VerifyVectorOfTables(valid_for_type()) &&
           verifier.EndTable();
  }
};

struct TrafficRuleValidityBuilder {
  typedef TrafficRuleValidity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_start_s(double start_s) {
    fbb_.AddElement<double>(TrafficRuleValidity::VT_START_S, start_s, 0.0);
  }
  void add_end_s(double end_s) {
    fbb_.AddElement<double>(TrafficRuleValidity::VT_END_S, end_s, 0.0);
  }
  void add_valid_for_type(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>>> valid_for_type) {
    fbb_.AddOffset(TrafficRuleValidity::VT_VALID_FOR_TYPE, valid_for_type);
  }
  explicit TrafficRuleValidityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TrafficRuleValidity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TrafficRuleValidity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TrafficRuleValidity> CreateTrafficRuleValidity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double start_s = 0.0,
    double end_s = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>>> valid_for_type = 0) {
  TrafficRuleValidityBuilder builder_(_fbb);
  builder_.add_end_s(end_s);
  builder_.add_start_s(start_s);
  builder_.add_valid_for_type(valid_for_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TrafficRuleValidity> CreateTrafficRuleValidityDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double start_s = 0.0,
    double end_s = 0.0,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>> *valid_for_type = nullptr) {
  auto valid_for_type__ = valid_for_type ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane_::TrafficRule_::TrafficRuleValidity_::TypeValidity>>(*valid_for_type) : 0;
  return osi3::LogicalLane_::TrafficRule_::CreateTrafficRuleValidity(
      _fbb,
      start_s,
      end_s,
      valid_for_type__);
}

namespace TrafficRuleValidity_ {

struct TypeValidity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TypeValidityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_VEHICLE_TYPE = 6,
    VT_VEHICLE_ROLE = 8
  };
  osi3::MovingObject_::Type type() const {
    return static_cast<osi3::MovingObject_::Type>(GetField<int32_t>(VT_TYPE, 0));
  }
  osi3::MovingObject_::VehicleClassification_::Type vehicle_type() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::Type>(GetField<int32_t>(VT_VEHICLE_TYPE, 0));
  }
  osi3::MovingObject_::VehicleClassification_::Role vehicle_role() const {
    return static_cast<osi3::MovingObject_::VehicleClassification_::Role>(GetField<int32_t>(VT_VEHICLE_ROLE, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_VEHICLE_TYPE, 4) &&
           VerifyField<int32_t>(verifier, VT_VEHICLE_ROLE, 4) &&
           verifier.EndTable();
  }
};

struct TypeValidityBuilder {
  typedef TypeValidity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(osi3::MovingObject_::Type type) {
    fbb_.AddElement<int32_t>(TypeValidity::VT_TYPE, static_cast<int32_t>(type), 0);
  }
  void add_vehicle_type(osi3::MovingObject_::VehicleClassification_::Type vehicle_type) {
    fbb_.AddElement<int32_t>(TypeValidity::VT_VEHICLE_TYPE, static_cast<int32_t>(vehicle_type), 0);
  }
  void add_vehicle_role(osi3::MovingObject_::VehicleClassification_::Role vehicle_role) {
    fbb_.AddElement<int32_t>(TypeValidity::VT_VEHICLE_ROLE, static_cast<int32_t>(vehicle_role), 0);
  }
  explicit TypeValidityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TypeValidity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TypeValidity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TypeValidity> CreateTypeValidity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    osi3::MovingObject_::Type type = osi3::MovingObject_::Type_TYPE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::Type vehicle_type = osi3::MovingObject_::VehicleClassification_::Type_TYPE_UNKNOWN,
    osi3::MovingObject_::VehicleClassification_::Role vehicle_role = osi3::MovingObject_::VehicleClassification_::Role_ROLE_UNKNOWN) {
  TypeValidityBuilder builder_(_fbb);
  builder_.add_vehicle_role(vehicle_role);
  builder_.add_vehicle_type(vehicle_type);
  builder_.add_type(type);
  return builder_.Finish();
}

}  // namespace TrafficRuleValidity_

struct SpeedLimit FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpeedLimitBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SPEED_LIMIT_VALUE = 4
  };
  const osi3::TrafficSignValue *speed_limit_value() const {
    return GetPointer<const osi3::TrafficSignValue *>(VT_SPEED_LIMIT_VALUE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SPEED_LIMIT_VALUE) &&
           verifier.VerifyTable(speed_limit_value()) &&
           verifier.EndTable();
  }
};

struct SpeedLimitBuilder {
  typedef SpeedLimit Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_speed_limit_value(::flatbuffers::Offset<osi3::TrafficSignValue> speed_limit_value) {
    fbb_.AddOffset(SpeedLimit::VT_SPEED_LIMIT_VALUE, speed_limit_value);
  }
  explicit SpeedLimitBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpeedLimit> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpeedLimit>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpeedLimit> CreateSpeedLimit(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::TrafficSignValue> speed_limit_value = 0) {
  SpeedLimitBuilder builder_(_fbb);
  builder_.add_speed_limit_value(speed_limit_value);
  return builder_.Finish();
}

}  // namespace TrafficRule_
}  // namespace LogicalLane_

namespace LogicalLaneBoundary_ {

}  // namespace LogicalLaneBoundary_

namespace LogicalLane_ {

namespace TrafficRule_ {

namespace TrafficRuleValidity_ {

}  // namespace TrafficRuleValidity_

}  // namespace TrafficRule_
}  // namespace LogicalLane_
}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSILOGICALLANE_OSI3_LOGICALLANE__TRAFFICRULE__H_
