// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIGROUNDTRUTH_OSI3_GROUNDTRUTH__H_
#define FLATBUFFERS_GENERATED_OSIGROUNDTRUTH_OSI3_GROUNDTRUTH__H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"
#include "osi_environment_generated.h"
#include "osi_lane_generated.h"
#include "osi_logicallane_generated.h"
#include "osi_object_generated.h"
#include "osi_occupant_generated.h"
#include "osi_referenceline_generated.h"
#include "osi_roadmarking_generated.h"
#include "osi_trafficlight_generated.h"
#include "osi_trafficsign_generated.h"

namespace osi3 {

struct GroundTruth;
struct GroundTruthBuilder;

namespace GroundTruth_ {

struct ProjFrameOffset;
struct ProjFrameOffsetBuilder;

}  // namespace GroundTruth_

struct GroundTruth FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GroundTruthBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_HOST_VEHICLE_ID = 6,
    VT_STATIONARY_OBJECT = 8,
    VT_MOVING_OBJECT = 10,
    VT_TRAFFIC_SIGN = 12,
    VT_TRAFFIC_LIGHT = 14,
    VT_ROAD_MARKING = 16,
    VT_LANE_BOUNDARY = 18,
    VT_LANE = 20,
    VT_OCCUPANT = 22,
    VT_ENVIRONMENTAL_CONDITIONS = 24,
    VT_COUNTRY_CODE = 26,
    VT_PROJ_STRING = 28,
    VT_MAP_REFERENCE = 30,
    VT_MODEL_REFERENCE = 32,
    VT_REFERENCE_LINE = 34,
    VT_LOGICAL_LANE_BOUNDARY = 36,
    VT_LOGICAL_LANE = 38,
    VT_PROJ_FRAME_OFFSET = 40
  };
  const osi3::Timestamp *timestamp() const {
    return GetPointer<const osi3::Timestamp *>(VT_TIMESTAMP);
  }
  const osi3::Identifier *host_vehicle_id() const {
    return GetPointer<const osi3::Identifier *>(VT_HOST_VEHICLE_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::StationaryObject>> *stationary_object() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::StationaryObject>> *>(VT_STATIONARY_OBJECT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject>> *moving_object() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject>> *>(VT_MOVING_OBJECT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficSign>> *traffic_sign() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficSign>> *>(VT_TRAFFIC_SIGN);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficLight>> *traffic_light() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficLight>> *>(VT_TRAFFIC_LIGHT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::RoadMarking>> *road_marking() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::RoadMarking>> *>(VT_ROAD_MARKING);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary>> *lane_boundary() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary>> *>(VT_LANE_BOUNDARY);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane>> *lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane>> *>(VT_LANE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Occupant>> *occupant() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::Occupant>> *>(VT_OCCUPANT);
  }
  const osi3::EnvironmentalConditions *environmental_conditions() const {
    return GetPointer<const osi3::EnvironmentalConditions *>(VT_ENVIRONMENTAL_CONDITIONS);
  }
  uint32_t country_code() const {
    return GetField<uint32_t>(VT_COUNTRY_CODE, 0);
  }
  const ::flatbuffers::String *proj_string() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PROJ_STRING);
  }
  const ::flatbuffers::String *map_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAP_REFERENCE);
  }
  const ::flatbuffers::String *model_reference() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_REFERENCE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine>> *reference_line() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine>> *>(VT_REFERENCE_LINE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>> *logical_lane_boundary() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>> *>(VT_LOGICAL_LANE_BOUNDARY);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane>> *logical_lane() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane>> *>(VT_LOGICAL_LANE);
  }
  const osi3::GroundTruth_::ProjFrameOffset *proj_frame_offset() const {
    return GetPointer<const osi3::GroundTruth_::ProjFrameOffset *>(VT_PROJ_FRAME_OFFSET);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TIMESTAMP) &&
           verifier.VerifyTable(timestamp()) &&
           VerifyOffset(verifier, VT_HOST_VEHICLE_ID) &&
           verifier.VerifyTable(host_vehicle_id()) &&
           VerifyOffset(verifier, VT_STATIONARY_OBJECT) &&
           verifier.VerifyVector(stationary_object()) &&
           verifier.VerifyVectorOfTables(stationary_object()) &&
           VerifyOffset(verifier, VT_MOVING_OBJECT) &&
           verifier.VerifyVector(moving_object()) &&
           verifier.VerifyVectorOfTables(moving_object()) &&
           VerifyOffset(verifier, VT_TRAFFIC_SIGN) &&
           verifier.VerifyVector(traffic_sign()) &&
           verifier.VerifyVectorOfTables(traffic_sign()) &&
           VerifyOffset(verifier, VT_TRAFFIC_LIGHT) &&
           verifier.VerifyVector(traffic_light()) &&
           verifier.VerifyVectorOfTables(traffic_light()) &&
           VerifyOffset(verifier, VT_ROAD_MARKING) &&
           verifier.VerifyVector(road_marking()) &&
           verifier.VerifyVectorOfTables(road_marking()) &&
           VerifyOffset(verifier, VT_LANE_BOUNDARY) &&
           verifier.VerifyVector(lane_boundary()) &&
           verifier.VerifyVectorOfTables(lane_boundary()) &&
           VerifyOffset(verifier, VT_LANE) &&
           verifier.VerifyVector(lane()) &&
           verifier.VerifyVectorOfTables(lane()) &&
           VerifyOffset(verifier, VT_OCCUPANT) &&
           verifier.VerifyVector(occupant()) &&
           verifier.VerifyVectorOfTables(occupant()) &&
           VerifyOffset(verifier, VT_ENVIRONMENTAL_CONDITIONS) &&
           verifier.VerifyTable(environmental_conditions()) &&
           VerifyField<uint32_t>(verifier, VT_COUNTRY_CODE, 4) &&
           VerifyOffset(verifier, VT_PROJ_STRING) &&
           verifier.VerifyString(proj_string()) &&
           VerifyOffset(verifier, VT_MAP_REFERENCE) &&
           verifier.VerifyString(map_reference()) &&
           VerifyOffset(verifier, VT_MODEL_REFERENCE) &&
           verifier.VerifyString(model_reference()) &&
           VerifyOffset(verifier, VT_REFERENCE_LINE) &&
           verifier.VerifyVector(reference_line()) &&
           verifier.VerifyVectorOfTables(reference_line()) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE_BOUNDARY) &&
           verifier.VerifyVector(logical_lane_boundary()) &&
           verifier.VerifyVectorOfTables(logical_lane_boundary()) &&
           VerifyOffset(verifier, VT_LOGICAL_LANE) &&
           verifier.VerifyVector(logical_lane()) &&
           verifier.VerifyVectorOfTables(logical_lane()) &&
           VerifyOffset(verifier, VT_PROJ_FRAME_OFFSET) &&
           verifier.VerifyTable(proj_frame_offset()) &&
           verifier.EndTable();
  }
};

struct GroundTruthBuilder {
  typedef GroundTruth Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_timestamp(::flatbuffers::Offset<osi3::Timestamp> timestamp) {
    fbb_.AddOffset(GroundTruth::VT_TIMESTAMP, timestamp);
  }
  void add_host_vehicle_id(::flatbuffers::Offset<osi3::Identifier> host_vehicle_id) {
    fbb_.AddOffset(GroundTruth::VT_HOST_VEHICLE_ID, host_vehicle_id);
  }
  void add_stationary_object(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::StationaryObject>>> stationary_object) {
    fbb_.AddOffset(GroundTruth::VT_STATIONARY_OBJECT, stationary_object);
  }
  void add_moving_object(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject>>> moving_object) {
    fbb_.AddOffset(GroundTruth::VT_MOVING_OBJECT, moving_object);
  }
  void add_traffic_sign(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficSign>>> traffic_sign) {
    fbb_.AddOffset(GroundTruth::VT_TRAFFIC_SIGN, traffic_sign);
  }
  void add_traffic_light(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficLight>>> traffic_light) {
    fbb_.AddOffset(GroundTruth::VT_TRAFFIC_LIGHT, traffic_light);
  }
  void add_road_marking(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::RoadMarking>>> road_marking) {
    fbb_.AddOffset(GroundTruth::VT_ROAD_MARKING, road_marking);
  }
  void add_lane_boundary(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary>>> lane_boundary) {
    fbb_.AddOffset(GroundTruth::VT_LANE_BOUNDARY, lane_boundary);
  }
  void add_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane>>> lane) {
    fbb_.AddOffset(GroundTruth::VT_LANE, lane);
  }
  void add_occupant(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Occupant>>> occupant) {
    fbb_.AddOffset(GroundTruth::VT_OCCUPANT, occupant);
  }
  void add_environmental_conditions(::flatbuffers::Offset<osi3::EnvironmentalConditions> environmental_conditions) {
    fbb_.AddOffset(GroundTruth::VT_ENVIRONMENTAL_CONDITIONS, environmental_conditions);
  }
  void add_country_code(uint32_t country_code) {
    fbb_.AddElement<uint32_t>(GroundTruth::VT_COUNTRY_CODE, country_code, 0);
  }
  void add_proj_string(::flatbuffers::Offset<::flatbuffers::String> proj_string) {
    fbb_.AddOffset(GroundTruth::VT_PROJ_STRING, proj_string);
  }
  void add_map_reference(::flatbuffers::Offset<::flatbuffers::String> map_reference) {
    fbb_.AddOffset(GroundTruth::VT_MAP_REFERENCE, map_reference);
  }
  void add_model_reference(::flatbuffers::Offset<::flatbuffers::String> model_reference) {
    fbb_.AddOffset(GroundTruth::VT_MODEL_REFERENCE, model_reference);
  }
  void add_reference_line(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine>>> reference_line) {
    fbb_.AddOffset(GroundTruth::VT_REFERENCE_LINE, reference_line);
  }
  void add_logical_lane_boundary(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>>> logical_lane_boundary) {
    fbb_.AddOffset(GroundTruth::VT_LOGICAL_LANE_BOUNDARY, logical_lane_boundary);
  }
  void add_logical_lane(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane>>> logical_lane) {
    fbb_.AddOffset(GroundTruth::VT_LOGICAL_LANE, logical_lane);
  }
  void add_proj_frame_offset(::flatbuffers::Offset<osi3::GroundTruth_::ProjFrameOffset> proj_frame_offset) {
    fbb_.AddOffset(GroundTruth::VT_PROJ_FRAME_OFFSET, proj_frame_offset);
  }
  explicit GroundTruthBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GroundTruth> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GroundTruth>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GroundTruth> CreateGroundTruth(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Timestamp> timestamp = 0,
    ::flatbuffers::Offset<osi3::Identifier> host_vehicle_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::StationaryObject>>> stationary_object = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::MovingObject>>> moving_object = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficSign>>> traffic_sign = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::TrafficLight>>> traffic_light = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::RoadMarking>>> road_marking = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LaneBoundary>>> lane_boundary = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Lane>>> lane = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::Occupant>>> occupant = 0,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions> environmental_conditions = 0,
    uint32_t country_code = 0,
    ::flatbuffers::Offset<::flatbuffers::String> proj_string = 0,
    ::flatbuffers::Offset<::flatbuffers::String> map_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_reference = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ReferenceLine>>> reference_line = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>>> logical_lane_boundary = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::LogicalLane>>> logical_lane = 0,
    ::flatbuffers::Offset<osi3::GroundTruth_::ProjFrameOffset> proj_frame_offset = 0) {
  GroundTruthBuilder builder_(_fbb);
  builder_.add_proj_frame_offset(proj_frame_offset);
  builder_.add_logical_lane(logical_lane);
  builder_.add_logical_lane_boundary(logical_lane_boundary);
  builder_.add_reference_line(reference_line);
  builder_.add_model_reference(model_reference);
  builder_.add_map_reference(map_reference);
  builder_.add_proj_string(proj_string);
  builder_.add_country_code(country_code);
  builder_.add_environmental_conditions(environmental_conditions);
  builder_.add_occupant(occupant);
  builder_.add_lane(lane);
  builder_.add_lane_boundary(lane_boundary);
  builder_.add_road_marking(road_marking);
  builder_.add_traffic_light(traffic_light);
  builder_.add_traffic_sign(traffic_sign);
  builder_.add_moving_object(moving_object);
  builder_.add_stationary_object(stationary_object);
  builder_.add_host_vehicle_id(host_vehicle_id);
  builder_.add_timestamp(timestamp);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GroundTruth> CreateGroundTruthDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Timestamp> timestamp = 0,
    ::flatbuffers::Offset<osi3::Identifier> host_vehicle_id = 0,
    const std::vector<::flatbuffers::Offset<osi3::StationaryObject>> *stationary_object = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::MovingObject>> *moving_object = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::TrafficSign>> *traffic_sign = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::TrafficLight>> *traffic_light = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::RoadMarking>> *road_marking = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LaneBoundary>> *lane_boundary = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Lane>> *lane = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::Occupant>> *occupant = nullptr,
    ::flatbuffers::Offset<osi3::EnvironmentalConditions> environmental_conditions = 0,
    uint32_t country_code = 0,
    const char *proj_string = nullptr,
    const char *map_reference = nullptr,
    const char *model_reference = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::ReferenceLine>> *reference_line = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>> *logical_lane_boundary = nullptr,
    const std::vector<::flatbuffers::Offset<osi3::LogicalLane>> *logical_lane = nullptr,
    ::flatbuffers::Offset<osi3::GroundTruth_::ProjFrameOffset> proj_frame_offset = 0) {
  auto stationary_object__ = stationary_object ? _fbb.CreateVector<::flatbuffers::Offset<osi3::StationaryObject>>(*stationary_object) : 0;
  auto moving_object__ = moving_object ? _fbb.CreateVector<::flatbuffers::Offset<osi3::MovingObject>>(*moving_object) : 0;
  auto traffic_sign__ = traffic_sign ? _fbb.CreateVector<::flatbuffers::Offset<osi3::TrafficSign>>(*traffic_sign) : 0;
  auto traffic_light__ = traffic_light ? _fbb.CreateVector<::flatbuffers::Offset<osi3::TrafficLight>>(*traffic_light) : 0;
  auto road_marking__ = road_marking ? _fbb.CreateVector<::flatbuffers::Offset<osi3::RoadMarking>>(*road_marking) : 0;
  auto lane_boundary__ = lane_boundary ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LaneBoundary>>(*lane_boundary) : 0;
  auto lane__ = lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Lane>>(*lane) : 0;
  auto occupant__ = occupant ? _fbb.CreateVector<::flatbuffers::Offset<osi3::Occupant>>(*occupant) : 0;
  auto proj_string__ = proj_string ? _fbb.CreateString(proj_string) : 0;
  auto map_reference__ = map_reference ? _fbb.CreateString(map_reference) : 0;
  auto model_reference__ = model_reference ? _fbb.CreateString(model_reference) : 0;
  auto reference_line__ = reference_line ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ReferenceLine>>(*reference_line) : 0;
  auto logical_lane_boundary__ = logical_lane_boundary ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLaneBoundary>>(*logical_lane_boundary) : 0;
  auto logical_lane__ = logical_lane ? _fbb.CreateVector<::flatbuffers::Offset<osi3::LogicalLane>>(*logical_lane) : 0;
  return osi3::CreateGroundTruth(
      _fbb,
      timestamp,
      host_vehicle_id,
      stationary_object__,
      moving_object__,
      traffic_sign__,
      traffic_light__,
      road_marking__,
      lane_boundary__,
      lane__,
      occupant__,
      environmental_conditions,
      country_code,
      proj_string__,
      map_reference__,
      model_reference__,
      reference_line__,
      logical_lane_boundary__,
      logical_lane__,
      proj_frame_offset);
}

namespace GroundTruth_ {

struct ProjFrameOffset FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProjFrameOffsetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_YAW = 6
  };
  const osi3::Vector3d *position() const {
    return GetPointer<const osi3::Vector3d *>(VT_POSITION);
  }
  double yaw() const {
    return GetField<double>(VT_YAW, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITION) &&
           verifier.VerifyTable(position()) &&
           VerifyField<double>(verifier, VT_YAW, 8) &&
           verifier.EndTable();
  }
};

struct ProjFrameOffsetBuilder {
  typedef ProjFrameOffset Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(::flatbuffers::Offset<osi3::Vector3d> position) {
    fbb_.AddOffset(ProjFrameOffset::VT_POSITION, position);
  }
  void add_yaw(double yaw) {
    fbb_.AddElement<double>(ProjFrameOffset::VT_YAW, yaw, 0.0);
  }
  explicit ProjFrameOffsetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ProjFrameOffset> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ProjFrameOffset>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ProjFrameOffset> CreateProjFrameOffset(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Vector3d> position = 0,
    double yaw = 0.0) {
  ProjFrameOffsetBuilder builder_(_fbb);
  builder_.add_yaw(yaw);
  builder_.add_position(position);
  return builder_.Finish();
}

}  // namespace GroundTruth_

namespace GroundTruth_ {

}  // namespace GroundTruth_
}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIGROUNDTRUTH_OSI3_GROUNDTRUTH__H_
