include "osi_common.fbs";
include "osi_environment.fbs";
include "osi_trafficsign.fbs";
include "osi_trafficlight.fbs";
include "osi_roadmarking.fbs";
include "osi_lane.fbs";
include "osi_logicallane.fbs";
include "osi_referenceline.fbs";
include "osi_object.fbs";
include "osi_occupant.fbs";

namespace osi3.GroundTruth_;
table ProjFrameOffset {
  position:osi3.Vector3d;
  yaw:double;
}

namespace osi3;
table GroundTruth {
  timestamp:osi3.Timestamp;
  host_vehicle_id:osi3.Identifier;
  stationary_object:[osi3.StationaryObject];
  moving_object:[osi3.MovingObject];
  traffic_sign:[osi3.TrafficSign];
  traffic_light:[osi3.TrafficLight];
  road_marking:[osi3.RoadMarking];
  lane_boundary:[osi3.LaneBoundary];
  lane:[osi3.Lane];
  occupant:[osi3.Occupant];
  environmental_conditions:osi3.EnvironmentalConditions;
  country_code:uint;
  proj_string:string;
  map_reference:string;
  model_reference:string;
  reference_line:[osi3.ReferenceLine];
  logical_lane_boundary:[osi3.LogicalLaneBoundary];
  logical_lane:[osi3.LogicalLane];
  proj_frame_offset:osi3.GroundTruth_.ProjFrameOffset;
}
