// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_OSIOCCUPANT_OSI3_OCCUPANT__H_
#define FLATBUFFERS_GENERATED_OSIOCCUPANT_OSI3_OCCUPANT__H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

#include "osi_common_generated.h"

namespace osi3 {

struct Occupant;
struct OccupantBuilder;

namespace Occupant_ {

struct Classification;
struct ClassificationBuilder;

namespace Classification_ {

enum Seat : int32_t {
  Seat_SEAT_UNKNOWN = 0,
  Seat_SEAT_OTHER = 1,
  Seat_SEAT_FRONT_LEFT = 2,
  Seat_SEAT_FRONT_RIGHT = 3,
  Seat_SEAT_FRONT_MIDDLE = 4,
  Seat_SEAT_BACK_LEFT = 5,
  Seat_SEAT_BACK_RIGHT = 6,
  Seat_SEAT_BACK_MIDDLE = 7,
  Seat_SEAT_THIRD_ROW_LEFT = 8,
  Seat_SEAT_THIRD_ROW_RIGHT = 9,
  Seat_SEAT_THIRD_ROW_MIDDLE = 10,
  Seat_MIN = Seat_SEAT_UNKNOWN,
  Seat_MAX = Seat_SEAT_THIRD_ROW_MIDDLE
};

inline const Seat (&EnumValuesSeat())[11] {
  static const Seat values[] = {
    Seat_SEAT_UNKNOWN,
    Seat_SEAT_OTHER,
    Seat_SEAT_FRONT_LEFT,
    Seat_SEAT_FRONT_RIGHT,
    Seat_SEAT_FRONT_MIDDLE,
    Seat_SEAT_BACK_LEFT,
    Seat_SEAT_BACK_RIGHT,
    Seat_SEAT_BACK_MIDDLE,
    Seat_SEAT_THIRD_ROW_LEFT,
    Seat_SEAT_THIRD_ROW_RIGHT,
    Seat_SEAT_THIRD_ROW_MIDDLE
  };
  return values;
}

inline const char * const *EnumNamesSeat() {
  static const char * const names[12] = {
    "SEAT_UNKNOWN",
    "SEAT_OTHER",
    "SEAT_FRONT_LEFT",
    "SEAT_FRONT_RIGHT",
    "SEAT_FRONT_MIDDLE",
    "SEAT_BACK_LEFT",
    "SEAT_BACK_RIGHT",
    "SEAT_BACK_MIDDLE",
    "SEAT_THIRD_ROW_LEFT",
    "SEAT_THIRD_ROW_RIGHT",
    "SEAT_THIRD_ROW_MIDDLE",
    nullptr
  };
  return names;
}

inline const char *EnumNameSeat(Seat e) {
  if (::flatbuffers::IsOutRange(e, Seat_SEAT_UNKNOWN, Seat_SEAT_THIRD_ROW_MIDDLE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSeat()[index];
}

enum SteeringControl : int32_t {
  SteeringControl_STEERING_CONTROL_UNKNOWN = 0,
  SteeringControl_STEERING_CONTROL_OTHER = 1,
  SteeringControl_STEERING_CONTROL_NO_HAND = 2,
  SteeringControl_STEERING_CONTROL_ONE_HAND = 3,
  SteeringControl_STEERING_CONTROL_BOTH_HANDS = 4,
  SteeringControl_STEERING_CONTROL_LEFT_HAND = 5,
  SteeringControl_STEERING_CONTROL_RIGHT_HAND = 6,
  SteeringControl_MIN = SteeringControl_STEERING_CONTROL_UNKNOWN,
  SteeringControl_MAX = SteeringControl_STEERING_CONTROL_RIGHT_HAND
};

inline const SteeringControl (&EnumValuesSteeringControl())[7] {
  static const SteeringControl values[] = {
    SteeringControl_STEERING_CONTROL_UNKNOWN,
    SteeringControl_STEERING_CONTROL_OTHER,
    SteeringControl_STEERING_CONTROL_NO_HAND,
    SteeringControl_STEERING_CONTROL_ONE_HAND,
    SteeringControl_STEERING_CONTROL_BOTH_HANDS,
    SteeringControl_STEERING_CONTROL_LEFT_HAND,
    SteeringControl_STEERING_CONTROL_RIGHT_HAND
  };
  return values;
}

inline const char * const *EnumNamesSteeringControl() {
  static const char * const names[8] = {
    "STEERING_CONTROL_UNKNOWN",
    "STEERING_CONTROL_OTHER",
    "STEERING_CONTROL_NO_HAND",
    "STEERING_CONTROL_ONE_HAND",
    "STEERING_CONTROL_BOTH_HANDS",
    "STEERING_CONTROL_LEFT_HAND",
    "STEERING_CONTROL_RIGHT_HAND",
    nullptr
  };
  return names;
}

inline const char *EnumNameSteeringControl(SteeringControl e) {
  if (::flatbuffers::IsOutRange(e, SteeringControl_STEERING_CONTROL_UNKNOWN, SteeringControl_STEERING_CONTROL_RIGHT_HAND)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSteeringControl()[index];
}

}  // namespace Classification_
}  // namespace Occupant_

struct Occupant FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OccupantBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_CLASSIFICATION = 6,
    VT_SOURCE_REFERENCE = 8
  };
  const osi3::Identifier *id() const {
    return GetPointer<const osi3::Identifier *>(VT_ID);
  }
  const osi3::Occupant_::Classification *classification() const {
    return GetPointer<const osi3::Occupant_::Classification *>(VT_CLASSIFICATION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>> *>(VT_SOURCE_REFERENCE);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyTable(id()) &&
           VerifyOffset(verifier, VT_CLASSIFICATION) &&
           verifier.VerifyTable(classification()) &&
           VerifyOffset(verifier, VT_SOURCE_REFERENCE) &&
           verifier.VerifyVector(source_reference()) &&
           verifier.VerifyVectorOfTables(source_reference()) &&
           verifier.EndTable();
  }
};

struct OccupantBuilder {
  typedef Occupant Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<osi3::Identifier> id) {
    fbb_.AddOffset(Occupant::VT_ID, id);
  }
  void add_classification(::flatbuffers::Offset<osi3::Occupant_::Classification> classification) {
    fbb_.AddOffset(Occupant::VT_CLASSIFICATION, classification);
  }
  void add_source_reference(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference) {
    fbb_.AddOffset(Occupant::VT_SOURCE_REFERENCE, source_reference);
  }
  explicit OccupantBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Occupant> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Occupant>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Occupant> CreateOccupant(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::Occupant_::Classification> classification = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<osi3::ExternalReference>>> source_reference = 0) {
  OccupantBuilder builder_(_fbb);
  builder_.add_source_reference(source_reference);
  builder_.add_classification(classification);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Occupant> CreateOccupantDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<osi3::Identifier> id = 0,
    ::flatbuffers::Offset<osi3::Occupant_::Classification> classification = 0,
    const std::vector<::flatbuffers::Offset<osi3::ExternalReference>> *source_reference = nullptr) {
  auto source_reference__ = source_reference ? _fbb.CreateVector<::flatbuffers::Offset<osi3::ExternalReference>>(*source_reference) : 0;
  return osi3::CreateOccupant(
      _fbb,
      id,
      classification,
      source_reference__);
}

namespace Occupant_ {

struct Classification FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassificationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_DRIVER = 4,
    VT_SEAT = 6,
    VT_STEERING_CONTROL = 8
  };
  bool is_driver() const {
    return GetField<uint8_t>(VT_IS_DRIVER, 0) != 0;
  }
  osi3::Occupant_::Classification_::Seat seat() const {
    return static_cast<osi3::Occupant_::Classification_::Seat>(GetField<int32_t>(VT_SEAT, 0));
  }
  osi3::Occupant_::Classification_::SteeringControl steering_control() const {
    return static_cast<osi3::Occupant_::Classification_::SteeringControl>(GetField<int32_t>(VT_STEERING_CONTROL, 0));
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_DRIVER, 1) &&
           VerifyField<int32_t>(verifier, VT_SEAT, 4) &&
           VerifyField<int32_t>(verifier, VT_STEERING_CONTROL, 4) &&
           verifier.EndTable();
  }
};

struct ClassificationBuilder {
  typedef Classification Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_driver(bool is_driver) {
    fbb_.AddElement<uint8_t>(Classification::VT_IS_DRIVER, static_cast<uint8_t>(is_driver), 0);
  }
  void add_seat(osi3::Occupant_::Classification_::Seat seat) {
    fbb_.AddElement<int32_t>(Classification::VT_SEAT, static_cast<int32_t>(seat), 0);
  }
  void add_steering_control(osi3::Occupant_::Classification_::SteeringControl steering_control) {
    fbb_.AddElement<int32_t>(Classification::VT_STEERING_CONTROL, static_cast<int32_t>(steering_control), 0);
  }
  explicit ClassificationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Classification> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Classification>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Classification> CreateClassification(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_driver = false,
    osi3::Occupant_::Classification_::Seat seat = osi3::Occupant_::Classification_::Seat_SEAT_UNKNOWN,
    osi3::Occupant_::Classification_::SteeringControl steering_control = osi3::Occupant_::Classification_::SteeringControl_STEERING_CONTROL_UNKNOWN) {
  ClassificationBuilder builder_(_fbb);
  builder_.add_steering_control(steering_control);
  builder_.add_seat(seat);
  builder_.add_is_driver(is_driver);
  return builder_.Finish();
}

}  // namespace Occupant_

namespace Occupant_ {

}  // namespace Occupant_
}  // namespace osi3

#endif  // FLATBUFFERS_GENERATED_OSIOCCUPANT_OSI3_OCCUPANT__H_
