include "osi_common.fbs";
include "osi_object.fbs";
include "osi_trafficsign.fbs";

namespace osi3.LogicalLaneBoundary_;
enum PassingRule : int {
    PASSING_RULE_UNKNOWN = 0,
    PASSING_RULE_OTHER = 1,
    PASSING_RULE_NONE_ALLOWED = 2,
    PASSING_RULE_INCREASING_T = 3,
    PASSING_RULE_DECREASING_T = 4,
    PASSING_RULE_BOTH_ALLOWED = 5,
}

namespace osi3.LogicalLaneBoundary_;
table LogicalBoundaryPoint {
  position:osi3.Vector3d;
  s_position:double;
  t_position:double;
}

namespace osi3;
table LogicalLaneBoundary {
  id:osi3.Identifier;
  boundary_line:[osi3.LogicalLaneBoundary_.LogicalBoundaryPoint];
  reference_line_id:osi3.Identifier;
  physical_boundary_id:[osi3.Identifier];
  passing_rule:osi3.LogicalLaneBoundary_.PassingRule;
  source_reference:[osi3.ExternalReference];
}

namespace osi3.LogicalLane_;
enum Type : int {
    TYPE_UNKNOWN = 0,
    TYPE_OTHER = 1,
    TYPE_NORMAL = 2,
    TYPE_BIKING = 3,
    TYPE_SIDEWALK = 4,
    TYPE_PARKING = 5,
    TYPE_STOP = 6,
    TYPE_RESTRICTED = 7,
    TYPE_BORDER = 8,
    TYPE_SHOULDER = 9,
    TYPE_EXIT = 10,
    TYPE_ENTRY = 11,
    TYPE_ONRAMP = 12,
    TYPE_OFFRAMP = 13,
    TYPE_CONNECTINGRAMP = 14,
    TYPE_MEDIAN = 15,
    TYPE_CURB = 16,
    TYPE_RAIL = 17,
    TYPE_TRAM = 18,
}

namespace osi3.LogicalLane_;
enum MoveDirection : int {
    MOVE_DIRECTION_UNKNOWN = 0,
    MOVE_DIRECTION_OTHER = 1,
    MOVE_DIRECTION_INCREASING_S = 2,
    MOVE_DIRECTION_DECREASING_S = 3,
    MOVE_DIRECTION_BOTH_ALLOWED = 4,
}

namespace osi3.LogicalLane_;
table PhysicalLaneReference {
  physical_lane_id:osi3.Identifier;
  start_s:double;
  end_s:double;
}

namespace osi3.LogicalLane_;
table LaneConnection {
  other_lane_id:osi3.Identifier;
  at_begin_of_other_lane:bool;
}

namespace osi3.LogicalLane_;
table LaneRelation {
  other_lane_id:osi3.Identifier;
  start_s:double;
  end_s:double;
  start_s_other:double;
  end_s_other:double;
}

namespace osi3.LogicalLane_.TrafficRule_;
enum TrafficRuleType : int {
    TRAFFIC_RULE_TYPE_SPEED_LIMIT = 0,
}

namespace osi3.LogicalLane_.TrafficRule_.TrafficRuleValidity_;
table TypeValidity {
  type:osi3.MovingObject_.Type;
  vehicle_type:osi3.MovingObject_.VehicleClassification_.Type;
  vehicle_role:osi3.MovingObject_.VehicleClassification_.Role;
}

namespace osi3.LogicalLane_.TrafficRule_;
table TrafficRuleValidity {
  start_s:double;
  end_s:double;
  valid_for_type:[osi3.LogicalLane_.TrafficRule_.TrafficRuleValidity_.TypeValidity];
}

namespace osi3.LogicalLane_.TrafficRule_;
table SpeedLimit {
  speed_limit_value:osi3.TrafficSignValue;
}

namespace osi3.LogicalLane_;
table TrafficRule {
  traffic_rule_type:osi3.LogicalLane_.TrafficRule_.TrafficRuleType;
  traffic_rule_validity:osi3.LogicalLane_.TrafficRule_.TrafficRuleValidity;
  speed_limit:osi3.LogicalLane_.TrafficRule_.SpeedLimit;
}

namespace osi3;
table LogicalLane {
  id:osi3.Identifier;
  type:osi3.LogicalLane_.Type;
  source_reference:[osi3.ExternalReference];
  physical_lane_reference:[osi3.LogicalLane_.PhysicalLaneReference];
  reference_line_id:osi3.Identifier;
  start_s:double;
  end_s:double;
  move_direction:osi3.LogicalLane_.MoveDirection;
  right_adjacent_lane:[osi3.LogicalLane_.LaneRelation];
  left_adjacent_lane:[osi3.LogicalLane_.LaneRelation];
  overlapping_lane:[osi3.LogicalLane_.LaneRelation];
  right_boundary_id:[osi3.Identifier];
  left_boundary_id:[osi3.Identifier];
  predecessor_lane:[osi3.LogicalLane_.LaneConnection];
  successor_lane:[osi3.LogicalLane_.LaneConnection];
  street_name:string;
  traffic_rule:[osi3.LogicalLane_.TrafficRule];
}
