syntax = "proto2";

option optimize_for = SPEED;

import "osi_common.proto";

package osi3;
message Lane
{
    optional Identifier id = 1;
    optional Classification classification = 2;
    repeated ExternalReference source_reference = 3;
    message Classification
    {
        optional Type type = 1;
        optional bool is_host_vehicle_lane = 2;
        repeated Vector3d centerline = 3;
        optional bool centerline_is_driving_direction = 4;
        repeated Identifier left_adjacent_lane_id = 5;
        repeated Identifier right_adjacent_lane_id = 6;
        repeated LanePairing lane_pairing = 7;
        repeated Identifier right_lane_boundary_id = 8;
        repeated Identifier left_lane_boundary_id = 9;
        repeated Identifier free_lane_boundary_id = 10;
        optional RoadCondition road_condition = 11;
        optional Subtype subtype = 12;
        enum Type
        {
            TYPE_UNKNOWN = 0;
            TYPE_OTHER = 1;
            TYPE_DRIVING = 2;
            TYPE_NONDRIVING = 3;
            TYPE_INTERSECTION = 4;
        }
        enum Subtype
        {
            SUBTYPE_UNKNOWN = 0;
            SUBTYPE_OTHER = 1;
            SUBTYPE_NORMAL = 2;
            SUBTYPE_BIKING = 3;
            SUBTYPE_SIDEWALK = 4;
            SUBTYPE_PARKING = 5;
            SUBTYPE_STOP = 6;
            SUBTYPE_RESTRICTED = 7;
            SUBTYPE_BORDER = 8;
            SUBTYPE_SHOULDER = 9;
            SUBTYPE_EXIT = 10;
            SUBTYPE_ENTRY = 11;
            SUBTYPE_ONRAMP = 12;
            SUBTYPE_OFFRAMP = 13;
            SUBTYPE_CONNECTINGRAMP = 14;
        }
        message RoadCondition
        {
            optional double surface_temperature = 1;
            optional double surface_water_film = 2;
            optional double surface_freezing_point = 3;
            optional double surface_ice = 4;
            optional double surface_roughness = 5;
            optional double surface_texture = 6;
        }
        message LanePairing
        {
            optional Identifier antecessor_lane_id = 1;
            optional Identifier successor_lane_id = 2;
        }
    }
}
message LaneBoundary
{
    optional Identifier id = 1;
    repeated BoundaryPoint boundary_line = 2;
    optional Classification classification = 3;
    repeated ExternalReference source_reference = 4;
    optional ColorDescription color_description = 5;
    message BoundaryPoint
    {
        optional Vector3d position = 1;
        optional double width = 2;
        optional double height = 3;
        optional Dash dash = 4;
        enum Dash
        {
            DASH_UNKNOWN = 0;
            DASH_OTHER = 1;
            DASH_START = 2;
            DASH_CONTINUE = 3;
            DASH_END = 4;
            DASH_GAP = 5;
        }
    }
    message Classification
    {
        enum Type
        {
            TYPE_UNKNOWN = 0;
            TYPE_OTHER = 1;
            TYPE_NO_LINE = 2;
            TYPE_SOLID_LINE = 3;
            TYPE_DASHED_LINE = 4;
            TYPE_BOTTS_DOTS = 5;
            TYPE_ROAD_EDGE = 6;
            TYPE_SNOW_EDGE = 7;
            TYPE_GRASS_EDGE = 8;
            TYPE_GRAVEL_EDGE = 9;
            TYPE_SOIL_EDGE = 10;
            TYPE_GUARD_RAIL = 11;
            TYPE_CURB = 12;
            TYPE_STRUCTURE = 13;
            TYPE_BARRIER = 14;
            TYPE_SOUND_BARRIER = 15;
        }
        optional Type type = 1;
        optional Color color = 2;
        repeated Identifier limiting_structure_id = 3;
        enum Color
        {
            COLOR_UNKNOWN = 0;
            COLOR_OTHER = 1;
            COLOR_NONE = 2;
            COLOR_WHITE = 3;
            COLOR_YELLOW = 4;
            COLOR_RED = 5;
            COLOR_BLUE = 6;
            COLOR_GREEN = 7;
            COLOR_VIOLET = 8;
            COLOR_ORANGE = 9;
        }
    }
}
