name: apps

on:
  push:
    paths:
    - 'apps/**'
    - 'include/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install reelay library
      run: sudo make install
    - name: Build command-line apps
      run: make apps
