name: apps

on:
  push:
    paths:
    - 'apps/**'
    - 'include/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y uuid-dev 
        sudo apt-get install -y libboost-all-dev
    - name: Install reelay library
      run: sudo make install
    - name: Build command-line apps
      run: make apps
