name: C/C++ CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y uuid-dev 
        sudo apt-get install -y libboost-all-dev
    - name: build
      run: |
        make antlr4-runtime
        sudo make antlr4-runtime-install
        make 
        sudo make install
    - name: test
      run: make test
