name: apps

on:
  push:
    paths:
    - 'mkdocs.yml'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
    - name: build and publish docs
      run: mkdocs gh-deploy --clean
      with:
        repo-token: ${{ secrets.ACCESS_TOKEN }}
    - name: build
      run: make apps
