name: docs

on:
  push:
    paths:
    - 'mkdocs.yml'
    - 'docs/**'
    - '.github/workflows/docs.yml' # Self-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build and deploy docs
      run: mkdocs gh-deploy --clean
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}