name: library

on:
  push:
    paths:
    - 'include/reelay/**'
    - '.github/workflows/library.yml' # Self-trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y uuid-dev
        sudo apt-get install -y autotools-dev
        sudo apt-get install -y libboost-all-dev

    - name: Install CUDD
      run: |
        make cudd
        sudo make cudd-install
        sudo ldconfig

    - name: Install Reelay
      run: |
        sudo make install

    - name: Test
      run: make test
