name: python

on:
  push:
    paths:
    - 'python/**'
    - 'include/reelay/**'
    - '.github/workflows/python.yml' # Self-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v1

    - name: Install Reelay dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Setup
      uses: actions/setup-python@v1
      run: |
        git submodule init 
        git submodule update 

      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python package
      run: pip install .

    - name: Install test dependencies
      run: pip install pytest

    - name: Run tests
      run: pytest python/tests
