name: Python

on:
  push:
    paths:
      - "pyproject.toml"
      - "python/**"
      - "include/reelay/**"
      - ".github/workflows/python.yml" # Self-trigger

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/doganulus/reelay-devel

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Reelay Python package
        run: pip install .

      - name: Install test dependencies
        run: pip install pytest

      # Configure in pyproject.toml
      - name: Run tests
        run: pytest
