name: python

on:
  push:
    paths:
    - 'python/**'
    - 'include/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y uuid-dev 
        sudo apt-get install -y libboost-all-dev
    - name: Install Reelay library
      run: |
        sudo make install
    - name: Install Python package
      run: make python
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run Tests
      run: pytest python/tests
