name: Run unit tests

on:
  workflow_dispatch:
  push:
    paths:
      - "include/reelay/**"
      - ".github/workflows/tests.yml" # Self-trigger

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/doganulus/reelay-devel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run unit tests
        run: make test
